### ISSUE TITLE
如何将checkpoint和模型整合？

### ISSUE THREAD

**Issue by Alexie-Z-Yevich** [modelscope/ms-swift#1697]
训练完之后在output中是有checkpoint文件夹，里面有不少配置文件。看了下加载方式是使用swift加载模型和ckpt来加载训练后的模型，如果我想用其他的框架加载，很多都没有ckpt那个参数，怎么进行一个整合呢？
直接copy ckpt里面的参数过去执行，启动会报错：
ERROR 08-14 13:30:34 worker_base.py:145] Error executing method load_model. This might cause deadlock in distributed execution.
ERROR 08-14 13:30:34 worker_base.py:145] Traceback (most recent call last):
ERROR 08-14 13:30:34 worker_base.py:145]   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 137, in execute_method
ERROR 08-14 13:30:34 worker_base.py:145]     return executor(*args, **kwargs)
ERROR 08-14 13:30:34 worker_base.py:145]   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/worker.py", line 118, in load_model
ERROR 08-14 13:30:34 worker_base.py:145]     self.model_runner.load_model()
ERROR 08-14 13:30:34 worker_base.py:145]   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 164, in load_model
ERROR 08-14 13:30:34 worker_base.py:145]     self.model = get_model(
ERROR 08-14 13:30:34 worker_base.py:145]   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
ERROR 08-14 13:30:34 worker_base.py:145]     return loader.load_model(model_config=model_config,
ERROR 08-14 13:30:34 worker_base.py:145]   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 224, in load_model
ERROR 08-14 13:30:34 worker_base.py:145]     model.load_weights(
ERROR 08-14 13:30:34 worker_base.py:145]   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 281, in load_weights
ERROR 08-14 13:30:34 worker_base.py:145]     param = params_dict[name]
ERROR 08-14 13:30:34 worker_base.py:145] KeyError: 'base_model.model.transformer.h.0.attn.c_attn.base_layer.lora_A.weight'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/qwen/code/vllm/server_vllm_weitiao.py", line 178, in <module>
[rank0]:     generation_config, tokenizer, stop_tokens, engine = model_load_vllm(args.model_path,
[rank0]:   File "/qwen/code/vllm/server_vllm_weitiao.py", line 44, in model_load_vllm
[rank0]:     engine = AsyncLLMEngine.from_engine_args(args)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 366, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 324, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 442, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 160, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 300, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 41, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 43, in _init_executor
[rank0]:     self._init_workers_ray(placement_group)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 165, in _init_workers_ray
[rank0]:     self._run_workers("load_model",
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 234, in _run_workers
[rank0]:     driver_worker_output = self.driver_worker.execute_method(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 146, in execute_method
[rank0]:     raise e
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 137, in execute_method
[rank0]:     return executor(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/worker.py", line 118, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 164, in load_model
[rank0]:     self.model = get_model(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 224, in load_model
[rank0]:     model.load_weights(
[rank0]:   File "/root/miniconda3/envs/swift/lib/python3.10/site-packages/vllm/model_executor/models/qwen.py", line 281, in load_weights
[rank0]:     param = params_dict[name]
[rank0]: KeyError: 'base_model.model.transformer.h.0.attn.c_attn.base_layer.lora_A.weight'
[rank0]:[W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

**Comment by Alexie-Z-Yevich** [comment]
已经解决，使用CUDA_VISIBLE_DEVICES=0 swift export  --ckpt_dir 'xxx/checkpoint-93' --merge_lora true合并模型，希望后续的文档能够简单提及😂，参考文档跟到最后还要去查接口
