### ISSUE TITLE
NPU环境推理报错ERR01004 OPS invalid pointer

### ISSUE THREAD

**Issue by liujiachang** [modelscope/ms-swift#2098]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

`swift infer --model_type qwen2-vl-7b-instruct --model_id_or_path models/Qwen2-VL-7B-Instruct`
![image](https://github.com/user-attachments/assets/6bfe096b-4408-46fd-941c-c55458cad088)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

昇腾910B+torch2.4.0rc1+Ascend8.0.rc1

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

推理qwen2系列模型时报错`RuntimeError: aclnnFusedInferAttentionScoreV2 or aclnnFusedInferAttentionScoreV2GetWorkspaceSize not in libopapi.so, or libopapi.sonot found.`

**Comment by Jintao-Huang** [comment]
--use_flash_attn false 试试

**Comment by liujiachang** [comment]
仍然报错，报错的内容与 #1951 相同

**Comment by zjukop** [comment]
@liujiachang 同样报错，请问解决了吗

**Comment by liujiachang** [comment]
> @liujiachang 同样报错，请问解决了吗

已解决，但我不确定这对你是否有效，我重新搭建了环境，降低了torch的版本，现在我的torch版本为：torch-npu                     2.3.1
