### ISSUE TITLE
华为昇腾910B上，单机8卡运行小模型Qwen2-0.5B-Base的RLHF算法，每次Saving model checkpoint后都会挂住

### ISSUE THREAD

**Issue by BigFishLi** [modelscope/ms-swift#2434]
环境信息：
华为昇腾910B，NPU驱动版本如下：
![image](https://github.com/user-attachments/assets/e9baf622-1e5f-4094-915e-1a7b21c59c1e)

 
ascend-toolkit版本：
cat /usr/local/Ascend/ascend-toolkit/latest/version.cfg
# version: 1.0
runtime_running_version=[7.3.0.1.231:8.0.RC2]
compiler_running_version=[7.3.0.1.231:8.0.RC2]
hccl_running_version=[7.3.0.1.231:8.0.RC2]
opp_running_version=[7.3.0.1.231:8.0.RC2]
toolkit_running_version=[7.3.0.1.231:8.0.RC2]
aoe_running_version=[7.3.0.1.231:8.0.RC2]
ncs_running_version=[7.3.0.1.231:8.0.RC2]
opp_kernel_running_version=[7.3.0.1.231:8.0.RC2]
runtime_upgrade_version=[7.3.0.1.231:8.0.RC2]
compiler_upgrade_version=[7.3.0.1.231:8.0.RC2]
hccl_upgrade_version=[7.3.0.1.231:8.0.RC2]
opp_upgrade_version=[7.3.0.1.231:8.0.RC2]
toolkit_upgrade_version=[7.3.0.1.231:8.0.RC2]
aoe_upgrade_version=[7.3.0.1.231:8.0.RC2]
ncs_upgrade_version=[7.3.0.1.231:8.0.RC2]
opp_kernel_upgrade_version=[7.3.0.1.231:8.0.RC2]
runtime_installed_version=[7.3.0.1.231:8.0.RC2]
compiler_installed_version=[7.3.0.1.231:8.0.RC2]
hccl_installed_version=[7.3.0.1.231:8.0.RC2]
opp_installed_version=[7.3.0.1.231:8.0.RC2]
toolkit_installed_version=[7.3.0.1.231:8.0.RC2]
aoe_installed_version=[7.3.0.1.231:8.0.RC2]
ncs_installed_version=[7.3.0.1.231:8.0.RC2]
opp_kernel_installed_version=[7.3.0.1.231:8.0.RC2]

ms-swift、transformers、trl版本如下：
 
![image](https://github.com/user-attachments/assets/b0983bf9-d4a9-4ce2-8773-0005fbd7479f)

问题描述：
1、	RLHF微调模型Qwen2-0.5B-Base，
NPU相关参数设置如下：
export GPU_NUM_PER_NODE=8
export ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export HCCL_CONNECT_TIMEOUT=120

RLHF相关参数设置如下：
    --lora_rank 64 \
    --lora_alpha 128 \
    --lora_dropout_p 0.01 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --weight_decay 0.1 \
    --max_grad_norm 1.0 \
    --warmup_ratio 0.03 \
    --save_total_limit 1 \
--save_strategy epoch
2、模型训练时，每次save checkpoint后都会报错，必现：
[INFO:swift] Saving model checkpoint to /data/lff/SwiftTelePatch/finetune/Qwen2-0.5B-Base/model/qwen2-0_5b/v0-20241112-105834/checkpoint-5
EI0006: 2024-11-12-11:01:11.856.890 Getting socket times out. Reason: Remote Rank did not send the data in time. Please check the reason for the rank being stuck
        Solution: 1. Check the rank service processes with other errors or no errors in the cluster.2. If this error is reported for all NPUs, check whether the time difference between the earliest and latest errors is greater than the connect timeout interval (120s by default). If so, adjust the timeout interval by using the HCCL_CONNECT_TIMEOUT environment variable.3. Check the connectivity of the communication link between nodes. (For details, see the TLS command and HCCN connectivity check examples.). For details:https://www.hiascend.com/document
        TraceBack (most recent call last):
        Transport init error. Reason: [Create][DestLink]Create Dest error! creakLink para:rank[2]-localUserrank[2]-localIpAddr[100.97.162.134], dst_rank[0]-remoteUserrank[0]-remote_ip_addr[100.97.162.134]

Traceback (most recent call last):
  File "/data/lff/SwiftTelePatch/./swifttelepatch/rlhf.py", line 7, in <module>
    rlhf_main()
  File "/data/lff/thirtparty/Swift-2.5.2-20241023@c87c5ee/swift/swift/utils/run_utils.py", line 32, in x_main
    result = llm_x(args, **kwargs)
  File "/data/lff/thirtparty/Swift-2.5.2-20241023@c87c5ee/swift/swift/llm/rlhf.py", line 47, in llm_rlhf
    return trainer_train(
  File "/data/lff/thirtparty/Swift-2.5.2-20241023@c87c5ee/swift/swift/llm/sft.py", line 495, in trainer_train
    trainer.train(training_args.resume_from_checkpoint)
  File "/data/lff/thirtparty/Swift-2.5.2-20241023@c87c5ee/swift/swift/trainers/mixin.py", line 488, in train
    res = super().train(resume_from_checkpoint, *args, **kwargs)
  File "/usr/local/python3.9.10/lib/python3.9/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/usr/local/python3.9.10/lib/python3.9/site-packages/transformers/trainer.py", line 2281, in _inner_training_loop
    if (
RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is HcclAllreduce.
Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, pleace set the environment variable ASCEND_LAUNCH_BLOCKING=1.
 
![image](https://github.com/user-attachments/assets/f776c38e-9247-47b2-aac6-3873ec2c3c00)

2、	修改NPU相关参数为单机4卡，就不会出现此问题
3、	找一个大模型，例如qwen2-72B。在8机8卡上也会出现同样的问题，但是在单机8卡就可以正常运行。  
和RLHF算法无关，只和模型大小和可用卡数有关。就是模型越小，就只能用单卡或双卡，8卡就一定会出现这个错误。

**Comment by BigFishLi** [comment]
在GPU环境上小模型使用单机多卡也会挂住。

环境信息：
![image](https://github.com/user-attachments/assets/1c511375-d0b8-4190-a021-85abaa5de300)

DPO训练参数
proc_per_node=1

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 \
NPROC_PER_NODE=$nproc_per_node \
MASTER_PORT=29500 \
swift dpo \
    --model_type  qwen2-0_5b \
    --model_revision  master \
    --model_id_or_path ${MODEL_DIR} \
    --sft_type  lora \
    --tuner_backend  swift \
    --dtype  AUTO  \
    --output_dir  output  \
    --dataset ${DPO_DATASET} \
    --custom_register_path ${CUSTOM_PY} \
    --num_train_epochs  10  \
    --max_length  1024  \
    --check_dataset_strategy  none  \
    --gradient_checkpointing  true  \
    --batch_size  1  \
    --weight_decay  0.1  \
    --learning_rate  5e-5  \
    --gradient_accumulation_steps  $(expr 16 / $nproc_per_node)  \
    --max_grad_norm  1.0  \
    --warmup_ratio  0.03  \
    --eval_steps  2000  \
    --save_steps  2000  \
    --save_total_limit  2  \
    --logging_steps  10 \

训练时也会报错：
![image](https://github.com/user-attachments/assets/d088ba64-9f53-4a1d-ae20-0984d732f87a)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices

在trl的项目中看到了这个问题，也没有解决。https://github.com/huggingface/trl/issues/1691

**Comment by matlab2017** [comment]
> 环境信息： 华为昇腾910B，NPU驱动版本如下： ![image](https://private-user-images.githubusercontent.com/46985317/385125666-e9baf622-1e5f-4094-915e-1a7b21c59c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDc2MDksIm5iZiI6MTczNDQwNzMwOSwicGF0aCI6Ii80Njk4NTMxNy8zODUxMjU2NjYtZTliYWY2MjItMWU1Zi00MDk0LTkxNWUtMWE3YjIxYzU5YzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjY2Q4MTE5MDRkNDY3MzYzMGEzMzU4NzUzMjAxMDJmMDA2MTI5NmQ1YTVkMzI3OGJkYTE2NDAyMWQ5Y2ZiOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sKMgk1bS7TmxFsMBd66VJ68nkoMS4KPZWGfu3qsn9wc)
> 
> ascend-toolkit版本： cat /usr/local/Ascend/ascend-toolkit/latest/version.cfg
> 
> # version: 1.0
> runtime_running_version=[7.3.0.1.231:8.0.RC2] compiler_running_version=[7.3.0.1.231:8.0.RC2] hccl_running_version=[7.3.0.1.231:8.0.RC2] opp_running_version=[7.3.0.1.231:8.0.RC2] toolkit_running_version=[7.3.0.1.231:8.0.RC2] aoe_running_version=[7.3.0.1.231:8.0.RC2] ncs_running_version=[7.3.0.1.231:8.0.RC2] opp_kernel_running_version=[7.3.0.1.231:8.0.RC2] runtime_upgrade_version=[7.3.0.1.231:8.0.RC2] compiler_upgrade_version=[7.3.0.1.231:8.0.RC2] hccl_upgrade_version=[7.3.0.1.231:8.0.RC2] opp_upgrade_version=[7.3.0.1.231:8.0.RC2] toolkit_upgrade_version=[7.3.0.1.231:8.0.RC2] aoe_upgrade_version=[7.3.0.1.231:8.0.RC2] ncs_upgrade_version=[7.3.0.1.231:8.0.RC2] opp_kernel_upgrade_version=[7.3.0.1.231:8.0.RC2] runtime_installed_version=[7.3.0.1.231:8.0.RC2] compiler_installed_version=[7.3.0.1.231:8.0.RC2] hccl_installed_version=[7.3.0.1.231:8.0.RC2] opp_installed_version=[7.3.0.1.231:8.0.RC2] toolkit_installed_version=[7.3.0.1.231:8.0.RC2] aoe_installed_version=[7.3.0.1.231:8.0.RC2] ncs_installed_version=[7.3.0.1.231:8.0.RC2] opp_kernel_installed_version=[7.3.0.1.231:8.0.RC2]
> 
> ms-swift、transformers、trl版本如下：
> 
> ![image](https://private-user-images.githubusercontent.com/46985317/385125705-b0983bf9-d4a9-4ce2-8773-0005fbd7479f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDc2MDksIm5iZiI6MTczNDQwNzMwOSwicGF0aCI6Ii80Njk4NTMxNy8zODUxMjU3MDUtYjA5ODNiZjktZDRhOS00Y2UyLTg3NzMtMDAwNWZiZDc0NzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MmY2MzQyMjIyYWE5ZDViZDgxZWM1YTNlOGU5ZThiNDA4NzlkYzlkMmVkMzIyM2JlZjhlZWE5NzY5NDg3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vuMJ2zmV1U_cGzr7jSyHqRu8Trp1BWROXtWhVjvZFvw)
> 
> 问题描述： 1、 RLHF微调模型Qwen2-0.5B-Base， NPU相关参数设置如下： export GPU_NUM_PER_NODE=8 export ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 export HCCL_CONNECT_TIMEOUT=120
> 
> RLHF相关参数设置如下： --lora_rank 64 --lora_alpha 128 --lora_dropout_p 0.01 --lora_target_modules ALL --gradient_checkpointing true --weight_decay 0.1 --max_grad_norm 1.0 --warmup_ratio 0.03 --save_total_limit 1 --save_strategy epoch 2、模型训练时，每次save checkpoint后都会报错，必现： [INFO:swift] Saving model checkpoint to /data/lff/SwiftTelePatch/finetune/Qwen2-0.5B-Base/model/qwen2-0_5b/v0-20241112-105834/checkpoint-5 EI0006: 2024-11-12-11:01:11.856.890 Getting socket times out. Reason: Remote Rank did not send the data in time. Please check the reason for the rank being stuck Solution: 1. Check the rank service processes with other errors or no errors in the cluster.2. If this error is reported for all NPUs, check whether the time difference between the earliest and latest errors is greater than the connect timeout interval (120s by default). If so, adjust the timeout interval by using the HCCL_CONNECT_TIMEOUT environment variable.3. Check the connectivity of the communication link between nodes. (For details, see the TLS command and HCCN connectivity check examples.). For details:https://www.hiascend.com/document TraceBack (most recent call last): Transport init error. Reason: [Create][DestLink]Create Dest error! creakLink para:rank[2]-localUserrank[2]-localIpAddr[100.97.162.134], dst_rank[0]-remoteUserrank[0]-remote_ip_addr[100.97.162.134]
> 
> Traceback (most recent call last): File "/data/lff/SwiftTelePatch/./swifttelepatch/rlhf.py", line 7, in rlhf_main() File "/data/lff/thirtparty/Swift-2.5.2-20241023@[c87c5ee](https://github.com/modelscope/ms-swift/commit/c87c5ee17f946be0669cd526bac68acfab38de9c)/swift/swift/utils/run_utils.py", line 32, in x_main result = llm_x(args, **kwargs) File "/data/lff/thirtparty/Swift-2.5.2-20241023@[c87c5ee](https://github.com/modelscope/ms-swift/commit/c87c5ee17f946be0669cd526bac68acfab38de9c)/swift/swift/llm/rlhf.py", line 47, in llm_rlhf return trainer_train( File "/data/lff/thirtparty/Swift-2.5.2-20241023@[c87c5ee](https://github.com/modelscope/ms-swift/commit/c87c5ee17f946be0669cd526bac68acfab38de9c)/swift/swift/llm/sft.py", line 495, in trainer_train trainer.train(training_args.resume_from_checkpoint) File "/data/lff/thirtparty/Swift-2.5.2-20241023@[c87c5ee](https://github.com/modelscope/ms-swift/commit/c87c5ee17f946be0669cd526bac68acfab38de9c)/swift/swift/trainers/mixin.py", line 488, in train res = super().train(resume_from_checkpoint, *args, **kwargs) File "/usr/local/python3.9.10/lib/python3.9/site-packages/transformers/trainer.py", line 1938, in train return inner_training_loop( File "/usr/local/python3.9.10/lib/python3.9/site-packages/transformers/trainer.py", line 2281, in _inner_training_loop if ( RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is HcclAllreduce. Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, pleace set the environment variable ASCEND_LAUNCH_BLOCKING=1.
> 
> ![image](https://private-user-images.githubusercontent.com/46985317/385125755-f776c38e-9247-47b2-aac6-3873ec2c3c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDc2MDksIm5iZiI6MTczNDQwNzMwOSwicGF0aCI6Ii80Njk4NTMxNy8zODUxMjU3NTUtZjc3NmMzOGUtOTI0Ny00N2IyLWFhYzYtMzg3M2VjMmMzYzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAzNDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlODE1YzhkODQ0MWU4OTdjOGMwMWQ0OTQ3YmM0ZTZjNTMwNTc5NThlMzcxOTRiNzEzMWI5ODIxZTMzYTYyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eT6G0nVTfc506MmbCopc6SlNZsWIUUUvz7ImYeaH__Y)
> 
> 2、 修改NPU相关参数为单机4卡，就不会出现此问题 3、 找一个大模型，例如qwen2-72B。在8机8卡上也会出现同样的问题，但是在单机8卡就可以正常运行。 和RLHF算法无关，只和模型大小和可用卡数有关。就是模型越小，就只能用单卡或双卡，8卡就一定会出现这个错误。


hello,请问你分布式训练32B 72B这种有设置device_map吗
