### ISSUE TITLE
单服务器双4090微调qwen2.5-14B-Instruct成功，多机多卡2台服务器4张4090微调启动失败，CUDA out of memory

### ISSUE THREAD

**Issue by HanJu-Chen** [modelscope/ms-swift#2715]
单机多卡启动cli：
CUDA_VISIBLE_DEVICES=0,1 \
swift sft \
      --torch_dtype bfloat16 \      
      --model /home/cache/Qwen2___5-14B-Instruct \
      --model_type qwen2_5 \
      --template qwen2_5 \
      --dataset swift/self-cognition \ 
      --max_length 1024 \
      --lora_rank 32 \
      --lora_alpha 8 \      
      --init_weights True \
      --learning_rate 1e-4 \
      --attn_impl flash_attn \
      --gradient_accumulation_steps 16 \
      --eval_steps 500 \
      --output_dir /home/cache/output/v10-20241220-110008 \
      --add_version False \
      --output_dir /home/cache/output/v10-20241220-110008/v0-20241220-110057 \
      --logging_dir /home/cache/output/v10-20241220-110008/v0-20241220-110057/runs

多机多卡启动cli：
CUDA_VISIBLE_DEVICES=0,1 \
NNODES=2 \
NODE_RANK=0 \
MASTER_ADDR=..... \
NPROC_PER_NODE=2 \
swift sft \
      --model /home/cache/Qwen2___5-14B-Instruct \
      --model_type qwen2_5 \
      --template qwen2_5 \
      --train_type lora \
      --torch_dtype bfloat16 \
      --dataset swift/self-cognition#1000 \
      --num_train_epochs 100 \
      --attn_impl 'flash_attn' \
      --max_length '1024' \
      --lora_rank 8 \
      --lora_alpha 32 \
      --init_weights 'True' \
      --learning_rate 1e-4 \
      --gradient_accumulation_steps 16 \
      --eval_steps 500 \
      --save_steps 500 \
      --save_total_limit 2 \
      --output_dir /home/cache/output \
      --logging_steps 5 \
      --model_name swift \
      --model_author swift \
      --add_version False

启动命令应该是没问题的，我测试过多机多卡微调qwen2.5-3B模型，可以成功训练。

我的疑问是为什么2张4090能训练14B。但是2台服务器4张4090就报错，CUDA out of memory了。
![Snipaste_2024-12-20_11-19-52](https://github.com/user-attachments/assets/9b4b9ae4-4134-43a8-92fb-3f2153b38e7e)

**Comment by Jintao-Huang** [comment]
--deepspeed zero2

**Comment by HanJu-Chen** [comment]
> --deepspeed zero3

当使用了--deepspeed zero3参数后，我现在的启动命令是：
# node0
CUDA_VISIBLE_DEVICES=0,1 \
NNODES=2 \
NODE_RANK=0 \
MASTER_ADDR=192.168.3.11 \
NPROC_PER_NODE=2 \
swift sft \
      --model /home/cache/Qwen2___5-14B-Instruct \
      --model_type qwen2_5 \
      --template qwen2_5 \
      --train_type lora \
      --torch_dtype bfloat16 \
      --dataset swift/self-cognition#1000 \
      --num_train_epochs 100 \
      --attn_impl 'flash_attn' \
      --max_length '1024' \
      --lora_rank 32 \
      --lora_alpha 8 \
      --init_weights 'True' \
      --learning_rate 1e-4 \
      --gradient_accumulation_steps 16 \
      --eval_steps 500 \
      --output_dir /home/cache/output \
      --logging_steps 5 \
      --model_name 小依 \
      --model_author 小依 \
      --deepspeed zero3
      
# node1
CUDA_VISIBLE_DEVICES=0,1 \
NNODES=2 \
NODE_RANK=1 \
MASTER_ADDR=192.168.3.11 \
NPROC_PER_NODE=2 \
swift sft \
      --model /home/cache/Qwen2___5-14B-Instruct \
      --model_type qwen2_5 \
      --template qwen2_5 \
      --train_type lora \
      --torch_dtype bfloat16 \
      --dataset swift/self-cognition#1000 \
      --num_train_epochs 100 \
      --attn_impl 'flash_attn' \
      --max_length '1024' \
      --lora_rank 32 \
      --lora_alpha 8 \
      --init_weights 'True' \
      --learning_rate 1e-4 \
      --gradient_accumulation_steps 16 \
      --eval_steps 500 \
      --output_dir /home/cache/output \
      --logging_steps 5 \
      --model_name 小依 \
      --model_author 小依 \
      --deepspeed zero3

现在使用上面两个命令，成功启动分布式训练了。但初始加载速度特别慢。

[INFO] [partition_parameters.py:348:__exit__] finished initializing model - num_params = 579, num_elems = 14.77B
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████| 8/8 [11:17<00:00, 84.73s/it]

**Comment by HanJu-Chen** [comment]
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/newuser/ms-swift/swift/cli/sft.py", line 5, in <module>
[rank1]:     sft_main()
[rank1]:   File "/home/newuser/ms-swift/swift/llm/train/sft.py", line 272, in sft_main
[rank1]:     return SwiftSft(args).main()
[rank1]:   File "/home/newuser/ms-swift/swift/llm/base.py", line 45, in main
[rank1]:     result = self.run()
[rank1]:   File "/home/newuser/ms-swift/swift/llm/train/sft.py", line 139, in run
[rank1]:     return self.train(trainer)
[rank1]:   File "/home/newuser/ms-swift/swift/llm/train/sft.py", line 191, in train
[rank1]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank1]:   File "/home/newuser/ms-swift/swift/trainers/mixin.py", line 261, in train
[rank1]:     return super().train(*args, **kwargs)
[rank1]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2480, in _inner_training_loop
[rank1]:     with context():
[rank1]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/contextlib.py", line 135, in __enter__
[rank1]:     return next(self.gen)
[rank1]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/accelerator.py", line 983, in no_sync
[rank1]:     with context():
[rank1]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/contextlib.py", line 135, in __enter__
[rank1]:     return next(self.gen)
[rank1]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2000, in no_sync
[rank1]:     assert not self.zero_optimization_partition_gradients(), \
[rank1]: AssertionError: no_sync context manager is incompatible with gradient partitioning logic of ZeRO stage 3
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/newuser/ms-swift/swift/cli/sft.py", line 5, in <module>
[rank0]:     sft_main()
[rank0]:   File "/home/newuser/ms-swift/swift/llm/train/sft.py", line 272, in sft_main
[rank0]:     return SwiftSft(args).main()
[rank0]:   File "/home/newuser/ms-swift/swift/llm/base.py", line 45, in main
[rank0]:     result = self.run()
[rank0]:   File "/home/newuser/ms-swift/swift/llm/train/sft.py", line 139, in run
[rank0]:     return self.train(trainer)
[rank0]:   File "/home/newuser/ms-swift/swift/llm/train/sft.py", line 191, in train
[rank0]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank0]:   File "/home/newuser/ms-swift/swift/trainers/mixin.py", line 261, in train
[rank0]:     return super().train(*args, **kwargs)
[rank0]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2123, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2480, in _inner_training_loop
[rank0]:     with context():
[rank0]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/contextlib.py", line 135, in __enter__
[rank0]:     return next(self.gen)
[rank0]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/accelerate/accelerator.py", line 983, in no_sync
[rank0]:     with context():
[rank0]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/contextlib.py", line 135, in __enter__
[rank0]:     return next(self.gen)
[rank0]:   File "/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2000, in no_sync
[rank0]:     assert not self.zero_optimization_partition_gradients(), \
[rank0]: AssertionError: no_sync context manager is incompatible with gradient partitioning logic of ZeRO stage 3


0.16.3版本Deepspeed也有问题。试过降级到0.15.4，不报no_sync错误了，又有其他错误。

**Comment by HanJu-Chen** [comment]
[1/3] /usr/local/cuda-12.1/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_adam.cuda.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/include -isystem /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/include/TH -isystem /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-12.1/include -isystem /home/newuser/anaconda3/envs/swift/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -std=c++17 -c /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
[2/3] c++ -MMD -MF fused_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/include -isystem /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/include/TH -isystem /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-12.1/include -isystem /home/newuser/anaconda3/envs/swift/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DBF16_AVAILABLE -c /home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp -o fused_adam_frontend.o 
[3/3] c++ fused_adam_frontend.o multi_tensor_adam.cuda.o -shared -L/home/newuser/anaconda3/envs/swift/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda-12.1/lib64 -lcudart -o fused_adam.so
Loading extension module fused_adam...
Time to load fused_adam op: 12.948566913604736 seconds
Loading extension module fused_adam...
Time to load fused_adam op: 13.03340768814087 seconds
Parameter Offload: Total persistent parameters: 19321856 in 769 params
[2024-12-24 16:23:14,503] [WARNING] [lr_schedules.py:855:get_lr] Attempting to get learning rate from scheduler before it has started
[2024-12-24 16:23:14,713] [WARNING] [lr_schedules.py:855:get_lr] Attempting to get learning rate from scheduler before it has started
Train:   0%|                                                                | 0/15 [00:00<?, ?it/s]


Deepspeed问题解决了，然后又卡死在了train步骤

**Comment by Jintao-Huang** [comment]
用deepspeed 0.14.5试试

**Comment by jun0403** [comment]
我是用4张4090微调，会爆显存，请问知道这个问题吗？命令如下
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
GPUS_PER_NODE=4
CUDA_VISIBLE_DEVICES=0,1,2,3 \
 swift sft \
    --model /root/.cache/modelscope/hub/Qwen/Qwen2-VL-2B-Instruct \
    --train_type lora \
    --torch_dtype bfloat16 \
    --dataset /root/data/data.json \
    --num_train_epochs 1 \
    --max_length 1024 \
    --per_device_train_batch_size 1 \
    --learning_rate 1e-4 \
    --lora_rank 4 \
    --lora_alpha 32 \
    --gradient_accumulation_steps 16 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 5 
报错信息如下：
Traceback (most recent call last):
  File "/root/LLaMA-Factory/ms-swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/root/LLaMA-Factory/ms-swift/swift/llm/train/sft.py", line 257, in sft_main
    return SwiftSft(args).main()
  File "/root/LLaMA-Factory/ms-swift/swift/llm/base.py", line 46, in main
    result = self.run()
  File "/root/LLaMA-Factory/ms-swift/swift/llm/train/sft.py", line 137, in run
    return self.train(trainer)
  File "/root/LLaMA-Factory/ms-swift/swift/llm/train/sft.py", line 196, in train
    trainer.train(trainer.args.resume_from_checkpoint)
  File "/root/LLaMA-Factory/ms-swift/swift/trainers/mixin.py", line 261, in train
    res = super().train(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2171, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2531, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 3675, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
  File "/root/LLaMA-Factory/ms-swift/swift/trainers/trainers.py", line 199, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1845, in _call_impl
    return inner()
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1772, in inner
    args_kwargs_result = hook(self, args, kwargs)  # type: ignore[misc]
  File "/root/LLaMA-Factory/ms-swift/swift/llm/template/base.py", line 837, in pre_forward_hook
    kwargs = to_device(self._post_encode(model, old_kwargs), model.device)
  File "/root/LLaMA-Factory/ms-swift/swift/llm/template/template/qwen.py", line 281, in _post_encode
    image_embeds = model.visual(pixel_values, grid_thw=image_grid_thw)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1009, in forward
    hidden_states = self._gradient_checkpointing_func(
  File "/root/LLaMA-Factory/ms-swift/swift/trainers/arguments.py", line 49, in _new_checkpoint
    return _old_checkpoint(*args, use_reentrant=use_reentrant_, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_compile.py", line 32, in inner
    return disable_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 489, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 264, in forward
    outputs = run_function(*args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 426, in forward
    hidden_states = hidden_states + self.attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 399, in forward
    attn_output = F.scaled_dot_product_attention(q, k, v, attention_mask, dropout_p=0.0)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 13.28 GiB. GPU 0 has a total capacity of 23.65 GiB of which 7.61 GiB is free. Process 2110187 has 16.03 GiB memory in use. Of the allocated memory 15.43 GiB is allocated by PyTorch, and 154.40 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by WellWang-S** [comment]
你用的是官方镜像吗 我多机多卡训练卡住了，求解

[2025-03-18 10:21:52,520] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-03-18 10:21:52,528] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-03-18 10:21:52,534] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-03-18 10:21:52,549] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-03-18 10:21:52,646] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-03-18 10:21:52,659] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-03-18 10:21:52,700] [INFO] [comm.py:652:init_distributed] cdb=None
