### ISSUE TITLE
swift3 qwen2-vl 72b vllm推理The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 51791).

### ISSUE THREAD

**Issue by munian08** [modelscope/ms-swift#3138]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
swift3 vllm推理qwen2-vl-72b出现以下报错torch.distributed.DistNetworkError: The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 51791).

<img width="1884" alt="Image" src="https://github.com/user-attachments/assets/ed6c4ec2-183f-4b53-965e-bf789c521950" />

之前用swift2+vllm推理也遇到过这个问题，是通过export VLLM_HOST_IP="127.0.0.1"解决的，但是对于swift3来说不起作用

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
torch 2.5.1
cuda 12.3.2
vllm 0.7.2
swift 3.1.0
transformer 4.49.0.dev0
flash_attn 2.7.2.post1
pynvml 12.0.0

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
报错脚本：
```
export VLLM_HOST_IP="127.0.0.1"

nproc_per_node=8
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
NPROC_PER_NODE=$nproc_per_node \
MAX_PIXELS=602112 \
swift infer \
    --model /workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged \
    --infer_backend vllm \
    --val_dataset 'test.jsonl' \
    --gpu_memory_utilization 0.9 \
    --limit_mm_per_prompt '{"image": 8}' \
    --tensor_parallel_size $nproc_per_node
```

**Comment by munian08** [comment]
报错日志：
```
run sh: `/usr/bin/python -m torch.distributed.run --nproc_per_node 8 --master_port 23456 --master_addr qs-18721-511647-master-0 /env/swift/ms-swift-3.0.3.dev/swift/cli/infer.py --model /workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged --infer_backend vllm --val_dataset /dataset/test/xml_market_xmlreason_test_1w_final_img8.jsonl --gpu_memory_utilization 0.9 --limit_mm_per_prompt {"image": 8} --tensor_parallel_size 8`
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[INFO:swift] Successfully registered `/env/swift/ms-swift-3.0.3.dev/swift/llm/dataset/data/dataset_info.json`
[INFO:swift] Successfully loaded /workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged/args.json.
[INFO:swift] rank: 0, local_rank: 0, world_size: 8, local_world_size: 8
[INFO:swift] Loading the model using model_dir: /workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged
[INFO:swift] Because len(args.val_dataset) > 0, setting split_dataset_ratio: 0.0
[INFO:swift] args.result_path: /workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged/infer_result/20250217-051037.jsonl
[INFO:swift] Setting args.eval_human: False
[INFO:swift] Global seed set to 42
[INFO:swift] args: InferArguments(model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', model_type='qwen2_vl', model_revision=None, task_type='causal_lm', torch_dtype=torch.bfloat16, attn_impl='flash_attn', num_labels=None, rope_scaling=None, device_map=None, local_repo_path=None, template='qwen2_vl', system=None, max_length=None, truncation_strategy='delete', max_pixels=None, tools_prompt='react_en', norm_bbox=None, padding_side='right', loss_scale='default', sequence_parallel_size=1, use_chat_template=True, template_backend='swift', dataset=[], val_dataset=['/dataset/test/xml_market_xmlreason_test_1w_final_img8.jsonl'], split_dataset_ratio=0.0, data_seed=42, dataset_num_proc=1, streaming=False, enable_cache=False, download_mode='reuse_dataset_if_exists', columns={}, strict=False, model_name=[None, None], model_author=[None, None], custom_dataset_info=[], quant_method=None, quant_bits=None, hqq_axis=None, bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, bnb_4bit_quant_storage=None, max_new_tokens=None, temperature=None, top_k=None, top_p=None, repetition_penalty=None, num_beams=1, stream=False, stop_words=[], logprobs=False, top_logprobs=None, ckpt_dir='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', load_dataset_config=None, lora_modules=[], tuner_backend='peft', train_type='lora', adapters=[], seed=42, model_kwargs={}, load_args=True, load_data_args=False, use_hf=False, hub_token=None, custom_register_path=[], ignore_args_error=False, use_swift_lora=False, tp=1, session_len=None, cache_max_entry_count=0.8, quant_policy=0, vision_batch_size=1, gpu_memory_utilization=0.9, tensor_parallel_size=8, pipeline_parallel_size=1, max_num_seqs=256, max_model_len=None, disable_custom_all_reduce=False, enforce_eager=False, limit_mm_per_prompt={'image': 8}, vllm_max_lora_rank=16, enable_prefix_caching=False, merge_lora=False, safe_serialization=True, max_shard_size='5GB', infer_backend='vllm', result_path='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged/infer_result/20250217-051037.jsonl', metric=None, max_batch_size=1, ddp_backend=None, val_dataset_sample=None)
INFO 02-17 05:10:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:10:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:10:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:10:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:10:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:10:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:10:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:10:39 __init__.py:190] Automatically detected platform cuda.
[INFO:swift] Loading the model using model_dir: /workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged
[INFO:swift] Setting image_factor: 28. You can adjust this hyperparameter through the environment variable: `IMAGE_FACTOR`.
[INFO:swift] Setting min_pixels: 3136. You can adjust this hyperparameter through the environment variable: `MIN_PIXELS`.
[INFO:swift] Using environment variable `MAX_PIXELS`, Setting max_pixels: 602112.
[INFO:swift] Setting max_ratio: 200. You can adjust this hyperparameter through the environment variable: `MAX_RATIO`.
[INFO:swift] Setting video_min_pixels: 100352. You can adjust this hyperparameter through the environment variable: `VIDEO_MIN_PIXELS`.
[INFO:swift] Setting video_max_pixels: 602112. You can adjust this hyperparameter through the environment variable: `VIDEO_MAX_PIXELS`.
[INFO:swift] Setting video_total_pixels: 90316800. You can adjust this hyperparameter through the environment variable: `VIDEO_TOTAL_PIXELS`.
[INFO:swift] Setting frame_factor: 2. You can adjust this hyperparameter through the environment variable: `FRAME_FACTOR`.
[INFO:swift] Setting fps: 2.0. You can adjust this hyperparameter through the environment variable: `FPS`.
[INFO:swift] Setting fps_min_frames: 4. You can adjust this hyperparameter through the environment variable: `FPS_MIN_FRAMES`.
[INFO:swift] Setting fps_max_frames: 768. You can adjust this hyperparameter through the environment variable: `FPS_MAX_FRAMES`.
INFO 02-17 05:11:06 config.py:542] This model supports multiple tasks: {'reward', 'classify', 'score', 'embed', 'generate'}. Defaulting to 'generate'.
INFO 02-17 05:11:06 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-17 05:11:06 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', speculative_config=None, tokenizer='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
INFO 02-17 05:11:06 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-17 05:11:08 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:10 config.py:542] This model supports multiple tasks: {'score', 'classify', 'reward', 'generate', 'embed'}. Defaulting to 'generate'.
INFO 02-17 05:11:10 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-17 05:11:10 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', speculative_config=None, tokenizer='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
INFO 02-17 05:11:10 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-17 05:11:11 config.py:542] This model supports multiple tasks: {'reward', 'embed', 'generate', 'classify', 'score'}. Defaulting to 'generate'.
INFO 02-17 05:11:11 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-17 05:11:11 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', speculative_config=None, tokenizer='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
INFO 02-17 05:11:11 config.py:542] This model supports multiple tasks: {'generate', 'reward', 'score', 'embed', 'classify'}. Defaulting to 'generate'.
INFO 02-17 05:11:11 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-17 05:11:11 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', speculative_config=None, tokenizer='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
INFO 02-17 05:11:11 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-17 05:11:11 config.py:542] This model supports multiple tasks: {'embed', 'score', 'reward', 'classify', 'generate'}. Defaulting to 'generate'.
INFO 02-17 05:11:11 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-17 05:11:11 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', speculative_config=None, tokenizer='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
INFO 02-17 05:11:11 config.py:542] This model supports multiple tasks: {'classify', 'score', 'reward', 'embed', 'generate'}. Defaulting to 'generate'.
INFO 02-17 05:11:11 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-17 05:11:11 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', speculative_config=None, tokenizer='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
INFO 02-17 05:11:11 config.py:542] This model supports multiple tasks: {'score', 'reward', 'classify', 'generate', 'embed'}. Defaulting to 'generate'.
INFO 02-17 05:11:11 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-17 05:11:11 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-17 05:11:11 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', speculative_config=None, tokenizer='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
INFO 02-17 05:11:11 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-17 05:11:11 config.py:542] This model supports multiple tasks: {'embed', 'classify', 'generate', 'reward', 'score'}. Defaulting to 'generate'.
INFO 02-17 05:11:11 config.py:1401] Defaulting to use mp for distributed inference
INFO 02-17 05:11:11 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-17 05:11:11 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', speculative_config=None, tokenizer='/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
INFO 02-17 05:11:11 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:11 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-17 05:11:11 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 02-17 05:11:12 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:12 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:12 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:12 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:12 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:12 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:24 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:24 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:25 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:25 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:25 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:25 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:25 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:27 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=543) INFO 02-17 05:11:28 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=546) INFO 02-17 05:11:29 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=540) INFO 02-17 05:11:29 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=545) INFO 02-17 05:11:29 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=541) INFO 02-17 05:11:29 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=544) INFO 02-17 05:11:29 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=542) INFO 02-17 05:11:29 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=543) INFO 02-17 05:11:30 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=567) INFO 02-17 05:11:31 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=546) INFO 02-17 05:11:31 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=540) INFO 02-17 05:11:31 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:31 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=545) INFO 02-17 05:11:31 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:32 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=541) INFO 02-17 05:11:32 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=542) INFO 02-17 05:11:32 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=544) INFO 02-17 05:11:32 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=567) INFO 02-17 05:11:34 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:36 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:37 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:37 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:38 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:39 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:39 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=565) INFO 02-17 05:11:41 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
INFO 02-17 05:11:43 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:43 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:44 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=569) INFO 02-17 05:11:44 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
INFO 02-17 05:11:44 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=565) INFO 02-17 05:11:44 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:45 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:45 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:45 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:45 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=587) INFO 02-17 05:11:45 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=564) INFO 02-17 05:11:45 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=566) INFO 02-17 05:11:45 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=570) INFO 02-17 05:11:46 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=568) INFO 02-17 05:11:46 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
INFO 02-17 05:11:46 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=615) INFO 02-17 05:11:46 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=569) INFO 02-17 05:11:46 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=604) INFO 02-17 05:11:46 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=586) INFO 02-17 05:11:46 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=585) INFO 02-17 05:11:46 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
INFO 02-17 05:11:46 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:46 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=637) INFO 02-17 05:11:46 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=633) INFO 02-17 05:11:46 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=617) INFO 02-17 05:11:47 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=587) INFO 02-17 05:11:47 cuda.py:230] Using Flash Attention backend.
[INFO:swift] Successfully registered `/env/swift/ms-swift-3.0.3.dev/swift/llm/dataset/data/dataset_info.json`
(VllmWorkerProcess pid=564) INFO 02-17 05:11:47 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=566) INFO 02-17 05:11:47 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=568) INFO 02-17 05:11:47 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=570) INFO 02-17 05:11:47 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=615) INFO 02-17 05:11:48 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=604) INFO 02-17 05:11:48 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=581) INFO 02-17 05:11:48 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=586) INFO 02-17 05:11:48 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=634) INFO 02-17 05:11:48 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=584) INFO 02-17 05:11:48 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=599) INFO 02-17 05:11:48 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[INFO:swift] Successfully registered `/env/swift/ms-swift-3.0.3.dev/swift/llm/dataset/data/dataset_info.json`
(VllmWorkerProcess pid=637) INFO 02-17 05:11:48 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=585) INFO 02-17 05:11:48 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=633) INFO 02-17 05:11:48 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=617) INFO 02-17 05:11:48 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=635) INFO 02-17 05:11:49 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
INFO 02-17 05:11:49 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:49 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=582) INFO 02-17 05:11:49 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=583) INFO 02-17 05:11:49 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[INFO:swift] Successfully registered `/env/swift/ms-swift-3.0.3.dev/swift/llm/dataset/data/dataset_info.json`
(VllmWorkerProcess pid=581) INFO 02-17 05:11:49 cuda.py:230] Using Flash Attention backend.
[INFO:swift] Successfully registered `/env/swift/ms-swift-3.0.3.dev/swift/llm/dataset/data/dataset_info.json`
INFO 02-17 05:11:50 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=634) INFO 02-17 05:11:50 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=584) INFO 02-17 05:11:50 cuda.py:230] Using Flash Attention backend.
[INFO:swift] Successfully registered `/env/swift/ms-swift-3.0.3.dev/swift/llm/dataset/data/dataset_info.json`
(VllmWorkerProcess pid=599) INFO 02-17 05:11:50 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:50 __init__.py:190] Automatically detected platform cuda.
[INFO:swift] Successfully registered `/env/swift/ms-swift-3.0.3.dev/swift/llm/dataset/data/dataset_info.json`
[INFO:swift] Successfully registered `/env/swift/ms-swift-3.0.3.dev/swift/llm/dataset/data/dataset_info.json`
INFO 02-17 05:11:51 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=635) INFO 02-17 05:11:51 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=582) INFO 02-17 05:11:51 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:51 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:51 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=583) INFO 02-17 05:11:52 cuda.py:230] Using Flash Attention backend.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:52 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:53 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:53 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:53 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:53 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:53 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:53 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:54 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:54 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:54 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:54 __init__.py:190] Automatically detected platform cuda.
INFO 02-17 05:11:54 __init__.py:190] Automatically detected platform cuda.
(VllmWorkerProcess pid=670) INFO 02-17 05:11:54 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=654) INFO 02-17 05:11:54 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=598) INFO 02-17 05:11:55 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=651) INFO 02-17 05:11:56 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=670) INFO 02-17 05:11:56 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=654) INFO 02-17 05:11:56 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=636) INFO 02-17 05:11:56 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=601) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=618) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=671) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=638) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=653) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=666) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=668) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=651) INFO 02-17 05:11:57 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=598) INFO 02-17 05:11:57 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=616) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=621) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=649) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=620) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=669) INFO 02-17 05:11:57 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=636) INFO 02-17 05:11:57 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=632) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=600) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=667) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=650) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=603) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=619) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=655) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=618) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=602) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=672) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=601) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=671) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=652) INFO 02-17 05:11:58 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
(VllmWorkerProcess pid=638) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=653) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=668) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=666) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=616) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=621) INFO 02-17 05:11:58 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=649) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=620) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=669) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=667) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=600) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=632) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=619) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=650) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=603) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=602) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=655) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=672) INFO 02-17 05:11:59 cuda.py:230] Using Flash Attention backend.
(VllmWorkerProcess pid=652) INFO 02-17 05:12:00 cuda.py:230] Using Flash Attention backend.
[E217 05:20:41.646850027 socket.cpp:1011] [c10d] The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 41903).
[W217 05:20:41.647750188 TCPStore.cpp:358] [c10d] TCP client failed to connect/validate to host 127.0.0.1:41903 - retrying (try=0, timeout=600000ms, delay=37980ms): The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 41903).
Exception raised from throwTimeoutError at ../torch/csrc/distributed/c10d/socket.cpp:1013 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7ff579b6c446 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x15e04c6 (0x7ff5649e04c6 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x6029d95 (0x7ff569429d95 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6029f36 (0x7ff569429f36 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x602a3a4 (0x7ff56942a3a4 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x5fe8016 (0x7ff5693e8016 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::string, c10d::TCPStoreOptions const&) + 0x20c (0x7ff5693eaf7c in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xd9acdd (0x7ff578f9acdd in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x4cb474 (0x7ff5786cb474 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x15a10e (0x55f6a4b5a10e in /usr/bin/python)
frame #10: _PyObject_MakeTpCall + 0x25b (0x55f6a4b50a7b in /usr/bin/python)
frame #11: <unknown function> + 0x168c20 (0x55f6a4b68c20 in /usr/bin/python)
frame #12: <unknown function> + 0x165087 (0x55f6a4b65087 in /usr/bin/python)
frame #13: <unknown function> + 0x150e2b (0x55f6a4b50e2b in /usr/bin/python)
frame #14: <unknown function> + 0x4c9ccb (0x7ff5786c9ccb in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #15: _PyObject_MakeTpCall + 0x25b (0x55f6a4b50a7b in /usr/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x64e6 (0x55f6a4b49096 in /usr/bin/python)
frame #17: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x6bd (0x55f6a4b4326d in /usr/bin/python)
frame #19: <unknown function> + 0x200175 (0x55f6a4c00175 in /usr/bin/python)
frame #20: <unknown function> + 0x15ac59 (0x55f6a4b5ac59 in /usr/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x6bd (0x55f6a4b4326d in /usr/bin/python)
frame #22: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #23: PyObject_Call + 0x122 (0x55f6a4b69492 in /usr/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x2a27 (0x55f6a4b455d7 in /usr/bin/python)
frame #25: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #26: PyObject_Call + 0x122 (0x55f6a4b69492 in /usr/bin/python)
frame #27: _PyEval_EvalFrameDefault + 0x2a27 (0x55f6a4b455d7 in /usr/bin/python)
frame #28: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x198c (0x55f6a4b4453c in /usr/bin/python)
frame #30: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x6bd (0x55f6a4b4326d in /usr/bin/python)
frame #32: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x6bd (0x55f6a4b4326d in /usr/bin/python)
frame #34: <unknown function> + 0x168a51 (0x55f6a4b68a51 in /usr/bin/python)
frame #35: _PyEval_EvalFrameDefault + 0x2a27 (0x55f6a4b455d7 in /usr/bin/python)
frame #36: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x6bd (0x55f6a4b4326d in /usr/bin/python)
frame #38: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #39: PyObject_Call + 0x122 (0x55f6a4b69492 in /usr/bin/python)
frame #40: _PyEval_EvalFrameDefault + 0x2a27 (0x55f6a4b455d7 in /usr/bin/python)
frame #41: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #42: _PyEval_EvalFrameDefault + 0x8ac (0x55f6a4b4345c in /usr/bin/python)
frame #43: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #44: _PyEval_EvalFrameDefault + 0x8ac (0x55f6a4b4345c in /usr/bin/python)
frame #45: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #46: _PyEval_EvalFrameDefault + 0x6bd (0x55f6a4b4326d in /usr/bin/python)
frame #47: _PyFunction_Vectorcall + 0x7c (0x55f6a4b5a9fc in /usr/bin/python)
frame #48: _PyEval_EvalFrameDefault + 0x198c (0x55f6a4b4453c in /usr/bin/python)
frame #49: <unknown function> + 0x13f9c6 (0x55f6a4b3f9c6 in /usr/bin/python)
frame #50: PyEval_EvalCode + 0x86 (0x55f6a4c35256 in /usr/bin/python)
frame #51: <unknown function> + 0x260108 (0x55f6a4c60108 in /usr/bin/python)
frame #52: <unknown function> + 0x2599cb (0x55f6a4c599cb in /usr/bin/python)
frame #53: PyRun_StringFlags + 0x81 (0x55f6a4c52ab1 in /usr/bin/python)
frame #54: PyRun_SimpleStringFlags + 0x41 (0x55f6a4c52961 in /usr/bin/python)
frame #55: Py_RunMain + 0x375 (0x55f6a4c51b15 in /usr/bin/python)
frame #56: Py_BytesMain + 0x2d (0x55f6a4c2802d in /usr/bin/python)
frame #57: <unknown function> + 0x29d90 (0x7ff57a629d90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #58: __libc_start_main + 0x80 (0x7ff57a629e40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #59: _start + 0x25 (0x55f6a4c27f25 in /usr/bin/python)
```

**Comment by TimeLessLing** [comment]
我也遇到了相同的问题，请问楼主现在解决了吗？

**Comment by munian08** [comment]
> 我也遇到了相同的问题，请问楼主现在解决了吗？

我换成swift2.7推理了，vllm0.6.5+swift2.7是可以的

推理脚本
```
# swift infer
export VLLM_HOST_IP="127.0.0.1"

nproc_per_node=8
MIN_PIXELS=50176 MAX_PIXELS=602112 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 NPROC_PER_NODE=$nproc_per_node swift infer \
    --model_type qwen2-vl-72b-instruct \
    --model_id_or_path "/workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged" \
    --val_dataset test.jsonl \
    --tensor_parallel_size $nproc_per_node \
    --gpu_memory_utilization 0.9 \
    --use_flash_attn True \
    --infer_backend vllm \
    --limit-mm-per-prompt '{"image": 8}'
```

**Comment by munian08** [comment]
@Jintao-Huang 大佬 能麻烦看一下这个问题吗 还没解决😭

**Comment by Jintao-Huang** [comment]
swift3.2嘛

**Comment by Jintao-Huang** [comment]
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
MAX_PIXELS=602112 \
swift infer \
    --model /workspace/swift3/output/Qwen2-VL-72B-Instruct/v1-20250213-024958/checkpoint-612-merged \
    --infer_backend vllm \
    --val_dataset 'test.jsonl' \
    --gpu_memory_utilization 0.9 \
    --limit_mm_per_prompt '{"image": 8}' \
    --tensor_parallel_size 8

**Comment by munian08** [comment]
感谢回复 问题已经解决啦

**Comment by zhanwenchen** [comment]
> 感谢回复 问题已经解决啦

请问具体怎么解决的?
