### ISSUE TITLE
AssertionError: Error in memory profiling

### ISSUE THREAD

**Issue by dawnranger** [modelscope/ms-swift#3241]
# Describe the bug
```
source /root/mindie-atb-models/set_env.sh
source /usr/local/Ascend/ascend-toolkit/set_env.sh
source /usr/local/Ascend/nnal/atb/set_env.sh
source /usr/local/Ascend/mindie/set_env.sh
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:False
export HCCL_RDMA_TIMEOUT=20
export CUDA_DEVICE_MAX_CONNECTIONS=1
export TASK_QUEUE_ENABLE=2
export COMBINED_ENABLE=1
export CPU_AFFINITY_CONF=1
export HCCL_CONNECT_TIMEOUT=300
export HCCL_EVENT_TIMEOUT=300
export HCCL_EXEC_TIMEOUT=300
export NPU_ASD_ENABLE=0
# export ASCEND_LAUNCH_BLOCKING=0
export ASCEND_LAUNCH_BLOCKING=1
export ACLNN_CACHE_LIMIT=100000
export ASCEND_SLOG_PRINT_TO_STDOUT=0
export ASCEND_GLOBAL_LOG_LEVEL=0
export ASCEND_GLOBAL_EVENT_ENABLE=1

ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
NPROC_PER_NODE=7 \
swift rlhf \
    --rlhf_type grpo \
    --model Qwen/Qwen2.5-1.5B-Instruct \
    --external_plugins examples/train/grpo/plugin/plugin.py \
    --reward_funcs accuracy format \
    --use_vllm true \
    --vllm_enable_prefix_caching false \
    --train_type full \
    --torch_dtype bfloat16 \
    --dataset datasets/NuminaMath-TIR \
    --max_completion_length 2048 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-6 \
    --gradient_accumulation_steps 2 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 10 \
    --logging_steps 1 \
    --max_length 4096 \
    --output_dir output \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 8 \
    --dataset_num_proc 8 \
    --num_generations 7 \
    --temperature 0.9 \
    --system 'examples/train/grpo/prompt.txt' \
    --deepspeed zero2
```

# FULL LOG
```
[INFO:swift] model_parameter_info: Qwen2ForCausalLM: 1543.7143M Params (1543.7143M Trainable [100.0000%]), 0.0001M Buffers.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:187] No platform detected, vLLM is running on UnspecifiedPlatform
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
WARNING 02-24 06:33:08 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 02-24 06:33:08 __init__.py:174] Platform plugin ascend is activated
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:187] No platform detected, vLLM is running on UnspecifiedPlatform
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:187] No platform detected, vLLM is running on UnspecifiedPlatform
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
INFO 02-24 06:33:08 __init__.py:28] Available plugins for group vllm.platform_plugins:
INFO 02-24 06:33:08 __init__.py:30] name=ascend, value=vllm_ascend:register
INFO 02-24 06:33:08 __init__.py:32] all available plugins for group vllm.platform_plugins will be loaded.
INFO 02-24 06:33:08 __init__.py:34] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 02-24 06:33:08 __init__.py:42] plugin ascend loaded.
WARNING 02-24 06:33:08 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 02-24 06:33:08 __init__.py:174] Platform plugin ascend is activated
INFO 02-24 06:33:08 __init__.py:187] No platform detected, vLLM is running on UnspecifiedPlatform
WARNING 02-24 06:33:08 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 02-24 06:33:08 __init__.py:187] No platform detected, vLLM is running on UnspecifiedPlatform
INFO 02-24 06:33:08 __init__.py:174] Platform plugin ascend is activated
INFO 02-24 06:33:08 __init__.py:187] No platform detected, vLLM is running on UnspecifiedPlatform
INFO 02-24 06:33:08 __init__.py:187] No platform detected, vLLM is running on UnspecifiedPlatform
WARNING 02-24 06:33:08 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
WARNING 02-24 06:33:08 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 02-24 06:33:08 __init__.py:174] Platform plugin ascend is activated
INFO 02-24 06:33:08 __init__.py:174] Platform plugin ascend is activated
WARNING 02-24 06:33:08 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 02-24 06:33:08 __init__.py:174] Platform plugin ascend is activated
WARNING 02-24 06:33:08 _custom_ops.py:19] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 02-24 06:33:08 __init__.py:174] Platform plugin ascend is activated
/root/ms-swift/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `GRPOTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
/root/ms-swift/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `GRPOTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
/root/ms-swift/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `GRPOTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
/root/ms-swift/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `GRPOTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
/root/ms-swift/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `GRPOTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
/root/ms-swift/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `GRPOTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
Detected kernel version 5.4.241, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/root/ms-swift/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `GRPOTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
[INFO:swift] Loading the model using model_dir: Qwen/Qwen2.5-1.5B-Instruct
INFO 02-24 06:33:20 config.py:526] This model supports multiple tasks: {'embed', 'reward', 'score', 'classify', 'generate'}. Defaulting to 'generate'.
INFO 02-24 06:33:20 importing.py:14] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 02-24 06:33:20 llm_engine.py:232] Initializing a V0 LLM engine (v0.7.1) with config: model='Qwen/Qwen2.5-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=npu:7, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2.5-1.5B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py:27: UserWarning: Failed to get the IP address, using 0.0.0.0 by default.The value can be set by the environment variable VLLM_HOST_IP or HOST_IP.
  get_ip(), get_open_port())
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:02<00:00,  2.16s/it]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:02<00:00,  2.16s/it]

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/ms-swift/swift/cli/rlhf.py", line 5, in <module>
[rank0]:     rlhf_main()
[rank0]:   File "/root/ms-swift/swift/llm/train/rlhf.py", line 96, in rlhf_main
[rank0]:     return SwiftRLHF(args).main()
[rank0]:   File "/root/ms-swift/swift/llm/base.py", line 46, in main
[rank0]:     result = self.run()
[rank0]:   File "/root/ms-swift/swift/llm/train/sft.py", line 127, in run
[rank0]:     trainer = trainer_cls(
[rank0]:   File "/root/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 146, in __init__
[rank0]:     self.engine = VllmEngine(
[rank0]:   File "/root/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 90, in __init__
[rank0]:     self._prepare_engine()
[rank0]:   File "/root/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 97, in _prepare_engine
[rank0]:     engine = AsyncLLMEngine.from_engine_args(self.engine_args)
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 642, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 592, in __init__
[rank0]:     self.engine = self._engine_class(*args, **kwargs)
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 265, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 274, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 414, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 99, in determine_num_available_blocks
[rank0]:     results = self.collective_rpc("determine_num_available_blocks")
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 49, in collective_rpc
[rank0]:     answer = run_method(self.driver_worker, method, args, kwargs)
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm/utils.py", line 2208, in run_method
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/python3.10.14/lib/python3.10/site-packages/vllm_ascend/worker.py", line 234, in determine_num_available_blocks
[rank0]:     assert peak_memory > 0, (
[rank0]: AssertionError: Error in memory profiling. Initial free memory 58247258112, current free memory 58247516160. This happens when the NPU memory was not properly cleaned up before initializing the vLLM instance.
```

# Your hardware and system info
- ms-swift: main branch. commit 8921d9b98310d93f9f111af8859358ee32dce687
- device: Ascend 910B
- CANN vesion: 8.0.0.beta1
- pip list:
```
torch                  2.5.1+cpu
torch-npu              2.5.1.dev20250218
transformers           4.50.0.dev0
trl                    0.16.0.dev0
vllm                   0.7.1+empty
vllm_ascend            0.7.1rc1
```

# Additional context
- related issue: https://github.com/vllm-project/vllm-ascend/issues/109
- How to fix: https://github.com/huggingface/trl/pull/2836

**Comment by yaxundai** [comment]
Why is this happening with my A800 as well.
Here's my training script
CUDA_VISIBLE_DEVICES=0,1 \
NPROC_PER_NODE=1 \
swift rlhf \
    --rlhf_type grpo \
    --model ${model_name} \
    --external_plugins ./my_grpo/plugin/plugin.py \
    --reward_funcs Format \
    --use_vllm true \
    --vllm_device auto \
    --vllm_gpu_memory_utilization 0.7 \
    --vllm_max_model_len 8192 \
    --train_type full \
    --torch_dtype bfloat16 \
    --dataset ${dadta_path} \
    --max_completion_length 2048 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --learning_rate 1e-6 \
    --gradient_accumulation_steps 1 \
    --eval_steps 200 \
    --save_steps 200 \
    --save_total_limit 2 \
    --logging_steps 5 \
    --max_length 4096 \
    --output_dir output \
    --report_to wandb \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 2 \
    --dataset_num_proc 2 \
    --num_generations 4 \
    --temperature 0.9 \
    --deepspeed zero2 \
    --log_completions true


### An error message is reported

/nfsdata3/daiyaxun/project/ms-swift/swift/trainers/mixin.py:80: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `GRPOTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
[INFO:swift] Loading the model using model_dir: /nfsdata3/daiyaxun/model/Qwen/Qwen2.5-Coder-1.5B-Instruct
WARNING 03-10 20:56:34 config.py:365] Async output processing is only supported for CUDA, TPU, XPU. Disabling it for other platforms.
INFO 03-10 20:56:34 llm_engine.py:237] Initializing an LLM engine (vdev) with config: model='/nfsdata3/daiyaxun/model/Qwen/Qwen2.5-Coder-1.5B-Instruct', speculative_config=None, tokenizer='/nfsdata3/daiyaxun/model/Qwen/Qwen2.5-Coder-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda:1, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/nfsdata3/daiyaxun/model/Qwen/Qwen2.5-Coder-1.5B-Instruct, use_v2_block_manager=True, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=True, use_async_output_proc=False, use_cached_outputs=False, mm_processor_kwargs=None)
INFO 03-10 20:56:34 model_runner.py:1060] Starting to load model /nfsdata3/daiyaxun/model/Qwen/Qwen2.5-Coder-1.5B-Instruct...
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.81it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.81it/s]

INFO 03-10 20:56:36 model_runner.py:1071] Loading model weights took 0.0000 GB
Traceback (most recent call last):
  File "/nfsdata3/daiyaxun/project/ms-swift/swift/cli/rlhf.py", line 5, in <module>
    rlhf_main()
  File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/train/rlhf.py", line 96, in rlhf_main
    return SwiftRLHF(args).main()
  File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/base.py", line 46, in main
    result = self.run()
  File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/train/sft.py", line 133, in run
    trainer = trainer_cls(
  File "/nfsdata3/daiyaxun/project/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 183, in __init__
    self.engine = VllmEngine(
  File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 94, in __init__
    self._prepare_engine()
  File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 101, in _prepare_engine
    engine = AsyncLLMEngine.from_engine_args(self.engine_args)
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 674, in from_engine_args
    engine = cls(
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 569, in __init__
    self.engine = self._engine_class(*args, **kwargs)
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 265, in __init__
    super().__init__(*args, **kwargs)
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 349, in __init__
    self._initialize_kv_caches()
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 484, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/executor/gpu_executor.py", line 114, in determine_num_available_blocks
    return self.driver_worker.determine_num_available_blocks()
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/worker/worker.py", line 232, in determine_num_available_blocks
    assert peak_memory > 0, (
AssertionError: Error in memory profiling. Initial free memory 77623263232, current free memory 77623263232. This happens when the GPU memory was not properly cleaned up before initializing the vLLM instance.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/nfsdata3/daiyaxun/project/ms-swift/swift/cli/rlhf.py", line 5, in <module>
[rank0]:     rlhf_main()
[rank0]:   File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/train/rlhf.py", line 96, in rlhf_main
[rank0]:     return SwiftRLHF(args).main()
[rank0]:   File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/base.py", line 46, in main
[rank0]:     result = self.run()
[rank0]:   File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/train/sft.py", line 133, in run
[rank0]:     trainer = trainer_cls(
[rank0]:   File "/nfsdata3/daiyaxun/project/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 183, in __init__
[rank0]:     self.engine = VllmEngine(
[rank0]:   File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 94, in __init__
[rank0]:     self._prepare_engine()
[rank0]:   File "/nfsdata3/daiyaxun/project/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 101, in _prepare_engine
[rank0]:     engine = AsyncLLMEngine.from_engine_args(self.engine_args)
[rank0]:   File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 674, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 569, in __init__
[rank0]:     self.engine = self._engine_class(*args, **kwargs)
[rank0]:   File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 265, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 349, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 484, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/executor/gpu_executor.py", line 114, in determine_num_available_blocks
[rank0]:     return self.driver_worker.determine_num_available_blocks()
[rank0]:   File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/vllm/worker/worker.py", line 232, in determine_num_available_blocks
[rank0]:     assert peak_memory > 0, (
[rank0]: AssertionError: Error in memory profiling. Initial free memory 77623263232, current free memory 77623263232. This happens when the GPU memory was not properly cleaned up before initializing the vLLM instance.
wandb: 
wandb: 🚀 View run Qwen2.5-Coder-1.5B-Instruct_0310-2056 at: https://wandb.ai/dyx_team/sql-r1/runs/vk6c5rh8
wandb: Find logs at: wandb/run-20250310_205626-vk6c5rh8/logs
E0310 20:56:40.954771 139846387775296 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 3659356) of binary: /data/daiyaxun/anaconda3/envs/swift/bin/python
Traceback (most recent call last):
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/torch/distributed/run.py", line 905, in <module>
    main()
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/daiyaxun/anaconda3/envs/swift/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/nfsdata3/daiyaxun/project/ms-swift/swift/cli/rlhf.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-10_20:56:40
  host      : 847b7df01948
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3659356)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by hjh0119** [comment]
@yaxundai This issue may occur when the GPU memory has not been cleared. Please ensure that other programs are closed before running.

**Comment by yaxundai** [comment]
> [@yaxundai](https://github.com/yaxundai) This issue may occur when the GPU memory has not been cleared. Please ensure that other programs are closed before running.

Thanks for the reply, I tried upgrading the version of vllm, from 0.6.3 to 0.7.3 and my problem was solved, I suspect it was my vllm version issue
