### ISSUE TITLE
nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.

### ISSUE THREAD

**Issue by Tian14267** [modelscope/ms-swift#3267]
**Describe the bug**
运行 ddp_device_map训练是提示报错。
**这是运行代码：**
```
nproc_per_node=1

CUDA_VISIBLE_DEVICES=0,1 \
NPROC_PER_NODE=$nproc_per_node \
swift sft \
    --model ./Qwen/Qwen2.5-7B-Instruct \
    --train_type lora \
    --dataset './1_data/AI-ModelScope/alpaca-gpt4-data-zh' \
    --torch_dtype bfloat16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --learning_rate 1e-4 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --gradient_accumulation_steps 1 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 5 \
    --max_length 2048 \
    --output_dir output \
    --system 'You are a helpful assistant.' \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --model_author swift \
    --model_name swift-robot \
    --gradient_checkpointing_kwargs '{"use_reentrant": false}'

```

**以下是报错信息：**
```
[INFO:swift] model_parameter_info: PeftModelForCausalLM: 7635.8016M Params (20.1851M Trainable [0.2643%]), 0.0001M Buffers.
/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
[2025-02-25 07:27:00,311] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
[INFO:swift] The logging file will be saved in: /data/fffan/0_experiment/4_ms_swift/output/v10-20250225-072622/logging.jsonl
[INFO:swift] Using MP + DDP(device_map)
Train:   0%|                                                                                                                                                                                                    | 0/6042 [00:00<?, ?it/s][rank0]: Traceback (most recent call last):
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/cli/sft.py", line 5, in <module>
[rank0]:     sft_main()
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/llm/train/sft.py", line 257, in sft_main
[rank0]:     return SwiftSft(args).main()
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/llm/base.py", line 46, in main
[rank0]:     result = self.run()
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/llm/train/sft.py", line 137, in run
[rank0]:     return self.train(trainer)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/llm/train/sft.py", line 196, in train
[rank0]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/trainers/mixin.py", line 262, in train
[rank0]:     res = super().train(*args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/transformers/trainer.py", line 2241, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/transformers/trainer.py", line 2548, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/transformers/trainer.py", line 3698, in training_step
[rank0]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/trainers/trainers.py", line 201, in compute_loss
[rank0]:     outputs = model(**inputs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
[rank0]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
[rank0]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
[rank0]:     return model_forward(*args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
[rank0]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 786, in convert_to_fp32
[rank0]:     return recursively_apply(_convert_to_fp32, tensor, test_type=_is_fp16_bf16_tensor)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 118, in recursively_apply
[rank0]:     {
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 119, in <dictcomp>
[rank0]:     k: recursively_apply(
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 126, in recursively_apply
[rank0]:     return func(data, *args, **kwargs)
[rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 778, in _convert_to_fp32
[rank0]:     return tensor.float()
[rank0]: RuntimeError: CUDA error: device-side assert triggered
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [18,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
Train:   0%|                                                                                                                                                                                                    | 0/6042 [00:05<?, ?it/s]
E0225 07:27:08.028000 554483 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -6) local_rank: 0 (pid: 554557) of binary: /data/miniconda3/envs/fffan_debug/bin/python
Traceback (most recent call last):
  File "/data/miniconda3/envs/fffan_debug/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/miniconda3/envs/fffan_debug/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================

```

**Your hardware and system info**
CUDA：12.5
GPU：A800 (80G)
torch ：2.5.1

**Additional context**
同样的代码，在4090显卡的机器中，就可以正常训练。

**Comment by Jintao-Huang** [comment]
你要不使用deepspeed 试试
没遇到过该问题

**Comment by slin000111** [comment]
> **Describe the bug** 运行 ddp_device_map训练是提示报错。 **这是运行代码：**
> 
> ```
> nproc_per_node=1
> 
> CUDA_VISIBLE_DEVICES=0,1 \
> NPROC_PER_NODE=$nproc_per_node \
> swift sft \
>     --model ./Qwen/Qwen2.5-7B-Instruct \
>     --train_type lora \
>     --dataset './1_data/AI-ModelScope/alpaca-gpt4-data-zh' \
>     --torch_dtype bfloat16 \
>     --num_train_epochs 1 \
>     --per_device_train_batch_size 8 \
>     --per_device_eval_batch_size 8 \
>     --learning_rate 1e-4 \
>     --lora_rank 8 \
>     --lora_alpha 32 \
>     --target_modules all-linear \
>     --gradient_accumulation_steps 1 \
>     --eval_steps 100 \
>     --save_steps 100 \
>     --save_total_limit 2 \
>     --logging_steps 5 \
>     --max_length 2048 \
>     --output_dir output \
>     --system 'You are a helpful assistant.' \
>     --warmup_ratio 0.05 \
>     --dataloader_num_workers 4 \
>     --model_author swift \
>     --model_name swift-robot \
>     --gradient_checkpointing_kwargs '{"use_reentrant": false}'
> ```
> 
> **以下是报错信息：**
> 
> ```
> [INFO:swift] model_parameter_info: PeftModelForCausalLM: 7635.8016M Params (20.1851M Trainable [0.2643%]), 0.0001M Buffers.
> /data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/trainers/mixin.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
>   super().__init__(
> [2025-02-25 07:27:00,311] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
> [INFO:swift] The logging file will be saved in: /data/fffan/0_experiment/4_ms_swift/output/v10-20250225-072622/logging.jsonl
> [INFO:swift] Using MP + DDP(device_map)
> Train:   0%|                                                                                                                                                                                                    | 0/6042 [00:00<?, ?it/s][rank0]: Traceback (most recent call last):
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/cli/sft.py", line 5, in <module>
> [rank0]:     sft_main()
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/llm/train/sft.py", line 257, in sft_main
> [rank0]:     return SwiftSft(args).main()
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/llm/base.py", line 46, in main
> [rank0]:     result = self.run()
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/llm/train/sft.py", line 137, in run
> [rank0]:     return self.train(trainer)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/llm/train/sft.py", line 196, in train
> [rank0]:     trainer.train(trainer.args.resume_from_checkpoint)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/trainers/mixin.py", line 262, in train
> [rank0]:     res = super().train(*args, **kwargs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/transformers/trainer.py", line 2241, in train
> [rank0]:     return inner_training_loop(
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/transformers/trainer.py", line 2548, in _inner_training_loop
> [rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/transformers/trainer.py", line 3698, in training_step
> [rank0]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/swift/trainers/trainers.py", line 201, in compute_loss
> [rank0]:     outputs = model(**inputs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
> [rank0]:     return self._call_impl(*args, **kwargs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
> [rank0]:     return forward_call(*args, **kwargs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
> [rank0]:     else self._run_ddp_forward(*inputs, **kwargs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
> [rank0]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
> [rank0]:     return self._call_impl(*args, **kwargs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
> [rank0]:     return forward_call(*args, **kwargs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
> [rank0]:     return model_forward(*args, **kwargs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
> [rank0]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 786, in convert_to_fp32
> [rank0]:     return recursively_apply(_convert_to_fp32, tensor, test_type=_is_fp16_bf16_tensor)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 118, in recursively_apply
> [rank0]:     {
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 119, in <dictcomp>
> [rank0]:     k: recursively_apply(
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 126, in recursively_apply
> [rank0]:     return func(data, *args, **kwargs)
> [rank0]:   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/accelerate/utils/operations.py", line 778, in _convert_to_fp32
> [rank0]:     return tensor.float()
> [rank0]: RuntimeError: CUDA error: device-side assert triggered
> [rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> [rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> [rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [18,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [22,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [25,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [26,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.
> Train:   0%|                                                                                                                                                                                                    | 0/6042 [00:05<?, ?it/s]
> E0225 07:27:08.028000 554483 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -6) local_rank: 0 (pid: 554557) of binary: /data/miniconda3/envs/fffan_debug/bin/python
> Traceback (most recent call last):
>   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/run.py", line 923, in <module>
>     main()
>   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
>     return f(*args, **kwargs)
>   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
>     run(args)
>   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
>     elastic_launch(
>   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/data/miniconda3/envs/fffan_debug/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> ```
> 
> **Your hardware and system info** CUDA：12.5 GPU：A800 (80G) torch ：2.5.1
> 
> **Additional context** 同样的代码，在4090显卡的机器中，就可以正常训练。

参考这个issue https://github.com/modelscope/ms-swift/issues/3319

**Comment by TES-ADC-JackeyLove** [comment]
这个问题现在解决了吗？我也遇到了一样的问题
