### ISSUE TITLE
请问怎么用4090进行grpo训练

### ISSUE THREAD

**Issue by 0awei0** [modelscope/ms-swift#3299]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
用4090进行grpo训练，发现好像优化不支持，应该怎么启动训练

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
[rank0]: NotImplementedError: Using RTX 4000 series doesn't support faster communication broadband via P2P or IB. Please set `NCCL_P2P_DISABLE="1"` and `NCCL_IB_DISABLE="1" or use `accelerate launch` which will do this automatically.
[rank0]:[W227 09:06:23.498216687 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by 0awei0** [comment]
这是我的启动命令
# nproc_per_node 比显卡数少一，vLLM默认单独部署于最后一张卡，即卡7
CUDA_VISIBLE_DEVICES=0,1,2,3,4 \
NPROC_PER_NODE=4 \
swift rlhf \
    --rlhf_type grpo \
    --model joshuaHe/tcm_qwen2.5-1.5b-sft \
    --model_type qwen2_5 \
    --dataset '/root/ms-swift/data' \
    --external_plugins examples/train/grpo/plugin/plugin.py \
    --reward_funcs TCMSDAccuracy format \
    --use_vllm true \
    --vllm_device auto \
    --vllm_gpu_memory_utilization 0.9 \
    --vllm_max_model_len 4096 \
    --train_type lora \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --torch_dtype bfloat16 \
    --max_completion_length 1024 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 3 \
    --per_device_eval_batch_size 3 \
    --learning_rate 1e-6 \
    --gradient_accumulation_steps 4 \
    --eval_steps 200 \
    --save_steps 200 \
    --save_total_limit 1 \
    --logging_steps 10 \
    --max_length 2048 \
    --output_dir output \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --dataset_num_proc 4 \
    --num_generations 3 \
    --temperature 0.9 \
    --system 'examples/train/grpo/prompt.txt' \
    --deepspeed zero2 \
    --log_completions true

**Comment by 0awei0** [comment]
已解决
CUDA_VISIBLE_DEVICES=0,1,2,3,4 \
NCCL_P2P_DISABLE="1" \
NCCL_IB_DISABLE="1" \
NPROC_PER_NODE=4 \
swift rlhf \
    --rlhf_type grpo \
    --model joshuaHe/tcm_qwen2.5-1.5b-sft \
    --model_type qwen2_5 \
    --dataset '/root/ms-swift/data' \
    --external_plugins examples/train/grpo/plugin/plugin.py \
    --reward_funcs TCMSDAccuracy format \
    --use_vllm true \
    --vllm_device auto \
    --vllm_gpu_memory_utilization 0.9 \
    --vllm_max_model_len 4096 \
    --train_type lora \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --torch_dtype bfloat16 \
    --max_completion_length 1024 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 3 \
    --per_device_eval_batch_size 3 \
    --learning_rate 1e-6 \
    --gradient_accumulation_steps 4 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 1 \
    --logging_steps 10 \
    --max_length 2048 \
    --output_dir output \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --dataset_num_proc 4 \
    --num_generations 6 \
    --temperature 0.9 \
    --system 'examples/train/grpo/prompt.txt' \
    --deepspeed zero2 \
    --log_completions true
