### ISSUE TITLE
qwen2.5 3b sft 多机训练 运行到固定的某个step会有一个节点显存 OOM

### ISSUE THREAD

**Issue by phantooom** [modelscope/ms-swift#3327]
我们运行了一个job 8台8卡A100 80g 的任务会在330步左右有一张卡OOM导致整个任务失败。
启动参数如下
torchrun --nnodes=8
 --node_rank=0 
--master_addr=qwen2-5vl-3b-pretrain-transcribe-20m-bs-zero3-52zfi-master-0.qwen2-5vl-3b-pretrain-transcribe-20m-bs-zero3-52zfi --nproc_per_node=8 
--master_port=34229
 swift/cli/sft.py 
--model /data/CV/Qwen2.5-VL-3B-Instruct --model_type qwen2_5_vl 
--train_type full
 --freeze_llm False
 --freeze_vit False
 --freeze_aligner False 
--output_dir /data/CV/lmm_model_output
 --dataset /data/CV/datasets/mllm-deploy
--per_device_train_batch_size 1
 --gradient_accumulation_steps 4
 --learning_rate 1e-5
 --max_length 4096
 --num_train_epochs 1
 --save_steps 5000 
--eval_steps 2000000
 --save_total_limit 1
 --logging_steps 5
 --warmup_ratio 0.05
 --torch_dtype bfloat16
 --dataloader_num_workers 8
 --dataset_num_proc 8 
--max_pixels 351232
 --deepspeed zero2

```
[rank62]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 19.14 GiB. GPU 6 has a total capacity of 79.33 GiB of which 8.35 GiB is free. Including non-PyTorch memory, this process has 70.97 GiB memory in use. Of the allocated memory 68.65 GiB is allocated by PyTorch, and 853.04 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by lukasindeed** [comment]
解决了吗，我也是这个问题...

**Comment by IamMegatron2025** [comment]
使用--deepspeed zero3试试

**Comment by phantooom** [comment]
最后发现是有条数据有问题。删掉就好了。

**Comment by yata0** [comment]
> 最后发现是有条数据有问题。删掉就好了。

@phantooom 请问是什么类型的数据问题

**Comment by z0o0ey** [comment]
feel free to create a new issue if it the problem persists.
