### ISSUE TITLE
用grpo爆显存了

### ISSUE THREAD

**Issue by joey9503** [modelscope/ms-swift#3359]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

grpo千问2.5 7b 显卡是4张A100 80GB显存，使用的是swift 3.1.1版本, vllm_gpu_memory_utilization, vllm_max_model_len 相关参数都很保守了，deepspeed用的zero3, 为什么还是爆显存？

<img width="1829" alt="Image" src="https://github.com/user-attachments/assets/bba65f37-e051-44ce-a26a-ace7fa7d7eac" />

<img width="561" alt="Image" src="https://github.com/user-attachments/assets/bfa5969f-cbbc-4229-9e0f-998c204ec73d" />

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
MASTER_PORT=29501 \
CUDA_VISIBLE_DEVICES=0,1,2,3 \
NPROC_PER_NODE=3 \
swift rlhf \
    --rlhf_type grpo \
    --model '/ossfs/workspace/Qwen2___5-7B-Instruct' \
    --model_type qwen2_5 \
    --external_plugins '/ossfs/workspace/ms-swift-3.1.1/examples/train/grpo/plugin/plugin.py' \
    --reward_funcs format external_css_selector_reward \
    --train_type lora \
    --use_vllm true \
    --vllm_device auto \
    --vllm_gpu_memory_utilization 0.6 \
    --vllm_max_model_len 2048 \
    --lora_rank 12 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --torch_dtype bfloat16 \
    --dataset '/ossfs/workspace/xpath_selector_data.jsonl'#3000 \
    --max_completion_length 2048 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --learning_rate 5e-6 \
    --gradient_accumulation_steps 8 \
    --eval_steps 50 \
    --save_steps 200 \
    --save_total_limit 4 \
    --logging_steps 2 \
    --max_length 2048 \
    --output_dir output \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --dataset_num_proc 4 \
    --num_generations 8 \
    --temperature 0.9 \
    --log_completions true \
    --gradient_checkpointing_kwargs '{"use_reentrant": false}' \
    --ddp_find_unused_parameters true \
    --attn_impl flash_attn \
    --deepspeed zero3 \
    --beta 0.001 \

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by hjh0119** [comment]
batch_size 太大了

**Comment by joey9503** [comment]
和数据的token长度有关系，我把数据长度限制了下就好了

**Comment by winni0** [comment]
> 和数据的token长度有关系，我把数据长度限制了下就好了

请问怎么限制数据token长度呀，用哪个参数

**Comment by Qiao0124** [comment]
> > 和数据的token长度有关系，我把数据长度限制了下就好了
> 
> 请问怎么限制数据token长度呀，用哪个参数

--max_length
另外用 flash_attention_2，如果训练的样本太长激活值吃掉的显存很恐怖的。
