### ISSUE TITLE
8*A100执行GRPO完整流程，使用vllm爆显存，不使用vllm可以正常训练但缓慢

### ISSUE THREAD

**Issue by HT-NEKO** [modelscope/ms-swift#4594]
请大家帮忙看看什么原因

基本按照[GRPO完整流程](https://swift.readthedocs.io/zh-cn/latest/BestPractices/GRPO%E5%AE%8C%E6%95%B4%E6%B5%81%E7%A8%8B.html)写的脚本

我的脚本：
```
export WANDB_API_KEY=xxx
export WANDB_MODE=dryrun
export WANDB_PROJECT=grpo
export WANDB_RUN_NAME=Qwen3-1.7B

NPROC_PER_NODE=8
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
swift rlhf \
    --rlhf_type grpo \
    --model ./Qwen3-1_7B \
    --model_type "qwen3" \
    --external_plugins /root/code/examples/train/grpo/plugin/plugin.py \
    --reward_funcs external_countdown format \
    --use_vllm true \
    --vllm_mode colocate \
    --train_type lora \
    --torch_dtype bfloat16 \
    --dataset 'zouxuhong/Countdown-Tasks-3to4#50000' \
    --max_length 2048 \
    --max_completion_length 1024 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --learning_rate 5e-7 \
    --gradient_accumulation_steps 8 \
    --eval_steps 500 \
    --save_steps 100 \
    --save_total_limit 3 \
    --logging_steps 1 \
    --output_dir output/GRPO_COUNTDOWN \
    --warmup_ratio 0.01 \
    --dataloader_num_workers 8 \
    --num_generations 8 \
    --temperature 1.0 \
    --system 'You are a helpful assistant. You first thinks about the reasoning process in the mind and then provides the user with the answer.' \
    --deepspeed "zero3_offload" \
    --log_completions true \
    --report_to wandb \
    --beta 0.001 \
    --num_iterations 1
```

报错（只放一个gpu的）：
```
[rank6]: Traceback (most recent call last):
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/cli/rlhf.py", line 5, in <module>
[rank6]:     rlhf_main()
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/train/rlhf.py", line 169, in rlhf_main
[rank6]:     return SwiftRLHF(args).main()
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/base.py", line 49, in main
[rank6]:     result = self.run()
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/train/sft.py", line 113, in run
[rank6]:     trainer = trainer_cls(
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/trainers/rlhf_trainer/grpo_trainer.py", line 248, in __init__
[rank6]:     self.engine = self.prepare_vllm(model)
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/trainers/rlhf_trainer/grpo_trainer.py", line 423, in prepare_vllm
[rank6]:     engine = GRPOVllmEngine(
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/infer/infer_engine/grpo_vllm_engine.py", line 52, in __init__
[rank6]:     super().__init__(
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/infer/infer_engine/vllm_engine.py", line 110, in __init__
[rank6]:     self._prepare_engine()
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/infer/infer_engine/vllm_engine.py", line 119, in _prepare_engine
[rank6]:     engine = llm_engine_cls.from_engine_args(self.engine_args)
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 501, in from_engine_args
[rank6]:     return engine_cls.from_vllm_config(
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 124, in from_vllm_config
[rank6]:     return cls(vllm_config=vllm_config,
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 101, in __init__
[rank6]:     self.engine_core = EngineCoreClient.make_client(
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 77, in make_client
[rank6]:     return InprocClient(vllm_config, executor_class, log_stats)
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 223, in __init__
[rank6]:     self.engine_core = EngineCore(*args, **kwargs)
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 76, in __init__
[rank6]:     self.model_executor = executor_class(vllm_config)
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 53, in __init__
[rank6]:     self._init_executor()
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 119, in _init_executor
[rank6]:     self.collective_rpc("init_device")
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 57, in collective_rpc
[rank6]:     answer = run_method(self.driver_worker, method, args, kwargs)
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/utils.py", line 2671, in run_method
[rank6]:     return func(*args, **kwargs)
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 606, in init_device
[rank6]:     self.worker.init_device()  # type: ignore
[rank6]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 140, in init_device
[rank6]:     raise ValueError(
[rank6]: ValueError: Free memory on device (22.64/79.15 GiB) on startup is less than desired GPU memory utilization (0.9, 71.24 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
```

相关包的版本：
```
ms-swift==3.5.0
vllm==0.9.1
deepspeed==0.14.5
trl==0.18.1
```

全部包：
```
Package                                  Version
---------------------------------------- -------------
absl-py                                  2.3.0
accelerate                               1.7.0
addict                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.12.12
aiosignal                                1.3.2
airportsdata                             20250523
aliyun-python-sdk-core                   2.16.0
aliyun-python-sdk-kms                    2.16.5
annotated-types                          0.7.0
antlr4-python3-runtime                   4.13.2
anyio                                    4.9.0
astor                                    0.8.1
async-timeout                            5.0.1
attrdict                                 2.0.1
attrs                                    25.3.0
binpacking                               1.5.2
blake3                                   1.0.5
cachetools                               6.0.0
certifi                                  2025.4.26
cffi                                     1.17.1
charset-normalizer                       3.4.2
click                                    8.2.1
cloudpickle                              3.1.1
colorama                                 0.4.6
compressed-tensors                       0.10.1
contourpy                                1.3.2
cpm-kernels                              1.0.11
crcmod                                   1.7
cryptography                             45.0.4
cupy-cuda12x                             13.4.1
cycler                                   0.12.1
dacite                                   1.9.2
datasets                                 3.3.2
deepspeed                                0.14.5
depyf                                    0.18.0
dill                                     0.3.8
diskcache                                5.6.3
distro                                   1.9.0
dnspython                                2.7.0
einops                                   0.8.1
email_validator                          2.2.0
evalscope                                0.16.1
exceptiongroup                           1.3.0
fastapi                                  0.115.12
fastapi-cli                              0.0.7
fastrlock                                0.8.3
ffmpy                                    0.6.0
filelock                                 3.18.0
fonttools                                4.58.2
frozenlist                               1.7.0
fsspec                                   2024.12.0
future                                   1.0.0
gguf                                     0.17.0
gitdb                                    4.0.12
GitPython                                3.1.44
googleapis-common-protos                 1.70.0
gradio                                   5.33.2
gradio_client                            1.10.3
groovy                                   0.1.2
grpcio                                   1.73.0
h11                                      0.16.0
hf-xet                                   1.1.3
hjson                                    3.1.0
httpcore                                 1.0.9
httptools                                0.6.4
httpx                                    0.28.1
huggingface-hub                          0.33.0
idna                                     3.10
immutabledict                            4.2.1
importlib_metadata                       8.7.0
interegular                              0.3.3
jieba                                    0.42.1
Jinja2                                   3.1.6
jiter                                    0.10.0
jmespath                                 0.10.0
joblib                                   1.5.1
jsonlines                                4.0.0
jsonschema                               4.24.0
jsonschema-specifications                2025.4.1
kiwisolver                               1.4.8
langdetect                               1.0.9
lark                                     1.2.2
latex2sympy2_extended                    1.10.1
liger_kernel                             0.5.10
llguidance                               0.7.29
llvmlite                                 0.44.0
lm-format-enforcer                       0.10.11
lxml                                     5.4.0
Markdown                                 3.8
markdown-it-py                           3.0.0
MarkupSafe                               3.0.2
matplotlib                               3.10.3
mdurl                                    0.1.2
mistral_common                           1.6.2
modelscope                               1.27.0
mpmath                                   1.3.0
ms_swift                                 3.5.0
msgpack                                  1.1.0
msgspec                                  0.19.0
multidict                                6.4.4
multiprocess                             0.70.16
nest-asyncio                             1.6.0
networkx                                 3.4.2
ninja                                    1.11.1.4
nltk                                     3.9.1
numba                                    0.61.2
numpy                                    1.26.4
nvidia-cublas-cu12                       12.6.4.1
nvidia-cuda-cupti-cu12                   12.6.80
nvidia-cuda-nvrtc-cu12                   12.6.77
nvidia-cuda-runtime-cu12                 12.6.77
nvidia-cudnn-cu12                        9.5.1.17
nvidia-cufft-cu12                        11.3.0.4
nvidia-cufile-cu12                       1.11.1.6
nvidia-curand-cu12                       10.3.7.77
nvidia-cusolver-cu12                     11.7.1.2
nvidia-cusparse-cu12                     12.5.4.2
nvidia-cusparselt-cu12                   0.6.3
nvidia-ml-py                             12.575.51
nvidia-nccl-cu12                         2.26.2
nvidia-nvjitlink-cu12                    12.6.85
nvidia-nvtx-cu12                         12.6.77
openai                                   1.86.0
opencv-python-headless                   4.11.0.86
opentelemetry-api                        1.34.1
opentelemetry-exporter-otlp              1.34.1
opentelemetry-exporter-otlp-proto-common 1.34.1
opentelemetry-exporter-otlp-proto-grpc   1.34.1
opentelemetry-exporter-otlp-proto-http   1.34.1
opentelemetry-proto                      1.34.1
opentelemetry-sdk                        1.34.1
opentelemetry-semantic-conventions       0.55b1
opentelemetry-semantic-conventions-ai    0.4.9
orjson                                   3.10.18
oss2                                     2.19.1
outlines                                 0.1.11
outlines_core                            0.1.26
packaging                                25.0
pandas                                   2.3.0
partial-json-parser                      0.2.1.1.post5
peft                                     0.15.2
pillow                                   11.2.1
pip                                      25.1
platformdirs                             4.3.8
portalocker                              3.1.1
prometheus_client                        0.22.1
prometheus-fastapi-instrumentator        7.1.0
propcache                                0.3.2
protobuf                                 5.29.5
psutil                                   7.0.0
py-cpuinfo                               9.0.0
pyarrow                                  20.0.0
pycountry                                24.6.1
pycparser                                2.22
pycryptodome                             3.23.0
pydantic                                 2.11.5
pydantic_core                            2.33.2
pydub                                    0.25.1
Pygments                                 2.19.1
pyparsing                                3.2.3
python-dateutil                          2.9.0.post0
python-dotenv                            1.1.0
python-json-logger                       3.3.0
python-multipart                         0.0.20
pytz                                     2025.2
PyYAML                                   6.0.2
pyzmq                                    26.4.0
ray                                      2.47.0
referencing                              0.36.2
regex                                    2024.11.6
requests                                 2.32.4
rich                                     14.0.0
rich-toolkit                             0.14.7
rouge                                    1.0.1
rouge-chinese                            1.0.3
rouge_score                              0.1.2
rpds-py                                  0.25.1
ruff                                     0.11.13
sacrebleu                                2.5.1
safehttpx                                0.1.6
safetensors                              0.5.3
scikit-learn                             1.7.0
scipy                                    1.15.3
seaborn                                  0.13.2
semantic-version                         2.10.0
sentencepiece                            0.2.0
sentry-sdk                               2.30.0
setproctitle                             1.3.6
setuptools                               69.5.1
shellingham                              1.5.4
simplejson                               3.20.1
six                                      1.17.0
smmap                                    5.0.2
sniffio                                  1.3.1
sortedcontainers                         2.4.0
starlette                                0.46.2
sympy                                    1.14.0
tabulate                                 0.9.0
tensorboard                              2.19.0
tensorboard-data-server                  0.7.2
threadpoolctl                            3.6.0
tiktoken                                 0.9.0
tokenizers                               0.21.1
tomlkit                                  0.13.3
torch                                    2.7.0
torchaudio                               2.7.0
torchvision                              0.22.0
tqdm                                     4.67.1
transformers                             4.52.4
transformers-stream-generator            0.0.5
triton                                   3.3.0
trl                                      0.18.1
typer                                    0.16.0
typing_extensions                        4.14.0
typing-inspection                        0.4.1
tzdata                                   2025.2
urllib3                                  2.4.0
uvicorn                                  0.34.3
uvloop                                   0.21.0
vllm                                     0.9.1
wandb                                    0.20.1
watchfiles                               1.0.5
websockets                               15.0.1
Werkzeug                                 3.1.3
wheel                                    0.45.1
word2number                              1.1
xformers                                 0.0.30
xgrammar                                 0.1.19
xxhash                                   3.5.0
yarl                                     1.20.1
zipp                                     3.23.0
zstandard                                0.23.0
```

**Comment by hjh0119** [comment]
decrease `--vllm_gpu_memory_utilization`

refer to https://swift.readthedocs.io/zh-cn/latest/Instruction/GRPO.html#colocate

**Comment by HT-NEKO** [comment]
> 减少`--vllm_gpu_memory_utilization`
> 
> 参考https://swift.readthedocs.io/zh-cn/latest/Instruction/GRPO.html#colocate

您好，我增加了下面这些参数：
```
    --sleep_level 1 \
    --offload_optimizer true \
    --offload_model true \
    --gc_collect_after_offload true \
    --vllm_gpu_memory_utilization 0.1 \
```
报错：
```
[rank4]: Traceback (most recent call last):
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/cli/rlhf.py", line 5, in <module>
[rank4]:     rlhf_main()
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/train/rlhf.py", line 169, in rlhf_main
[rank4]:     return SwiftRLHF(args).main()
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/base.py", line 49, in main
[rank4]:     result = self.run()
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/train/sft.py", line 113, in run
[rank4]:     trainer = trainer_cls(
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/trainers/rlhf_trainer/grpo_trainer.py", line 248, in __init__
[rank4]:     self.engine = self.prepare_vllm(model)
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/trainers/rlhf_trainer/grpo_trainer.py", line 423, in prepare_vllm
[rank4]:     engine = GRPOVllmEngine(
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/infer/infer_engine/grpo_vllm_engine.py", line 52, in __init__
[rank4]:     super().__init__(
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/infer/infer_engine/vllm_engine.py", line 110, in __init__
[rank4]:     self._prepare_engine()
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/swift/llm/infer/infer_engine/vllm_engine.py", line 119, in _prepare_engine
[rank4]:     engine = llm_engine_cls.from_engine_args(self.engine_args)
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 501, in from_engine_args
[rank4]:     return engine_cls.from_vllm_config(
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 124, in from_vllm_config
[rank4]:     return cls(vllm_config=vllm_config,
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 101, in __init__
[rank4]:     self.engine_core = EngineCoreClient.make_client(
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 77, in make_client
[rank4]:     return InprocClient(vllm_config, executor_class, log_stats)
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 223, in __init__
[rank4]:     self.engine_core = EngineCore(*args, **kwargs)
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 83, in __init__
[rank4]:     self._initialize_kv_caches(vllm_config)
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 145, in _initialize_kv_caches
[rank4]:     kv_cache_configs = [
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 146, in <listcomp>
[rank4]:     get_kv_cache_config(vllm_config, kv_cache_spec_one_worker,
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/core/kv_cache_utils.py", line 940, in get_kv_cache_config
[rank4]:     check_enough_kv_cache_memory(vllm_config, kv_cache_spec, available_memory)
[rank4]:   File "/root/storage/miniconda3/envs/kkms/lib/python3.10/site-packages/vllm/v1/core/kv_cache_utils.py", line 572, in check_enough_kv_cache_memory
[rank4]:     raise ValueError(
[rank4]: ValueError: To serve at least one request with the models's max seq len (40960), (4.38 GiB KV cache is needed, which is larger than the available KV cache memory (4.22 GiB). Based on the available memory, the estimated maximum model length is 39472. Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
```
很奇怪的是我已经设置了参数```--max_length 2048```，怎么会最大长度还是40960呢？有些疑惑

**Comment by hjh0119** [comment]
--vllm_max_model_len

**Comment by HT-NEKO** [comment]
> --vllm_max_model_len

非常感谢， 已解决

**Comment by FrankCreen** [comment]
@HT-NEKO 这个是在qwen3-1.7b上做啥任务？grpo效果怎么样哈
