### ISSUE TITLE
执行多卡 GRPO lora 训练时，中途GPU 显存占用突然升高，报OOM

### ISSUE THREAD

**Issue by hrz394943230** [modelscope/ms-swift#4961]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
执行多卡 GRPO lora 训练时，GPU 显存占用突然升高，报OOM
正在使用 7 卡 A100 80g 进行 GRPO Qwen3-8B 的multi-turn训练，命令行报错 OOM 通过 swanlab 发现

<img width="2298" height="756" alt="Image" src="https://github.com/user-attachments/assets/ad95f70d-be13-4e22-92e5-d2d8f9433478" />

我的训练参数中已经规定了
`    --max_completion_length 8192 \
    --max_length 16384\`

以下是全部训练参数：
```
conda activate swift
export LOG_LEVEL=DEBUG
export NCCL_DEBUG=INFO
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 \
NPROC_PER_NODE=7 \
swift rlhf \
    --rlhf_type grpo \
    --use_vllm true \
    --vllm_mode colocate \
    --sleep_level 1 \
    --offload_optimizer true \
    --offload_model true \
    --vllm_gpu_memory_utilization 0.4 \
    --max_completion_length 8192 \
    --max_length 16384\
    --num_generations 7 \
    --split_dataset_ratio 0.05 \
    --model /gz-data/Qwen3-8B \
    --external_plugins /repo/tf_plugin.py \
    --reward_funcs tf_format_reward tf_result_reward \
    --train_type lora \
    --dataset /repo/dataset/ide_tool_dataset.jsonl \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --learning_rate 1e-6 \
    --gradient_accumulation_steps 1 \
    --eval_steps 20 \
    --save_steps 20 \
    --reward_weights 0.1 1.0\
    --save_total_limit 5 \
    --logging_steps 1 \
    --output_dir /gz-data/output \
    --temperature 1.0\
    --warmup_ratio 0.01 \
    --log_completions true \
    --beta 0.04 \
    --deepspeed zero3 \
    --log_completions true \
    --multi_turn_scheduler tf_tool_res_scheduler\
    --swanlab_token *** \
    --swanlab_project ide_tool \
    --swanlab_exp_name ide_tool_qwen3_8b_colocate\
    --report_to swanlab 
```

此时是已经进行到了第 48 个 steps 为什么会在中间报错呢？

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
ms_swift                                 3.7.0.dev0  
torch                                        2.7.0
CUDA                                      12.6
**Additional context**
Add any other context about the problem here(在这里补充其他信息)
我在自己实现的 multiturn  schedular 中控制了max turn 是 5

**Comment by hjh0119** [comment]
Check the changes in completion_length in the logs.

Set `--completion_length_limit_scope total` to use `max_completion_length` as a cap on the total completion length across multiple turns.

**Comment by hrz394943230** [comment]
when I add this --completion_length_limit_scope total 
```
urn self.engine.infer(infer_requests, request_config, use_tqdm=use_tqdm)
[rank2]:   File "/repo/ms-swift/swift/llm/infer/infer_engine/grpo_vllm_engine.py", line 113, in infer
[rank2]:     return super().infer(
[rank2]:   File "/repo/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 440, in infer
[rank2]:     self.set_default_max_tokens(request_config, batched_inputs)
[rank2]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 1503, in set_default_max_tokens
[rank2]:     prompt_tokens = max(_self._get_num_tokens(inp) for inp in inputs)
[rank2]: ValueError: max() arg is an empty sequence
[rank3]: Traceback (most recent call last):
[rank3]:   File "/repo/ms-swift/swift/cli/rlhf.py", line 5, in <module>
[rank3]:     rlhf_main()
[rank3]:   File "/repo/ms-swift/swift/llm/train/rlhf.py", line 172, in rlhf_main
[rank3]:     return SwiftRLHF(args).main()
[rank3]:   File "/repo/ms-swift/swift/llm/base.py", line 49, in main
[rank3]:     result = self.run()
[rank3]:   File "/repo/ms-swift/swift/llm/train/sft.py", line 122, in run
[rank3]:     return self.train(trainer)
[rank3]:   File "/repo/ms-swift/swift/llm/train/sft.py", line 183, in train
[rank3]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank3]:   File "/repo/ms-swift/swift/trainers/mixin.py", line 419, in train
[rank3]:     res = super().train(*args, **kwargs)
[rank3]:   File "/usr/local/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2240, in train
[rank3]:     return inner_training_loop(
[rank3]:   File "/usr/local/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2555, in _inner_training_loop
[rank3]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 1395, in training_step
[rank3]:     return super().training_step(model, inputs, num_items_in_batch)
[rank3]:   File "/usr/local/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 3739, in training_step
[rank3]:     inputs = self._prepare_inputs(inputs)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/utils.py", line 158, in wrapper
[rank3]:     return func(self, *args, **kwargs)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 350, in _prepare_inputs
[rank3]:     generation_batch = self._generate_and_score_completions(generation_batch)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 875, in _generate_and_score_completions
[rank3]:     inputs = self._generate_completions(inputs)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 856, in _generate_completions
[rank3]:     inputs, outputs = self._fast_infer(inputs)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 836, in _fast_infer
[rank3]:     outputs = self._infer_single_or_multi_turn(inputs, self.request_config)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 751, in _infer_single_or_multi_turn
[rank3]:     results = self._infer(current_infer_inputs, request_config)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 611, in _infer
[rank3]:     results: List[ChatCompletionResponse] = self._engine_infer(
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 1420, in _engine_infer
[rank3]:     return self.engine.infer(infer_requests, request_config, use_tqdm=use_tqdm)
[rank3]:   File "/repo/ms-swift/swift/llm/infer/infer_engine/grpo_vllm_engine.py", line 113, in infer
[rank3]:     return super().infer(
[rank3]:   File "/repo/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 440, in infer
[rank3]:     self.set_default_max_tokens(request_config, batched_inputs)
[rank3]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 1503, in set_default_max_tokens
[rank3]:     prompt_tokens = max(_self._get_num_tokens(inp) for inp in inputs)
[rank3]: ValueError: max() arg is an empty sequence
[rank1]: Traceback (most recent call last):
[rank1]:   File "/repo/ms-swift/swift/cli/rlhf.py", line 5, in <module>
[rank1]:     rlhf_main()
[rank1]:   File "/repo/ms-swift/swift/llm/train/rlhf.py", line 172, in rlhf_main
[rank1]:     return SwiftRLHF(args).main()
[rank1]:   File "/repo/ms-swift/swift/llm/base.py", line 49, in main
[rank1]:     result = self.run()
[rank1]:   File "/repo/ms-swift/swift/llm/train/sft.py", line 122, in run
[rank1]:     return self.train(trainer)
[rank1]:   File "/repo/ms-swift/swift/llm/train/sft.py", line 183, in train
[rank1]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank1]:   File "/repo/ms-swift/swift/trainers/mixin.py", line 419, in train
[rank1]:     res = super().train(*args, **kwargs)
[rank1]:   File "/usr/local/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2240, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/usr/local/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2555, in _inner_training_loop
[rank1]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 1395, in training_step
[rank1]:     return super().training_step(model, inputs, num_items_in_batch)
[rank1]:   File "/usr/local/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 3739, in training_step
[rank1]:     inputs = self._prepare_inputs(inputs)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/utils.py", line 158, in wrapper
[rank1]:     return func(self, *args, **kwargs)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 350, in _prepare_inputs
[rank1]:     generation_batch = self._generate_and_score_completions(generation_batch)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 875, in _generate_and_score_completions
[rank1]:     inputs = self._generate_completions(inputs)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 856, in _generate_completions
[rank1]:     inputs, outputs = self._fast_infer(inputs)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 836, in _fast_infer
[rank1]:     outputs = self._infer_single_or_multi_turn(inputs, self.request_config)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 751, in _infer_single_or_multi_turn
[rank1]:     results = self._infer(current_infer_inputs, request_config)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 611, in _infer
[rank1]:     results: List[ChatCompletionResponse] = self._engine_infer(
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 1420, in _engine_infer
[rank1]:     return self.engine.infer(infer_requests, request_config, use_tqdm=use_tqdm)
[rank1]:   File "/repo/ms-swift/swift/llm/infer/infer_engine/grpo_vllm_engine.py", line 113, in infer
[rank1]:     return super().infer(
[rank1]:   File "/repo/ms-swift/swift/llm/infer/infer_engine/vllm_engine.py", line 440, in infer
[rank1]:     self.set_default_max_tokens(request_config, batched_inputs)
[rank1]:   File "/repo/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 1503, in set_default_max_tokens
[rank1]:     prompt_tokens = max(_self._get_num_tokens(inp) for inp in inputs)
[rank1]: ValueError: max() arg is an empty sequence
```
remove it then can start training

**Comment by hjh0119** [comment]
Thank you for your report.

I'm just wondering why inputs would be empty in this case

**Comment by yfllllll** [comment]
@hrz394943230 have u solved this problem, i also met this problem

**Comment by hjh0119** [comment]
@yfllllll can you provide some scripts to reproduce this issue?

**Comment by hrz394943230** [comment]
> [@hrz394943230](https://github.com/hrz394943230) have u solved this problem, i also met this problem

no,I switch to colocate mode and it works well

**Comment by z0o0ey** [comment]
please retry with latest swift and vllm, feel free to reopen or create a new issue if it the problem persists.
