### ISSUE TITLE
qwenvl2.5_7B的sft训练显存非常不均衡，分配一百多g到一张卡里，用了deepspeed zero3都不行

### ISSUE THREAD

**Issue by lzk9508** [modelscope/ms-swift#4989]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

<img width="837" height="94" alt="Image" src="https://github.com/user-attachments/assets/fba2394a-deb0-432b-9d39-785dfe859a6f" />

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
cuda12.4，96g的八卡h20，训书生2.5_8B都没问题，改了个模型就挂了

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export NCCL_DEBUG=WARN
export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH

while true; do
    echo "开始训练 - $(date)"
    NPROC_PER_NODE=8 \
    swift sft \
        --model /245_disk/Qwen2.5-VL-7B \
        --dataset /245_disk/lengqidong_sft_0605.json \
        --lora_rank 8 \
        --freeze_aligner true \
        --output_dir ./qwen_lengqidong_sft_0605 \
        --torch_dtype bfloat16 \
        --deepspeed zero3 \
        --split_dataset_ratio 0.0 \
        --num_train_epochs 3 \
        --per_device_train_batch_size 1 \
        --learning_rate 1e-5 \
        --gradient_accumulation_steps 4 \
        --save_steps 50 \
        --save_total_limit 5 \
        --logging_steps 5 \
        --gradient_checkpointing true \
        --max_length 5000 \
        --warmup_ratio 0.03 \
        --weight_decay 0.05 \
        --dataloader_num_workers 16
    echo "训练完成 - $(date)"
    echo "等待50秒后重新开始..."
    sleep 50
done

**Comment by hjh0119** [comment]
Because the default image resolution is too high, the model input length becomes excessively long.

Please set `MAX_PIXELS` or `--max_pixels` to limit the image size.

**Comment by lzk9508** [comment]
> Because the default image resolution is too high, the model input length becomes excessively long.
> 
> Please set `MAX_PIXELS` or `--max_pixels` to limit the image size.
i set max_pixels to 1003520,but still not work. I think the problem is in allocation. The oom is happened in the step 13/258 during training
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 125.51 GiB. GPU 7 has a total capacity of 95.62 GiB of which 78.34 GiB is free. Process 267621 has 17.17 GiB memory in use. Process 267621 has 17.17 GiB memory in use. Of the allocated memory 16.10 GiB is allocated by PyTorch, and 183.84 MiB is reserved by PyTorch but unallocated.

**Comment by lzk9508** [comment]
<img width="318" height="289" alt="Image" src="https://github.com/user-attachments/assets/b42bec5e-2a66-43ae-a450-91d4898cd66e" />the memory is very uneven, so as the allocation

**Comment by KQL11** [comment]
> <img alt="Image" width="318" height="289" src="https://private-user-images.githubusercontent.com/91788329/467381612-b42bec5e-2a66-43ae-a450-91d4898cd66e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI3MzM5MzUsIm5iZiI6MTc1MjczMzYzNSwicGF0aCI6Ii85MTc4ODMyOS80NjczODE2MTItYjQyYmVjNWUtMmE2Ni00M2FlLWE0NTAtOTFkNDg5OGNkNjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE3VDA2MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MjU0OTExNDhmZjNkMmZlYTA1NTQ5ODdhMWFmMjAxYWRjOGU1MzU1ZjYxMWVkYzUwNGQxYzM4YTI0OTFjZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jg0Lq8bnZThf--LKYeFCMKhnUOj1x2EFjwHpY7IpDAI">the memory is very uneven, so as the allocation

--sequence_parallel_size 8
这个参数好像可以解决，但是相对的速度会变慢

**Comment by lzk9508** [comment]
--attn_impl flash_attn 
 finially, I set this config and the problem solved

**Comment by lzk9508** [comment]
> Because the default image resolution is too high, the model input length becomes excessively long.
> 
> Please set `MAX_PIXELS` or `--max_pixels` to limit the image size.

finally, i set the following configs and works:
        --attn_impl flash_attn \
        --max_pixel 1003520 \ 
thank you guy
