### ISSUE TITLE
qwen2_5vl lora微调oom

### ISSUE THREAD

**Issue by Jesayy** [modelscope/ms-swift#5292]
微调的脚本：
MAX_PIXELS=602112 \
nproc_per_node=2 \
CUDA_VISIBLE_DEVICES=0,1 \
NPROC_PER_NODE=$nproc_per_node \
swift sft \
    --model /root/data3/Qwen.Qwen2.5-VL-7B-Instruct \
    --model_type qwen2_5_vl \
    --train_type lora \
    --dataset data2/train_mecg_converted_multimodal_grpo.jsonl \
    --torch_dtype bfloat16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-4 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --gradient_accumulation_steps 16 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 5 \
    --max_length 30480 \
    --output_dir output \
    --system 'You are a helpful assistant.' \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --model_author swift \
    --model_name swift-robot \
    --deepspeed zero3

报错：
run sh: `/conda/envs/swift3/bin/python3.10 -m torch.distributed.run --nproc_per_node 2 /conda/envs/swift3/lib/python3.10/site-packages/swift/cli/sft.py --model /root/data3/Qwen.Qwen2.5-VL-7B-Instruct --model_type qwen2_5_vl --train_type lora --dataset data2/train_mecg_converted_multimodal_grpo.jsonl --torch_dtype bfloat16 --num_train_epochs 1 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --learning_rate 1e-4 --lora_rank 8 --lora_alpha 32 --target_modules all-linear --gradient_accumulation_steps 16 --eval_steps 100 --save_steps 100 --save_total_limit 2 --logging_steps 5 --max_length 30480 --output_dir output --system You are a helpful assistant. --warmup_ratio 0.05 --dataloader_num_workers 4 --model_author swift --model_name swift-robot --deepspeed zero3`

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[INFO:swift] Successfully registered `/conda/envs/swift3/lib/python3.10/site-packages/swift/llm/dataset/data/dataset_info.json`.
[2025-08-06 22:38:35,743] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[INFO:swift] rank: 0, local_rank: 0, world_size: 2, local_world_size: 2
[INFO:swift] Loading the model using model_dir: /root/data3/Qwen.Qwen2.5-VL-7B-Instruct
[INFO:swift] freeze_parameters: ['model.visual', 'model.visual.merger']
[INFO:swift] Using deepspeed: {'fp16': {'enabled': 'auto', 'loss_scale': 0, 'loss_scale_window': 1000, 'initial_scale_power': 16, 'hysteresis': 2, 'min_loss_scale': 1}, 'bf16': {'enabled': 'auto'}, 'zero_optimization': {'stage': 3, 'offload_optimizer': {'device': 'none', 'pin_memory': True}, 'offload_param': {'device': 'none', 'pin_memory': True}, 'overlap_comm': False, 'contiguous_gradients': True, 'sub_group_size': 1000000000.0, 'reduce_bucket_size': 'auto', 'zero_quantized_weights': False, 'zero_quantized_gradients': False, 'stage3_prefetch_bucket_size': 'auto', 'stage3_param_persistence_threshold': 'auto', 'stage3_max_live_parameters': 1000000000.0, 'stage3_max_reuse_distance': 1000000000.0, 'stage3_gather_16bit_weights_on_model_save': True}, 'gradient_accumulation_steps': 'auto', 'gradient_clipping': 'auto', 'steps_per_print': 2000, 'train_batch_size': 'auto', 'train_micro_batch_size_per_gpu': 'auto', 'wall_clock_breakdown': False}
[INFO:swift] Setting args.lazy_tokenize: True
[2025-08-06 22:38:35,963] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-06 22:38:38,076] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-06 22:38:38,093] [INFO] [comm.py:676:init_distributed] cdb=None
[2025-08-06 22:38:38,093] [INFO] [comm.py:707:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2025-08-06 22:38:38,167] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-06 22:38:38,192] [INFO] [comm.py:676:init_distributed] cdb=None
[INFO:swift] output_dir: /root/data5/caohanyu/cause/cause/lora_qwen-vl-0418/ms-swift-main/output/v19-20250806-223838
[INFO:swift] Global seed set to 42
[INFO:swift] args: TrainArguments(
_n_gpu=-1,
acc_steps=1,
acc_strategy=token,
accelerator_config={'dispatch_batches': False},
adafactor=False,
adalora_beta1=0.85,
adalora_beta2=0.85,
adalora_deltaT=1,
adalora_init_r=12,
adalora_orth_reg_weight=0.5,
adalora_target_r=8,
adalora_tfinal=0,
adalora_tinit=0,
adam_beta1=0.9,
adam_beta2=0.95,
adam_epsilon=1e-08,
adapter_act=gelu,
adapter_length=128,
adapters=[],
add_version=True,
agent_template=None,
aligner_lr=None,
attn_impl=None,
auto_find_batch_size=False,
average_tokens_across_devices=False,
batch_eval_metrics=False,
bf16=True,
bf16_full_eval=False,
bnb_4bit_compute_dtype=torch.bfloat16,
bnb_4bit_quant_storage=None,
bnb_4bit_quant_type=nf4,
bnb_4bit_use_double_quant=True,
boft_block_num=0,
boft_block_size=4,
boft_dropout=0.0,
boft_n_butterfly_factor=1,
channels=None,
check_model=True,
ckpt_dir=None,
columns={},
create_checkpoint_symlink=False,
custom_dataset_info=[],
custom_register_path=[],
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=4,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
dataset=['data2/train_mecg_converted_multimodal_grpo.jsonl'],
dataset_num_proc=1,
dataset_shuffle=True,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=18000000,
debug=None,
deepspeed={'fp16': {'enabled': 'auto', 'loss_scale': 0, 'loss_scale_window': 1000, 'initial_scale_power': 16, 'hysteresis': 2, 'min_loss_scale': 1}, 'bf16': {'enabled': 'auto'}, 'zero_optimization': {'stage': 3, 'offload_optimizer': {'device': 'none', 'pin_memory': True}, 'offload_param': {'device': 'none', 'pin_memory': True}, 'overlap_comm': False, 'contiguous_gradients': True, 'sub_group_size': 1000000000.0, 'reduce_bucket_size': 'auto', 'zero_quantized_weights': False, 'zero_quantized_gradients': False, 'stage3_prefetch_bucket_size': 'auto', 'stage3_param_persistence_threshold': 'auto', 'stage3_max_live_parameters': 1000000000.0, 'stage3_max_reuse_distance': 1000000000.0, 'stage3_gather_16bit_weights_on_model_save': True}, 'gradient_accumulation_steps': 'auto', 'gradient_clipping': 'auto', 'steps_per_print': 2000, 'train_batch_size': 'auto', 'train_micro_batch_size_per_gpu': 'auto', 'wall_clock_breakdown': False},
device_map=None,
disable_tqdm=None,
do_eval=False,
do_predict=False,
do_train=False,
download_mode=reuse_dataset_if_exists,
ds3_gather_for_generation=True,
eval_accumulation_steps=None,
eval_dataset=[],
eval_dataset_args=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_generation_config=None,
eval_limit=None,
eval_on_start=False,
eval_steps=100.0,
eval_strategy=no,
eval_use_evalscope=False,
eval_use_gather_object=False,
external_plugins=[],
fourier_n_frequency=2000,
fourier_scaling=300.0,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
freeze_aligner=True,
freeze_llm=False,
freeze_parameters=['model.visual', 'model.visual.merger'],
freeze_parameters_ratio=0.0,
freeze_parameters_regex=None,
freeze_vit=True,
fsdp=,
fsdp_config=None,
fsdp_min_num_params=0,
fsdp_num=1,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
galore_cos_threshold=0.4,
galore_gamma_proj=2,
galore_optim_per_parameter=False,
galore_proj_bits=4,
galore_proj_group_size=256,
galore_proj_quant=False,
galore_proj_type=std,
galore_quantization=False,
galore_queue_size=5,
galore_rank=128,
galore_scale=1.0,
galore_target_modules=None,
galore_update_proj_gap=50,
galore_with_embedding=False,
generation_config=None,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=True,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hqq_axis=None,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_args_error=False,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
init_strategy=None,
init_weights=True,
interleave_prob=None,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
lazy_tokenize=True,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
lisa_activated_layers=0,
lisa_step_interval=20,
llamapro_num_groups=None,
llamapro_num_new_blocks=4,
load_args=False,
load_best_model_at_end=False,
load_data_args=False,
load_from_cache_file=True,
local_rank=0,
local_repo_path=None,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=/root/data5/caohanyu/cause/cause/lora_qwen-vl-0418/ms-swift-main/output/v19-20250806-223838/runs,
logging_first_step=True,
logging_nan_inf_filter=True,
logging_steps=5,
logging_strategy=steps,
logprobs=False,
lora_alpha=32,
lora_bias=none,
lora_dropout=0.05,
lora_dtype=None,
lora_ga_batch_size=2,
lora_ga_direction=ArB2r,
lora_ga_iters=2,
lora_ga_max_length=1024,
lora_ga_scale=stable,
lora_ga_stable_gamma=16,
lora_modules=[],
lora_rank=8,
lorap_lr_ratio=None,
loss_scale=default,
loss_type=None,
lr_scheduler_kwargs=None,
lr_scheduler_type=cosine,
max_epochs=None,
max_grad_norm=1.0,
max_length=30480,
max_memory={},
max_new_tokens=64,
max_pixels=None,
max_steps=-1,
metric=None,
metric_for_best_model=loss,
metric_warmup_step=0,
model=/root/data3/Qwen.Qwen2.5-VL-7B-Instruct,
model_author=['swift'],
model_kwargs={},
model_name=['swift-robot'],
model_revision=None,
model_type=qwen2_5_vl,
modules_to_save=[],
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
norm_bbox=None,
num_beams=1,
num_labels=None,
num_train_epochs=1.0,
optim=adamw_torch,
optim_args=None,
optim_target_modules=None,
optimizer=None,
output_dir=/root/data5/caohanyu/cause/cause/lora_qwen-vl-0418/ms-swift-main/output/v19-20250806-223838,
overwrite_output_dir=False,
packing=False,
packing_cache=None,
padding_free=False,
padding_side=right,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=False,
prediction_loss_only=False,
problem_type=None,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
quant_bits=None,
quant_method=None,
ray_scope=last,
reft_args=None,
reft_intervention_type=LoreftIntervention,
reft_layer_key=None,
reft_layers=None,
reft_rank=4,
remove_unused_columns=True,
repetition_penalty=None,
report_to=['tensorboard'],
response_prefix=None,
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
resume_only_model=False,
rope_scaling=None,
run_name=/root/data5/caohanyu/cause/cause/lora_qwen-vl-0418/ms-swift-main/output/v19-20250806-223838,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=100.0,
save_strategy=steps,
save_total_limit=2,
seed=42,
sequence_parallel_size=1,
shuffle_buffer_size=1000,
skip_memory_metrics=True,
sortish_sampler=False,
split_dataset_ratio=0.0,
stop_words=[],
stopping_strategy=first_exhausted,
stream=False,
streaming=False,
strict=False,
swanlab_exp_name=None,
swanlab_lark_secret=None,
swanlab_lark_webhook_url=None,
swanlab_mode=cloud,
swanlab_project=None,
swanlab_token=<SWANLAB_TOKEN>,
swanlab_workspace=None,
system=You are a helpful assistant.,
target_modules=['all-linear'],
target_regex=None,
task_type=causal_lm,
temperature=0.0,
template=qwen2_5_vl,
template_backend=swift,
tf32=None,
top_k=None,
top_logprobs=None,
top_p=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_dtype=torch.bfloat16,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
train_dataloader_shuffle=True,
train_type=lora,
trainable_parameters=[],
trainable_parameters_regex=None,
truncation_strategy=delete,
tuner_backend=peft,
use_chat_template=True,
use_cpu=False,
use_dora=False,
use_galore=False,
use_hf=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_logits_to_keep=None,
use_mps_device=False,
use_rslora=False,
use_swift_lora=False,
val_dataset=[],
val_dataset_shuffle=False,
vera_d_initial=0.1,
vera_dropout=0.0,
vera_projection_prng_key=0,
vera_rank=256,
vit_gradient_checkpointing=None,
vit_lr=None,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.1,
zero_hpz_partition_size=None,
)
[INFO:swift] Loading the model using model_dir: /root/data3/Qwen.Qwen2.5-VL-7B-Instruct
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
You have video processor config saved in `preprocessor.json` file which is deprecated. Video processor configs should be saved in their own `video_preprocessor.json` file. You can rename the file or load and save the processor back which renames it automatically. Loading from `preprocessor.json` will be removed in v5.0.
You have video processor config saved in `preprocessor.json` file which is deprecated. Video processor configs should be saved in their own `video_preprocessor.json` file. You can rename the file or load and save the processor back which renames it automatically. Loading from `preprocessor.json` will be removed in v5.0.
[2025-08-06 22:38:39,856] [INFO] [config.py:684:__init__] Config mesh_device None world_size = 2
[INFO:swift] model_kwargs: {'device_map': None}
[2025-08-06 22:38:39,903] [INFO] [config.py:684:__init__] Config mesh_device None world_size = 2
[2025-08-06 22:38:40,425] [INFO] [partition_parameters.py:366:__exit__] finished initializing model - num_params = 729, num_elems = 8.29B

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]
Loading checkpoint shards:  20%|██        | 1/5 [00:03<00:15,  3.82s/it]
Loading checkpoint shards:  20%|██        | 1/5 [00:04<00:16,  4.01s/it]
Loading checkpoint shards:  40%|████      | 2/5 [00:06<00:09,  3.08s/it]
Loading checkpoint shards:  40%|████      | 2/5 [00:06<00:09,  3.18s/it]
Loading checkpoint shards:  60%|██████    | 3/5 [00:08<00:05,  2.86s/it]
Loading checkpoint shards:  60%|██████    | 3/5 [00:09<00:06,  3.00s/it]
Loading checkpoint shards:  80%|████████  | 4/5 [00:11<00:02,  2.82s/it]
Loading checkpoint shards: 100%|██████████| 5/5 [00:11<00:00,  2.35s/it]

Loading checkpoint shards:  80%|████████  | 4/5 [00:12<00:02,  2.96s/it]
Loading checkpoint shards: 100%|██████████| 5/5 [00:12<00:00,  2.15s/it]
Loading checkpoint shards: 100%|██████████| 5/5 [00:12<00:00,  2.60s/it]
[INFO:swift] Setting image_factor: 28. You can adjust this hyperparameter through the environment variable: `IMAGE_FACTOR`.
[INFO:swift] Setting min_pixels: 3136. You can adjust this hyperparameter through the environment variable: `MIN_PIXELS`.
[INFO:swift] Setting max_pixels: 12845056. You can adjust this hyperparameter through the environment variable: `MAX_PIXELS`.
[INFO:swift] Setting max_ratio: 200. You can adjust this hyperparameter through the environment variable: `MAX_RATIO`.
[INFO:swift] Setting video_min_pixels: 100352. You can adjust this hyperparameter through the environment variable: `VIDEO_MIN_PIXELS`.
[INFO:swift] Setting video_max_pixels: 602112. You can adjust this hyperparameter through the environment variable: `VIDEO_MAX_PIXELS`.
[INFO:swift] Setting video_total_pixels: 90316800. You can adjust this hyperparameter through the environment variable: `VIDEO_TOTAL_PIXELS`.
[INFO:swift] Setting frame_factor: 2. You can adjust this hyperparameter through the environment variable: `FRAME_FACTOR`.
[INFO:swift] Setting fps: 2.0. You can adjust this hyperparameter through the environment variable: `FPS`.
[INFO:swift] Setting fps_min_frames: 4. You can adjust this hyperparameter through the environment variable: `FPS_MIN_FRAMES`.
[INFO:swift] Setting fps_max_frames: 768. You can adjust this hyperparameter through the environment variable: `FPS_MAX_FRAMES`.
[INFO:swift] model_info: ModelInfo(model_type='qwen2_5_vl', model_dir='/root/data3/Qwen.Qwen2.5-VL-7B-Instruct', torch_dtype=torch.bfloat16, max_model_len=128000, quant_method=None, quant_bits=None, rope_scaling={'type': 'default', 'mrope_section': [16, 24, 24], 'rope_type': 'default'}, config=Qwen2_5_VLConfig {
  "architectures": [
    "Qwen2_5_VLForConditionalGeneration"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "image_token_id": 151655,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "max_position_embeddings": 128000,
  "max_window_layers": 28,
  "model_type": "qwen2_5_vl",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "pad_token_id": 151643,
  "rms_norm_eps": 1e-06,
  "rope_scaling": {
    "mrope_section": [
      16,
      24,
      24
    ],
    "rope_type": "default",
    "type": "default"
  },
  "rope_theta": 1000000.0,
  "sliding_window": 32768,
  "text_config": {
    "architectures": [
      "Qwen2_5_VLForConditionalGeneration"
    ],
    "attention_dropout": 0.0,
    "bos_token_id": 151643,
    "eos_token_id": 151645,
    "hidden_act": "silu",
    "hidden_size": 3584,
    "image_token_id": null,
    "initializer_range": 0.02,
    "intermediate_size": 18944,
    "layer_types": [
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention"
    ],
    "max_position_embeddings": 128000,
    "max_window_layers": 28,
    "model_type": "qwen2_5_vl_text",
    "num_attention_heads": 28,
    "num_hidden_layers": 28,
    "num_key_value_heads": 4,
    "rms_norm_eps": 1e-06,
    "rope_scaling": {
      "mrope_section": [
        16,
        24,
        24
      ],
      "rope_type": "default",
      "type": "default"
    },
    "rope_theta": 1000000.0,
    "sliding_window": null,
    "torch_dtype": "bfloat16",
    "use_cache": true,
    "use_sliding_window": false,
    "video_token_id": null,
    "vision_end_token_id": 151653,
    "vision_start_token_id": 151652,
    "vision_token_id": 151654,
    "vocab_size": 152064
  },
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.53.3",
  "use_cache": true,
  "use_sliding_window": false,
  "video_token_id": 151656,
  "vision_config": {
    "depth": 32,
    "fullatt_block_indexes": [
      7,
      15,
      23,
      31
    ],
    "hidden_act": "silu",
    "hidden_size": 1280,
    "in_channels": 3,
    "in_chans": 3,
    "initializer_range": 0.02,
    "intermediate_size": 3420,
    "model_type": "qwen2_5_vl",
    "num_heads": 16,
    "out_hidden_size": 3584,
    "patch_size": 14,
    "spatial_merge_size": 2,
    "spatial_patch_size": 14,
    "temporal_patch_size": 2,
    "tokens_per_second": 2,
    "torch_dtype": "bfloat16",
    "window_size": 112
  },
  "vision_end_token_id": 151653,
  "vision_start_token_id": 151652,
  "vision_token_id": 151654,
  "vocab_size": 152064
}
, task_type='causal_lm', num_labels=None)
[INFO:swift] model.generation_config: GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": [
    151645,
    151643
  ],
  "max_new_tokens": 64,
  "pad_token_id": 151643,
  "repetition_penalty": 1.05
}

[INFO:swift] default_system: 'You are a helpful assistant.'
[INFO:swift] max_length: 30480
[INFO:swift] response_prefix: ''
[INFO:swift] agent_template: hermes
[INFO:swift] norm_bbox: none
[INFO:swift] Start time of running main: 2025-08-06 22:38:53.511679
[INFO:swift] swift.__version__: 3.6.2
[INFO:swift] SelfCognitionPreprocessor has been successfully configured with name: ('swift-robot', 'swift-robot'), author: ('swift', 'swift').
[INFO:swift] train_dataset: Dataset({
    features: ['messages', 'images'],
    num_rows: 5577
})
[INFO:swift] val_dataset: None
[INFO:swift] [LABELS] [-100 * 15767]The girl is needy, she is vulnerable.<|im_end|>
[INFO:swift] The TrainArguments will be saved in: /root/data5/caohanyu/cause/cause/lora_qwen-vl-0418/ms-swift-main/output/v19-20250806-223838/args.json
[INFO:swift] lora_config: LoraConfig(task_type='CAUSAL_LM', peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path='/root/data3/Qwen.Qwen2.5-VL-7B-Instruct', revision=None, inference_mode=False, r=8, target_modules='^(model.language_model.*\\.(gate_proj|k_proj|v_proj|up_proj|o_proj|q_proj|down_proj))$', exclude_modules=None, lora_alpha=32, lora_dropout=0.05, fan_in_fan_out=False, bias='none', use_rslora=False, modules_to_save=[], init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', trainable_token_indices=None, loftq_config={}, eva_config=None, corda_config=None, use_dora=False, layer_replication=None, runtime_config=LoraRuntimeConfig(ephemeral_gpu_offload=False), lora_bias=False, lora_dtype=None, lorap_lr_ratio=None, lorap_emb_lr=1e-06)
[INFO:swift] model: PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen2_5_VLForConditionalGeneration(
      (model): Qwen2_5_VLModel(
        (visual): Qwen2_5_VisionTransformerPretrainedModel(
          (patch_embed): Qwen2_5_VisionPatchEmbed(
            (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
          )
          (rotary_pos_emb): Qwen2_5_VisionRotaryEmbedding()
          (blocks): ModuleList(
            (0-31): 32 x Qwen2_5_VLVisionBlock(
              (norm1): Qwen2RMSNorm((0,), eps=1e-06)
              (norm2): Qwen2RMSNorm((0,), eps=1e-06)
              (attn): Qwen2_5_VLVisionAttention(
                (qkv): Linear(in_features=1280, out_features=3840, bias=True)
                (proj): Linear(in_features=1280, out_features=1280, bias=True)
              )
              (mlp): Qwen2_5_VLMLP(
                (gate_proj): Linear(in_features=1280, out_features=3420, bias=True)
                (up_proj): Linear(in_features=1280, out_features=3420, bias=True)
                (down_proj): Linear(in_features=3420, out_features=1280, bias=True)
                (act_fn): SiLU()
              )
            )
          )
          (merger): Qwen2_5_VLPatchMerger(
            (ln_q): Qwen2RMSNorm((0,), eps=1e-06)
            (mlp): Sequential(
              (0): Linear(in_features=5120, out_features=5120, bias=True)
              (1): GELU(approximate='none')
              (2): Linear(in_features=5120, out_features=3584, bias=True)
            )
          )
        )
        (language_model): Qwen2_5_VLTextModel(
          (embed_tokens): Embedding(152064, 3584)
          (layers): ModuleList(
            (0-27): 28 x Qwen2_5_VLDecoderLayer(
              (self_attn): Qwen2_5_VLAttention(
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=3584, out_features=3584, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3584, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=3584, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_proj): lora.Linear(
                  (base_layer): Linear(in_features=3584, out_features=512, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3584, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=512, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=3584, out_features=512, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3584, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=512, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (o_proj): lora.Linear(
                  (base_layer): Linear(in_features=3584, out_features=3584, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3584, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=3584, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (rotary_emb): Qwen2_5_VLRotaryEmbedding()
              )
              (mlp): Qwen2MLP(
                (gate_proj): lora.Linear(
                  (base_layer): Linear(in_features=3584, out_features=18944, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3584, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=18944, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (up_proj): lora.Linear(
                  (base_layer): Linear(in_features=3584, out_features=18944, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3584, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=18944, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (down_proj): lora.Linear(
                  (base_layer): Linear(in_features=18944, out_features=3584, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=18944, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=3584, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (act_fn): SiLU()
              )
              (input_layernorm): Qwen2RMSNorm((0,), eps=1e-06)
              (post_attention_layernorm): Qwen2RMSNorm((0,), eps=1e-06)
            )
          )
          (norm): Qwen2RMSNorm((0,), eps=1e-06)
          (rotary_emb): Qwen2_5_VLRotaryEmbedding()
        )
      )
      (lm_head): Linear(in_features=3584, out_features=152064, bias=False)
    )
  )
)
[INFO:swift] model_parameter_info: PeftModelForCausalLM: 8312.3517M Params (20.1851M Trainable [0.2428%]), 0.0019M Buffers.
/conda/envs/swift3/lib/python3.10/site-packages/swift/trainers/mixin.py:95: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
/conda/envs/swift3/lib/python3.10/site-packages/swift/trainers/mixin.py:95: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  super().__init__(
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
[INFO:swift] use_reentrant: True
[INFO:swift] The logging file will be saved in: /root/data5/caohanyu/cause/cause/lora_qwen-vl-0418/ms-swift-main/output/v19-20250806-223838/logging.jsonl
[INFO:swift] Successfully registered post_encode hook: ['PeftModelForCausalLM'].
No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.
Parameter Offload - Persistent parameters statistics: param_count = 676, numel = 8303616

Train:   0%|          | 0/175 [00:00<?, ?it/s][INFO:swift] use_logits_to_keep: False
[rank1]: Traceback (most recent call last):
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/cli/sft.py", line 7, in <module>
[rank1]:     sft_main()
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/llm/train/sft.py", line 274, in sft_main
[rank1]:     return SwiftSft(args).main()
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/llm/base.py", line 49, in main
[rank1]:     result = self.run()
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/llm/train/sft.py", line 122, in run
[rank1]:     return self.train(trainer)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/llm/train/sft.py", line 183, in train
[rank1]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/trainers/mixin.py", line 419, in train
[rank1]:     res = super().train(*args, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/transformers/trainer.py", line 2206, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/transformers/trainer.py", line 2548, in _inner_training_loop
[rank1]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/trainers/trainers.py", line 368, in training_step
[rank1]:     return super().training_step(model, inputs, *args, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/transformers/trainer.py", line 3749, in training_step
[rank1]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/trainers/trainers.py", line 320, in compute_loss
[rank1]:     outputs = model(**inputs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 20, in wrapped_fn
[rank1]:     ret_val = func(*args, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2105, in forward
[rank1]:     loss = self.module(*inputs, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
[rank1]:     return inner()
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in inner
[rank1]:     args_kwargs_result = hook(self, args, kwargs)  # type: ignore[misc]
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/llm/template/base.py", line 1285, in pre_forward_hook
[rank1]:     kwargs = to_device(self._post_encode(model, old_kwargs), model.device)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/swift/llm/template/template/qwen.py", line 349, in _post_encode
[rank1]:     image_embeds = model.visual(pixel_values, grid_thw=image_grid_thw)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
[rank1]:     return inner()
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1805, in inner
[rank1]:     result = forward_call(*args, **kwargs)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 491, in forward
[rank1]:     attention_mask = self._prepare_attention_mask(hidden_states, cu_seqlens_now)
[rank1]:   File "/conda/envs/swift3/lib/python3.10/site-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 434, in _prepare_attention_mask
[rank1]:     attention_mask = torch.full(
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 5.16 GiB. GPU 1 has a total capacity of 47.54 GiB of which 2.98 GiB is free. Process 36407 has 44.54 GiB memory in use. Of the allocated memory 42.93 GiB is allocated by PyTorch, and 1.16 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Exception in thread Thread-3 (_pin_memory_loop):
Traceback (most recent call last):
  File "/conda/envs/swift3/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/conda/envs/swift3/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/conda/envs/swift3/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 61, in _pin_memory_loop
    do_one_step()
  File "/conda/envs/swift3/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 37, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/conda/envs/swift3/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/conda/envs/swift3/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
  File "/conda/envs/swift3/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/conda/envs/swift3/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/conda/envs/swift3/lib/python3.10/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/conda/envs/swift3/lib/python3.10/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
我的数据集格式如下：{"messages": [{"role": "user", "content": "question: Why does Monica feel joy in U13? \\ context: <image>U8. Doug: Oh well, give it time. | <image><image>U9. Doug: So the divorce, the marriage, we have got a lot to celebrate. | <image><image>U10. Doug: How about we all go out to dinner tomorrow night? | <image><image>U11. Doug: Tomorrow night it is then, I should be out of court by six. | <image><image>U12. Doug: They keep throwing these sexual harassment cases at me and I keep knocking them out of the park! | <image>U13. Monica: Okay, I will see you tomorrow! | <image><image>U14. Monica: Just so you know, we are not seeing him tomorrow. | <image>U15. Monica: I... I cannot spend another evening with that man."}, {"role": "assistant", "content": "Monica and Chandler will meet Doug tomorrow."}], "solutions": "Monica and Chandler will meet Doug tomorrow.", "images": ["/root/data2/ECF/key_frames/ECF_img/dia1224utt8_keyframe-01.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt9_keyframe-01.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt9_keyframe-02.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt10_keyframe-01.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt10_keyframe-02.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt11_keyframe-01.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt11_keyframe-02.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt12_keyframe-01.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt12_keyframe-02.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt13_keyframe-01.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt14_keyframe-01.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt14_keyframe-02.jpeg", "/root/data2/ECF/key_frames/ECF_img/dia1224utt15_keyframe-01.jpeg"]}

**Comment by xingyang-zhang** [comment]
1. Reduce image resolution - decrease the environment variable MAX_PIXELS
2. Reduce the number of images

**Comment by Jintao-Huang** [comment]
<img width="717" height="175" alt="Image" src="https://github.com/user-attachments/assets/cb740bec-481f-4c5f-ab95-4c88e4b2b875" />

没有设置成功

**Comment by Jesayy** [comment]
> <img alt="Image" width="717" height="175" src="https://private-user-images.githubusercontent.com/45290347/475401749-cb740bec-481f-4c5f-ab95-4c88e4b2b875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ1NTczNTQsIm5iZiI6MTc1NDU1NzA1NCwicGF0aCI6Ii80NTI5MDM0Ny80NzU0MDE3NDktY2I3NDBiZWMtNDgxZi00YzVmLWFiOTUtNGM4OGU0YjJiODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA3VDA4NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NGMzMmJjMWRmYTQ0ZmNlMTA0ZTgyNjA0YmUxZmE2NTRjNjljNWQ3NjNkNTY5OTM3ZWMzZGM3M2JmZWMyYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uaGH28rKfydbZ3K7zPZveHvVbFhDq2Y2RG1Nv3lPMsM">
> 没有设置成功

您好，我在微调脚本里面设置了这个参数，所以为什么会设置不成功呢

**Comment by Jesayy** [comment]
y已解决
