### ISSUE TITLE
v100*4 grpo lora训练qwen3-8b，启用deepspeed还是爆显存

### ISSUE THREAD

**Issue by leuitong** [modelscope/ms-swift#6209]
swift：release/3.5
2.6.0+cu124

### 超参
/opt/conda/bin/python -m torch.distributed.run 
--nproc_per_node 4 
--nnodes 1 
--node_rank 0 
/workspace/bin/ms-swift/swift/cli/rlhf.py 
--rlhf_type grpo 
--output_dir /checkpoint 
--model /model/actor_model 
--dataset /data 
--torch_dtype float16 
--model_type qwen3 
--train_type lora 
--num_train_epochs 2 
--learning_rate 1e-06 
--save_steps 100 
--per_device_train_batch_size 1 
--report_to tensorboard 
--logging_steps 10 
--logging_dir /home/admin/logs/tfevent 
--log_completions true 
--use_vllm true 
--vllm_mode colocate 
--vllm_gpu_memory_utilization 0.7 
--vllm_max_model_len 1024 
--temperature 1.0 
--top_p 0.85 
--sleep_level 1 
--offload_model true 
--offload_optimizer true 
--gc_collect_after_offload true 
--reward_funcs accuracy 
--per_device_eval_batch_size 2 
--gradient_accumulation_steps 4 
--warmup_ratio 0.1 
--dataloader_num_workers 1 
--max_completion_length 1024 
--num_generations 2 
--overlong_filter true 
--include_num_input_tokens_seen True 
--max_length 1024 
--deepspeed zero3_offload 
--finetuning_type lora 
--lr_scheduler_type cosine 
--overwrite_cache true 
--overwrite_output_dir true 
--stage grpo 
--trust_remote_code true 
--use_fast_tokenizer true 
--lora_rank 8 
--lora_alpha 32 
--ignore_args_error True

### 异常
其中一张卡的报错：
[rank1]: Traceback (most recent call last):
[rank1]:   File "/workspace/bin/ms-swift/swift/cli/rlhf.py", line 5, in <module>
[rank1]:     rlhf_main()
[rank1]:   File "/workspace/bin/ms-swift/swift/llm/train/rlhf.py", line 175, in rlhf_main
[rank1]:     return SwiftRLHF(args).main()
[rank1]:   File "/workspace/bin/ms-swift/swift/llm/base.py", line 49, in main
[rank1]:     result = self.run()
[rank1]:   File "/workspace/bin/ms-swift/swift/llm/train/sft.py", line 123, in run
[rank1]:     return self.train(trainer)
[rank1]:   File "/workspace/bin/ms-swift/swift/llm/train/sft.py", line 184, in train
[rank1]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank1]:   File "/workspace/bin/ms-swift/swift/trainers/mixin.py", line 379, in train
[rank1]:     res = super().train(*args, **kwargs)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2245, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2560, in _inner_training_loop
[rank1]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank1]:   File "/workspace/bin/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 1356, in training_step
[rank1]:     return super().training_step(model, inputs, num_items_in_batch)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3730, in training_step
[rank1]:     inputs = self._prepare_inputs(inputs)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/trl/extras/profiling.py", line 98, in wrapper
[rank1]:     return func(self, *args, **kwargs)
[rank1]:   File "/workspace/bin/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 324, in _prepare_inputs
[rank1]:     generation_batch = self._generate_and_score_completions(generation_batch)
[rank1]:   File "/workspace/bin/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 850, in _generate_and_score_completions
[rank1]:     inputs = self._generate_completions(inputs)
[rank1]:   File "/workspace/bin/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 825, in _generate_completions
[rank1]:     inputs, outputs = self._fast_infer(inputs)
[rank1]:   File "/workspace/bin/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 778, in _fast_infer
[rank1]:     self._move_model_to_vllm()
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/trl/extras/profiling.py", line 98, in wrapper
[rank1]:     return func(self, *args, **kwargs)
[rank1]:   File "/workspace/bin/ms-swift/swift/trainers/rlhf_trainer/grpo_trainer.py", line 482, in _move_model_to_vllm
[rank1]:     with gather_if_zero3(parameters), patch_lora_merge(self.model, parameter_group):
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 2236, in __enter__
[rank1]:     self.params[0].all_gather(param_list=self.params)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1154, in all_gather
[rank1]:     return self._all_gather(param_list, async_op=async_op, hierarchy=hierarchy)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank1]:     ret_val = func(*args, **kwargs)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1522, in _all_gather
[rank1]:     self._allgather_params_coalesced(all_gather_nonquantize_list, hierarchy, quantize=False)
[rank1]:   File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1810, in _allgather_params_coalesced
[rank1]:     flat_tensor = torch.empty(tensor_size, dtype=param_list[0].ds_tensor.dtype,
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 1 has a total capacity of 31.99 GiB of which 352.00 MiB is free. Process 29958 has 31.65 GiB memory in use. Of the allocated memory 30.80 GiB is allocated by PyTorch, with 104.02 MiB allocated in private pools (e.g., CUDA Graphs), and 69.51 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

感觉超参已经没什么调整余地了，数据集也是测试用的，才不到500条，理论上4张v100 32G是够用的，还能怎么调整，求助🙏

PS：关闭vllm，可以跑，每张卡消耗显存21G左右，但非常非常慢

<img width="573" height="59" alt="Image" src="https://github.com/user-attachments/assets/d28ec570-e980-412a-ad44-f83b09e82b8f" />

**Comment by hjh0119** [comment]
upgrade swift, set parameter move_model_batches

**Comment by leuitong** [comment]
> upgrade swift, set parameter move_model_batches

thx，解决了
