### ISSUE TITLE
qwen3vl dense grpo bug

### ISSUE THREAD

**Issue by aJupyter** [modelscope/ms-swift#6365]
**Describe the bug**
torch.AcceleratorError: CUDA error: the provided PTX was compiled with an unsupported toolchain.

**Additional context**

运行命令
```
torchrun \
    $DISTRIBUTED_ARGS \
    swift/cli/rlhf.py \
    --rlhf_type grpo \
    --model ${model_dir} \
    --dataset ${data_dir} \
    --external_plugins tasks/qwenvl/plugs/grpo/dataset.py \
        tasks/qwenvl/plugs/grpo/reward.py \
    --reward_funcs wxz_grpo_acc \
    --train_type full \
    --use_vllm true \
    --vllm_mode colocate \
    --vllm_gpu_memory_utilization 0.4 \
    --vllm_tensor_parallel_size 1 \
    --torch_dtype bfloat16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-6 \
    --save_total_limit 3 \
    --logging_steps 5 \
    --output_dir ${output_dir} \
    --gradient_accumulation_steps 1 \
    --dataloader_num_workers 96 \
    --dataset_num_proc 16 \
    --max_completion_length 1024 \
    --num_generations 8 \
    --sleep_level 1 \
    --temperature 1.0 \
    --top_p 0.85 \
```
cc @Jintao-Huang

**Comment by aJupyter** [comment]
vllm 版本：0.11.0

**Comment by hjh0119** [comment]
Please check that the vLLM environment is correctly set up

**Comment by aJupyter** [comment]
> Please check that the vLLM environment is correctly set up

import正常导的，且qwenvl2.5能跑，请问应该用哪个版本呢

**Comment by hjh0119** [comment]
run normally on my side

```
IMAGE_MAX_TOKEN_NUM=1024 \
CUDA_VISIBLE_DEVICES=0,1,2,3 \
NPROC_PER_NODE=4 \
swift rlhf \
    --rlhf_type grpo \
    --model Qwen/Qwen3-VL-4B-Instruct \
    --external_plugins examples/train/grpo/plugin/plugin.py \
    --dataset 'AI-ModelScope/clevr_cogen_a_train' \
    --reward_funcs external_r1v_acc format \
    --train_type full \
    --use_vllm true \
    --vllm_mode colocate \
    --vllm_gpu_memory_utilization 0.4 \
    --vllm_max_model_len 16394 \
    --vllm_tensor_parallel_size 1 \
    --torch_dtype bfloat16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 1e-6 \
    --save_total_limit 3 \
    --logging_steps 5 \
    --gradient_accumulation_steps 1 \
    --dataloader_num_workers 96 \
    --dataset_num_proc 16 \
    --max_completion_length 1024 \
    --num_generations 4 \
    --sleep_level 1 \
    --temperature 1.0 \
    --top_p 0.85 \
```

**Comment by aJupyter** [comment]
我测的是2B，我试一下4B

**Comment by tommy-fcy** [comment]
> 我测的是2B，我试一下4B

Hi. I also met the same issue. Did you solve the problem?

**Comment by tommy-fcy** [comment]
> run normally on my side
> 
> ```
> IMAGE_MAX_TOKEN_NUM=1024 \
> CUDA_VISIBLE_DEVICES=0,1,2,3 \
> NPROC_PER_NODE=4 \
> swift rlhf \
>     --rlhf_type grpo \
>     --model Qwen/Qwen3-VL-4B-Instruct \
>     --external_plugins examples/train/grpo/plugin/plugin.py \
>     --dataset 'AI-ModelScope/clevr_cogen_a_train' \
>     --reward_funcs external_r1v_acc format \
>     --train_type full \
>     --use_vllm true \
>     --vllm_mode colocate \
>     --vllm_gpu_memory_utilization 0.4 \
>     --vllm_max_model_len 16394 \
>     --vllm_tensor_parallel_size 1 \
>     --torch_dtype bfloat16 \
>     --num_train_epochs 1 \
>     --per_device_train_batch_size 1 \
>     --per_device_eval_batch_size 1 \
>     --learning_rate 1e-6 \
>     --save_total_limit 3 \
>     --logging_steps 5 \
>     --gradient_accumulation_steps 1 \
>     --dataloader_num_workers 96 \
>     --dataset_num_proc 16 \
>     --max_completion_length 1024 \
>     --num_generations 4 \
>     --sleep_level 1 \
>     --temperature 1.0 \
>     --top_p 0.85 \
> ```

Hi. Could you share your environment? I would really appreciate it.

**Comment by aJupyter** [comment]
> > 我测的是2B，我试一下4B
> 
> Hi. I also met the same issue. Did you solve the problem?

没有

**Comment by HarreyJ** [comment]
> > > 我测的是2B，我试一下4B
> > 
> > 
> > Hi. I also met the same issue. Did you solve the problem?你好。我也遇到了同样的问题。你解决了问题吗？
> 
> 没有

我也遇到了同样的问题，这个貌似是vllm框架的问题，
我使用以下方法解决了：
设置export VLLM_ATTENTION_BACKEND=FLASHINFER
安装pip install flashinfer-python==0.3.1

**Comment by HarreyJ** [comment]
> > > 我测的是2B，我试一下4B
> > 
> > 
> > Hi. I also met the same issue. Did you solve the problem?你好。我也遇到了同样的问题。你解决了问题吗？
> 
> 没有
先nvidai-smi查看英伟达启动适配的最高cuda版本（比如我的驱动适配cuda12.6）
然后安装cuda12.6 conda install -c "nvidia/label/cuda-12.6.0" cuda-toolkit -y
然后在安装vllm的时候安装0.10.1版本 pip install vllm==0.10.1（这个是重点，记得安装和cuda适配的vllm版本）

**Comment by QileSuu** [comment]
> > > > 我测的是2B，我试一下4B
> > > 
> > > 
> > > Hi. I also met the same issue. Did you solve the problem?你好。我也遇到了同样的问题。你解决了问题吗？
> > 
> > 
> > 没有
> > 先nvidai-smi查看英伟达启动适配的最高cuda版本（比如我的驱动适配cuda12.6）
> > 然后安装cuda12.6 conda install -c "nvidia/label/cuda-12.6.0" cuda-toolkit -y
> > 然后在安装vllm的时候安装0.10.1版本 pip install vllm==0.10.1（这个是重点，记得安装和cuda适配的vllm版本）
我去看了vllm官方的文档，好像vllm==0.10.1并不支持Qwen3-VL，但我还没有尝试。请问你可以在这个版本下跑通吗

**Comment by Ryann-Ran** [comment]
This solution from the [official docs](https://docs.vllm.ai/en/latest/usage/troubleshooting/#cuda-error-the-provided-ptx-was-compiled-with-an-unsupported-toolchain) worked for me:

```Bash
apt-get install cuda-compat-12-9

# Add to ~/.bashrc:
# export LD_LIBRARY_PATH=/usr/local/cuda-12.9/compat:$LD_LIBRARY_PATH

source ~/.bashrc

**Comment by alanshaoTT** [comment]
> This solution from the [official docs](https://docs.vllm.ai/en/latest/usage/troubleshooting/#cuda-error-the-provided-ptx-was-compiled-with-an-unsupported-toolchain) worked for me:
> 
> apt-get install cuda-compat-12-9
> 
> # Add to ~/.bashrc:
> # export LD_LIBRARY_PATH=/usr/local/cuda-12.9/compat:$LD_LIBRARY_PATH
> 
> source ~/.bashrc

请问这个是会对全部的用户产生影响嘛？我的服务器环境并不是我自己在用 如果没有root权限能否解决呢？或者这个命令是不是不会对其他用户造成影响呢
