### ISSUE TITLE
训 InternVL3_5-30B-A3B 报错

### ISSUE THREAD

**Issue by shuoyinn** [modelscope/ms-swift#6495]
按照 https://github.com/modelscope/ms-swift/blob/main/docs/source/Megatron-SWIFT/Quick-start.md 安装的环境，但是 pip install git+https://github.com/NVIDIA/Megatron-LM.git@core_r0.14.0 执行失败，于是选择 git clone --branch core_r0.14.0 https://github.com/NVIDIA/Megatron-LM.git 并指定 export MEGATRON_LM_PATH='/xxx/Megatron-LM'

脚本如下
```shell

MASTER_ADDR=$1 
MASTER_PORT=$2 
NODE_RANK=$3 

echo MASTER_ADDR: $MASTER_ADDR 
echo MASTER_PORT: $MASTER_PORT 
echo NODE_RANK: $NODE_RANK 

MODEL_PATH=/mnt/bn/shuoyinnas/official_models_ckpt/InternVL3_5-30B-A3B_mcore

OUTPUT_DIR=/mnt/bn/shuoyinnas/tmp/Relevance_short8_InternVL3_5_30B_megatron

TRAIN_FILE_PATH=/mnt/bn/shuoyinnas/offline_learning/ms-swift/ysbd_train_sets/my_data.jsonl 

# --load_safetensors true \
# --save_safetensors true \
# --split_dataset_ratio 0.0 \
# --pipeline_model_parallel_size 2 \
# --decoder_first_pipeline_num_layers 25 \
# --moe_expert_capacity_factor 2 \

export TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD=1 
export MEGATRON_LM_PATH=/mnt/bn/shuoyinnas/offline_learning/Megatron-LM
export MODELSCOPE_CACHE=/mnt/bn/shuoyinnas/tmp_files/swift_megatron_shared

PYTORCH_CUDA_ALLOC_CONF='expandable_segments:True' \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
NNODES=4 \
NODE_RANK=$NODE_RANK \
MASTER_ADDR=$MASTER_ADDR \
MASTER_PORT=$MASTER_PORT \
NPROC_PER_NODE=8 \
MAX_NUM=1 \
megatron sft \
    --load $MODEL_PATH \
    --freeze_llm false \
    --freeze_vit false \
    --freeze_aligner false \
    --dataset $TRAIN_FILE_PATH \
    --load_from_cache_file true \
    --moe_permute_fusion true \
    --tensor_model_parallel_size 4 \
    --expert_model_parallel_size 4 \
    --moe_grouped_gemm true \
    --moe_shared_expert_overlap true \
    --moe_aux_loss_coeff 1e-6 \
    --micro_batch_size 2 \
    --global_batch_size 64 \
    --recompute_granularity full \
    --recompute_method uniform \
    --recompute_num_layers 1 \
    --max_epochs 2 \
    --finetune true \
    --cross_entropy_loss_fusion true \
    --lr 1e-6 \
    --lr_warmup_fraction 0.05 \
    --min_lr 1e-7 \
    --save $OUTPUT_DIR \
    --eval_interval 100000000000 \
    --save_interval 1000 \
    --vit_gradient_checkpointing true \
    --max_length 3600 \
    --packing false \
    --num_workers 8 \
    --dataset_num_proc 8 \
    --no_save_optim false \
    --no_save_rng false \
    --sequence_parallel true \
    --attention_backend flash
```

使用 core_r0.14.0 版本的 Megatron-LM 报错
```shell
[rank5]: Traceback (most recent call last):
[rank5]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/cli/_megatron/sft.py", line 5, in <module>
[rank5]:     megatron_sft_main()
[rank5]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/megatron/train/sft.py", line 72, in megatron_sft_main
[rank5]:     return MegatronSft(args).main()
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/llm/base.py", line 49, in main
[rank5]:     result = self.run()
[rank5]:              ^^^^^^^^^^
[rank5]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/megatron/train/sft.py", line 62, in run
[rank5]:     self.trainer.train(train_dataset, val_dataset, data_collator)
[rank5]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/megatron/trainers/base.py", line 801, in train
[rank5]:     pretrain(
[rank5]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/training/training.py", line 710, in pretrain
[rank5]:     iteration, num_floating_point_operations_so_far = train(
[rank5]:                                                       ^^^^^^
[rank5]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/training/training.py", line 2122, in train
[rank5]:     ) = train_step(
[rank5]:         ^^^^^^^^^^^
[rank5]: TypeError: BaseMegatronTrainer.train_step() takes 7 positional arguments but 8 were given
```

感觉是版本问题，因此使用 core_r0.13.0 版本的Megatron-LM（因为看 .md 改动的前一个版本就是这个 core_r0.13.0 所以尝试一下）， 但是又报另一个错

```shell
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/llm/base.py", line 49, in main                        [448/1805]
[rank2]:     result = self.run()                                                                                                    
[rank2]:              ^^^^^^^^^^                                                                                                    
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/megatron/train/sft.py", line 62, in run                         
[rank2]:     self.trainer.train(train_dataset, val_dataset, data_collator)                                                          
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/megatron/trainers/base.py", line 801, in train                  
[rank2]:     pretrain(                                                                                                              
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/training/training.py", line 864, in pretrain              
[rank2]:     iteration, num_floating_point_operations_so_far = train(
[rank2]:                                                       ^^^^^^
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/training/training.py", line 2279, in train
[rank2]:     ) = train_step(
[rank2]:         ^^^^^^^^^^^
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/ms-swift/swift/megatron/trainers/base.py", line 322, in train_step
[rank2]:     return self._origin_train_step(forward_step_func, new_data_iterator, model, optimizer, opt_param_scheduler,
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/training/training.py", line 1395, in train_step
[rank2]:     losses_reduced = forward_backward_func(
[rank2]:                      ^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 540, in forward
_backward_no_pipelining
[rank2]:     config.finalize_model_grads_func(
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/core/distributed/finalize_model_grads.py", line 297, in fi
nalize_model_grads
[rank2]:     model_chunk.finish_grad_sync()
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/core/distributed/distributed_data_parallel.py", line 586, 
in finish_grad_sync
[rank2]:     bucket_group.finish_grad_sync()
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/core/distributed/param_and_grad_buffer.py", line 419, in f
inish_grad_sync
[rank2]:     self.start_grad_sync()
[rank2]:   File "/mnt/bn/shuoyinnas/offline_learning/Megatron-LM/megatron/core/distributed/param_and_grad_buffer.py", line 354, in s
tart_grad_sync
[rank2]:     with stream_context, _coalescing_manager(communication_group, async_ops=async_op) as cm:
[rank2]:   File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
[rank2]:     next(self.gen)
[rank2]:   File "/home/tiger/.local/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 2634, in _coalescing_m
anager
[rank2]:     work = group.reduce_scatter_tensor_coalesced(outputs, inputs, reduce_opts)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: RuntimeError: NCCL Error 3: internal error - please report this issue to the NCCL developers
```

用 python3.10 与 python3.11 都出现了上述报错

求指教~

**Comment by Jintao-Huang** [comment]
NCCL 网络问题

https://github.com/NVIDIA/nccl/issues?q=is%3Aissue%20state%3Aclosed%20RuntimeError%3A%20NCCL%20Error%203%3A%20internal%20error%20-%20please%20report%20this%20issue%20to%20the%20NCCL%20developers

**Comment by Jintao-Huang** [comment]
0.14.0 需要ms-swift main分支的

**Comment by shuoyinn** [comment]
> 0.14.0 需要ms-swift main分支的

感谢回复~
那可能是我前几天拉下的 ms-swift 后有了更新，使用了上一个 main 版本的 ms-swift 但是照着新 doc 安装了 0.14.0 导致这个问题

**Comment by shuoyinn** [comment]
> NCCL 网络问题
> 
> https://github.com/NVIDIA/nccl/issues?q=is%3Aissue%20state%3Aclosed%20RuntimeError%3A%20NCCL%20Error%203%3A%20internal%20error%20-%20please%20report%20this%20issue%20to%20the%20NCCL%20developers

我使用 torchrun 训 deepspeed 是能跑通的，也是同样 master addr/port 的传参方式

看起来跟这个 https://github.com/modelscope/ms-swift/issues/6107 很像，@leizhenjie-yfd 是通过”将torch降低到2.7.1“解决的，但是我这里试了下仍然报错


```shell
Package                           Version        Editable project location
--------------------------------- -------------- -----------------------------------------------
absl-py                           2.3.1
accelerate                        1.9.0
addict                            2.4.0
aiofiles                          24.1.0
aiohappyeyeballs                  2.6.1
aiohttp                           3.12.15
aiosignal                         1.4.0
alabaster                         0.7.16
aliyun-python-sdk-core            2.16.0
aliyun-python-sdk-kms             2.16.5
annotated-doc                     0.0.3
annotated-types                   0.7.0
antlr4-python3-runtime            4.9.3
anyio                             4.11.0
apex                              0.1
argon2-cffi                       25.1.0
argon2-cffi-bindings              25.1.0
arrow                             1.4.0
asgiref                           3.9.1
astor                             0.8.1
asttokens                         3.0.0
async-lru                         2.0.5
async-timeout                     5.0.1
attrdict                          2.0.1
attrs                             25.3.0
babel                             2.17.0
backports-datetime-fromisoformat  2.0.3
beautifulsoup4                    4.14.2
bidict                            0.22.1
binpacking                        1.5.2
bitsandbytes                      0.48.2
blake3                            1.0.5
bleach                            6.3.0
blinker                           1.5
boto3                             1.40.3
botocore                          1.40.3
brotli                            1.2.0
byted-torch                       2.7.1.post1
byted-wandb                       0.13.92
bytedance-context                 0.8.0
bytedance-metrics                 0.5.2
bytedance.modelhub                0.0.104
bytedance.servicediscovery        0.1.2
bytedbackgrounds                  0.0.6
byteddatabus                      1.0.8
byteddps                          0.1.2
bytedenv                          0.7.1
bytedlogger                       0.15.2
bytedmemfd                        0.2
bytedmetrics                      0.10.2
bytedpymongo                      2.0.8+sbom
bytedrh2                          1.18.11
bytedservicediscovery             0.18.2
bytedtcc                          1.4.5
bytedtos                          1.1.22
bytedtrace                        0.3.0
bytedztijwthelper                 0.0.24
bytedztispiffe                    0.0.16
cachetools                        6.2.1
cbor2                             5.7.1
certifi                           2025.8.3
cffi                              2.0.0
chardet                           5.1.0
charset-normalizer                3.4.2
cli_exit_tools                    1.2.7
click                             8.2.1
cloudpickle                       3.1.2
comm                              0.2.3
compressed-tensors                0.11.0
configparser                      7.2.0
contourpy                         1.3.2
cpm-kernels                       1.0.11
crcmod                            1.7
cryptography                      46.0.3
cupy-cuda12x                      13.6.0
cycler                            0.12.1
cyclopts                          3.22.5
dacite                            1.9.2
datasets                          3.6.0
dbus-python                       1.3.2
debugpy                           1.8.17
decorator                         5.2.1
decord                            0.6.0
deepspeed                         0.17.4
defusedxml                        0.7.1
Deprecated                        1.3.1
depyf                             0.19.0
devscripts                        2.23.4+deb12u2
dill                              0.3.8
diskcache                         5.6.3
Distance                          0.1.3
distlib                           0.4.0
distro                            1.8.0
distro-info                       1.5+deb12u1
Django                            5.2.5
dnspython                         2.8.0
docker-pycreds                    0.4.0
docstring_parser                  0.17.0
docutils                          0.22
einops                            0.8.1
email-validator                   2.3.0
environs                          14.3.0
et_xmlfile                        2.0.0
exceptiongroup                    1.3.0
executing                         2.2.0
Faker                             37.5.3
fastapi                           0.121.0
fastapi-cli                       0.0.14
fastapi-cloud-cli                 0.3.1
fastjsonschema                    2.21.2
fastrlock                         0.8.3
ffmpy                             0.6.4
filelock                          3.18.0
fire                              0.7.1
flash_attn                        2.8.1
fonttools                         4.59.0
fqdn                              1.5.1
frozendict                        2.4.6
frozenlist                        1.7.0
fsspec                            2025.3.0
funcy                             1.18
future                            1.0.0
gguf                              0.17.1
gitdb                             4.0.12
GitPython                         3.1.45
gpg                               1.18.0
gradio                            5.49.1
gradio_client                     1.13.3
groovy                            0.1.2
grpcio                            1.74.0
h11                               0.16.0
hf-xet                            1.1.7
hjson                             3.1.0
httpcore                          1.0.9
httplib2                          0.20.4
httptools                         0.7.1
httpx                             0.28.1
huggingface-hub                   0.34.3
humanize                          4.12.3
idna                              3.10
image                             1.5.33
ImageHash                         4.3.2
imageio                           2.37.0
imagesize                         1.4.1
importlib_metadata                8.7.0
iniconfig                         2.3.0
interegular                       0.3.3
iotop                             0.6
ipaddress                         1.0.23
ipdb                              0.13.13
ipykernel                         7.1.0
ipython                           8.37.0
ipython_pygments_lexers           1.1.1
ipywidgets                        8.1.8
isoduration                       20.11.0
isort                             7.0.0
jedi                              0.19.2
jieba                             0.42.1
Jinja2                            3.1.6
jiter                             0.11.1
jmespath                          0.10.0
joblib                            1.5.1
json_repair                       0.52.5
json5                             0.12.1
jsonlines                         4.0.0
jsonpointer                       3.0.0
jsonschema                        4.25.1
jsonschema-specifications         2025.9.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.9.1
jupyter-events                    0.12.0
jupyter-lsp                       2.3.0
jupyter_server                    2.17.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.4.10
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.28.0
jupyterlab_widgets                3.0.16
kernels                           0.9.0
kiwisolver                        1.4.8
lark                              1.2.2
latex2sympy2_extended             1.10.2
lazr.restfulclient                0.14.5
lazr.uri                          1.0.6
lib-detect-testenv                2.0.8
lightning-utilities               0.15.2
llguidance                        0.7.30
llvmlite                          0.44.0
lm-format-enforcer                0.11.3
loralib                           0.1.2
Markdown                          3.8.2
markdown-it-py                    3.0.0
MarkupSafe                        3.0.2
marshmallow                       4.0.0
math-verify                       0.8.0
matplotlib                        3.10.5
matplotlib-inline                 0.1.7
mdurl                             0.1.2
megatron-core                     0.14.1         /mnt/bn/shuoyinnas/offline_learning/Megatron-LM
mistral_common                    1.8.5
mistune                           3.1.4
ml_dtypes                         0.5.3
mmengine                          0.10.7
modelscope                        1.28.2
mpmath                            1.3.0
ms_swift                          3.10.0.dev0    /mnt/bn/shuoyinnas/offline_learning/ms-swift
msgpack                           1.1.1
msgspec                           0.19.0
multidict                         6.6.3
multiprocess                      0.70.16
nbclient                          0.10.2
nbconvert                         7.16.6
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.4.2
ninja                             1.11.1.4
nltk                              3.9.1
none                              0.1.1
notebook                          7.4.7
notebook_shim                     0.2.4
numba                             0.61.2
numpy                             1.26.4
nvidia-cublas-cu12                12.6.4.1
nvidia-cuda-cupti-cu12            12.6.80
nvidia-cuda-nvrtc-cu12            12.6.77
nvidia-cuda-runtime-cu12          12.6.77
nvidia-cudnn-cu12                 9.5.1.17
nvidia-cufft-cu12                 11.3.0.4
nvidia-cufile-cu12                1.11.1.6
nvidia-curand-cu12                10.3.7.77
nvidia-cusolver-cu12              11.7.1.2
nvidia-cusparse-cu12              12.5.4.2
nvidia-cusparselt-cu12            0.6.3
nvidia-ml-py                      12.575.51
nvidia-nccl-cu12                  2.26.2
nvidia-nvjitlink-cu12             12.6.85
nvidia-nvtx-cu12                  12.6.77
oauthlib                          3.2.2
omegaconf                         2.3.0
onnx                              1.19.1
onnx-ir                           0.1.12
onnxscript                        0.3.1
openai                            2.7.1
openai-harmony                    0.0.8
opencv-python                     4.12.0.88
opencv-python-headless            4.12.0.88
openpyxl                          3.1.5
optimum                           2.0.0
orjson                            3.11.4
oss2                              2.19.1
outlines_core                     0.2.11
overrides                         7.7.0
packaging                         25.0
pandas                            2.3.1
pandocfilters                     1.5.1
parso                             0.8.4
partial-json-parser               0.2.1.1.post6
pathlib2                          2.3.7.post1
peft                              0.17.1
pexpect                           4.9.0
pillow                            11.3.0
pip                               25.3
platformdirs                      4.3.8
pluggy                            1.6.0
ply                               3.11
portalocker                       3.2.0
prometheus_client                 0.23.1
prometheus-fastapi-instrumentator 7.1.0
promise                           2.3
prompt_toolkit                    3.0.51
propcache                         0.3.2
protobuf                          6.31.1
psutil                            7.0.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py                                1.11.0
py-aiger                          6.2.3
py-aiger-cnf                      5.0.8
py-cpuinfo                        9.0.0
pyapproxmc                        4.1.24
pyarrow                           21.0.0
pybase64                          1.4.2
pybind11                          3.0.1
pycountry                         24.6.1
pycparser                         2.23
pycryptodome                      3.23.0
pycryptodomex                     3.23.0
pycryptosat                       5.11.23
pydantic                          2.11.7
pydantic_core                     2.33.2
pydantic-extra-types              2.10.6
pydub                             0.25.1
Pygments                          2.19.2
PyGObject                         3.42.2
PyJWT                             2.6.0
pynvml                            12.0.0
pyOpenSSL                         25.3.0
pyparsing                         3.2.3
pypblib                           0.0.4
pyrsistent                        0.19.3
pytest                            6.2.5
python-apt                        2.6.0
python-consul                     1.1.0
python-dateutil                   2.9.0.post0
python-debian                     0.1.49
python-dotenv                     1.1.1
python-engineio                   4.12.3
python-etcd                       0.4.5
python-json-logger                4.0.0
python-magic                      0.4.26
python-multipart                  0.0.20
python-sat                        1.8.dev18
python-socketio                   5.14.3
pytz                              2025.2
PyWavelets                        1.8.0
pyxdg                             0.28
PyYAML                            6.0.2
pyzmq                             27.1.0
ray                               2.51.1
referencing                       0.37.0
regex                             2025.7.34
requests                          2.32.4
rfc3339-validator                 0.1.4
rfc3986                           2.0.0
rfc3986-validator                 0.1.1
rfc3987-syntax                    1.1.0
rich                              14.1.0
rich-rst                          1.3.1
rich-toolkit                      0.15.1
rignore                           0.7.6
rouge                             1.0.1
rpds-py                           0.28.0
ruff                              0.14.4
s3transfer                        0.13.1
safehttpx                         0.1.7
safetensors                       0.5.3
schedule                          1.2.2
scikit-learn                      1.7.2
scipy                             1.15.3
semantic-version                  2.10.0
Send2Trash                        1.8.3
sentencepiece                     0.2.0
sentry-sdk                        2.34.1
setproctitle                      1.3.7
setuptools                        80.9.0
shellingham                       1.5.4
shortuuid                         1.0.13
simple-websocket                  1.1.0
simplejson                        3.20.2
six                               1.17.0
smmap                             5.0.2
sniffio                           1.3.1
snowballstemmer                   3.0.1
sortedcontainers                  2.4.0
soundfile                         0.13.1
soupsieve                         2.8
soxr                              1.0.0
Sphinx                            5.3.0
sphinxcontrib-applehelp           2.0.0
sphinxcontrib-devhelp             2.0.0
sphinxcontrib-htmlhelp            2.1.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              2.0.0
sphinxcontrib-serializinghtml     2.0.0
sphinxcontrib-websupport          2.0.0
sqlparse                          0.5.3
stack-data                        0.6.3
starlette                         0.49.3
sty                               1.0.6
sympy                             1.14.0
tabulate                          0.9.0
tensorboard                       2.20.0
tensorboard-data-server           0.7.2
termcolor                         3.1.0
terminado                         0.18.1
threadpoolctl                     3.6.0
thriftpy2                         0.5.3
tiktoken                          0.10.0
timeout-decorator                 0.5.0
timm                              1.0.19
tinycss2                          1.4.0
tokenizers                        0.22.1
toml                              0.10.2
tomli                             2.2.1
tomlkit                           0.13.3
torch                             2.7.1
torchaudio                        2.8.0
torchmetrics                      1.8.2
torchvision                       0.22.1
tornado                           6.5.2
tox                               3.28.0
tqdm                              4.67.1
traitlets                         5.14.3
transformer_engine                2.8.0
transformer_engine_cu12           2.8.0
transformer_engine_torch          2.8.0
transformers                      4.57.1
transformers-stream-generator     0.0.5
triton                            3.3.1
trl                               0.21.0
typer                             0.20.0
typing_extensions                 4.14.1
typing-inspection                 0.4.1
tzdata                            2025.2
unattended-upgrades               0.1
unidiff                           0.7.3
uri-template                      1.3.0
urllib3                           2.5.0
uvicorn                           0.38.0
uvloop                            0.21.0
validators                        0.35.0
virtualenv                        20.35.4
wadllib                           1.3.6
wandb                             0.21.0
watchdog                          6.0.0
watchfiles                        1.1.1
wcwidth                           0.2.13
webcolors                         25.10.0
webencodings                      0.5.1
websocket-client                  1.9.0
websockets                        15.0.1
Werkzeug                          3.1.3
wheel                             0.45.1
widgetsnbextension                4.0.15
wrapt                             1.17.2
wrapt_timeout_decorator           1.5.1
wsproto                           1.2.0
xdg                               5
xgrammar                          0.1.23
xlsxwriter                        3.2.5
xxhash                            3.5.0
yacs                              0.1.8
yapf                              0.43.0
yarl                              1.20.1
zipp                              3.23.0
zstandard                         0.25.0
```

**Comment by shuoyinn** [comment]
拉取最新的 ms-swift 使用 0.14.0 的 megatron_core 也报同样的错

**Comment by shuoyinn** [comment]
@Jintao-Huang 检查了下我的配置跟 [Quick-start.md](https://github.com/modelscope/ms-swift/blob/main/docs/source/Megatron-SWIFT/Quick-start.md) 与 https://github.com/modelscope/ms-swift/issues/6107 的 diff，改用 cu128，问题解决，成功启动训练了，先 close 了~

总结下，代码 /home/tiger/.local/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py 中的 work = group.reduce_scatter_tensor_coalesced(outputs, inputs, reduce_opts)：
- 在 cu126 中会报出错误 RuntimeError: NCCL Error 3: internal error - please report this issue to the NCCL developers
- 在 cu128 中使用 torch==2.8.0 会报出错误 RuntimeError: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)
- cu128+torch==2.7.1 成功启动训练
