### ISSUE TITLE
Qwen3-VL-32B多机 grpo 训练第一步卡住

### ISSUE THREAD

**Issue by Qiao0124** [modelscope/ms-swift#6759]
**Describe the bug**
多节点多卡 grpo 训练在训练的第一步卡住，卡住时间达一小时无响应。

3节点，每节点8张H20 96G。1节点执行 swift rollout ，剩余2节点执行 swift rlhf。

rlhf 日志末尾：
```bash
Parameter Offload - Persistent parameters statistics: param_count = 490, numel = 1143024
[INFO:swift] The logging file will be saved in: /checkpoint/binary/train_package/output/models/Qwen3-VL-32B-Instruct/grpo/logging.jsonl
[INFO:swift] Successfully registered post_encode hook: ['Qwen3VLForConditionalGeneration', 'Qwen3VLForConditionalGeneration'].
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
Parameter Offload - Persistent parameters statistics: param_count = 490, numel = 1143024

Train:   0%|          | 0/1 [00:00<?, ?it/s]xdl-xxx-worker-0:3945:4480 [0] NCCL INFO Channel 00/0 : 2[2] -> 8[0] [receive] via NET/IB/0/GDRDMA
xdl-xxx-worker-0:3945:4480 [0] NCCL INFO Channel 01/0 : 2[2] -> 8[0] [receive] via NET/IB/0/GDRDMA
xdl-xxx-worker-0:3945:4480 [0] NCCL INFO Connected all rings, use ring PXN 1 GDR 1
```

在  Connected all rings 后卡住

rollout 日志末尾：
```bash
INFO:     xxx:44790 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
INFO:     xxx:44790 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
INFO:     xxx:44790 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
INFO:     xxx:44790 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
INFO:     xxx:44790 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
INFO:     xxx:44790 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
INFO:     xxx:44790 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
INFO:     xxx:44790 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
[1;36m(EngineCore_DP0 pid=4228)[0;0m INFO 11-26 17:32:17 [block_pool.py:378] Successfully reset prefix cache
[1;36m(EngineCore_DP1 pid=4229)[0;0m INFO 11-26 17:32:17 [block_pool.py:378] Successfully reset prefix cache
INFO:     xxx:44790 - "POST /reset_prefix_cache/ HTTP/1.1" 200 OK
```

在 reset_prefix_cache 后卡住

rollout 脚本：
```bash
VLLM_PORT=${VLLM_SERVER_PORT:-"8000"}
unset http_proxy
unset https_proxy
unset HTTP_PROXY
unset HTTPS_PROXY
unset all_proxy
unset ALL_PROXY
unset no_proxy
unset NO_PROXY

MODEL_PATH=$(readlink -f output/models/Qwen3-VL-32B-Instruct/sft4grpo)

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
swift rollout \
  --model $MODEL_PATH \
  --infer_backend vllm \
  --vllm_tensor_parallel_size 4 \
  --vllm_data_parallel_size 2 \
  --vllm_gpu_memory_utilization 0.6 \
  --vllm_max_model_len 65536 \
  --max_length 65536
  --vllm_use_async_engine true \
  --agent_template hermes \
  --temperature 0.8 \
  --padding_free true \
  --attn_impl flash_attention_2 \
  --vllm_limit_mm_per_prompt '{"image": 4, "video": 0}' \
  --port ${VLLM_PORT}
```

rlhf 脚本：
```
nnodes=${NNODES:-2}
nproc_per_node=8
node_rank=${NODE_RANK:-0}
master_addr=${MASTER_ADDR:-"127.0.0.1"}
master_port=${MASTER_PORT:-"29500"}

export CUDA_LAUNCH_BLOCKING=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

VLLM_HOST=${VLLM_SERVER_HOST:-"127.0.0.1"}
VLLM_PORT=${VLLM_SERVER_PORT:-"8000"}

unset http_proxy
unset https_proxy
unset HTTP_PROXY
unset HTTPS_PROXY
unset all_proxy
unset ALL_PROXY
unset no_proxy
unset NO_PROXY

echo "📡 vLLM服务地址: ${VLLM_HOST}:${VLLM_PORT}"
echo "📡 分布式配置: NNODES=${nnodes}, NODE_RANK=${node_rank}, MASTER_ADDR=${master_addr}, MASTER_PORT=${master_port}"

MODEL_PATH=$(readlink -f output/models/Qwen3-VL-32B-Instruct/sft4grpo)

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
NPROC_PER_NODE=$nproc_per_node \
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
NNODES=$nnodes \
NODE_RANK=$node_rank \
MASTER_ADDR=$master_addr \
MASTER_PORT=$master_port \
swift rlhf \
    --rlhf_type grpo \
    --model $MODEL_PATH \
    --external_plugins train/plugin.py \
    --multi_turn_scheduler d2c_scheduler \
    --max_turns 3 \
    --agent_template hermes \
    --loss_scale hermes \
    --reward_funcs d2c_reward \
    --use_vllm true \
    --vllm_mode server \
    --vllm_server_host ${VLLM_HOST} \
    --vllm_server_port ${VLLM_PORT} \
    --vllm_server_timeout 300 \
    --train_type full \
    --torch_dtype bfloat16 \
    --dataset 'train/data/grpo_train.jsonl' \
    --load_from_cache_file true \
    --max_completion_length 8192 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --learning_rate 1e-6 \
    --gradient_accumulation_steps 1 \
    --save_strategy 'steps' \
    --save_steps 1000 \
    --save_total_limit 10 \
    --logging_steps 1 \
    --output_dir output/models/Qwen3-VL-32B-Instruct/grpo \
    --warmup_ratio 0.01 \
    --dataloader_num_workers 1 \
    --num_generations 8 \
    --temperature 0.7 \
    --padding_free true \
    --attn_impl flash_attention_2 \
    --deepspeed zero3 \
    --move_model_batches 8 \
    --add_version false \
    --create_checkpoint_symlink true
```

rollout 所在节点的 GPU 利用率始终为 0
```
================================================================================
🖥️  GPU 状态监控 [2025-11-26]
================================================================================
GPU 0: NVIDIA H20
  利用率: 0%
  显存: 63800MB / 97871MB (65.2%)
GPU 1: NVIDIA H20
  利用率: 0%
  显存: 63760MB / 97871MB (65.1%)
GPU 2: NVIDIA H20
  利用率: 0%
  显存: 63760MB / 97871MB (65.1%)
GPU 3: NVIDIA H20
  利用率: 0%
  显存: 63760MB / 97871MB (65.1%)
GPU 4: NVIDIA H20
  利用率: 0%
  显存: 63760MB / 97871MB (65.1%)
GPU 5: NVIDIA H20
  利用率: 0%
  显存: 63760MB / 97871MB (65.1%)
GPU 6: NVIDIA H20
  利用率: 0%
  显存: 63760MB / 97871MB (65.1%)
GPU 7: NVIDIA H20
  利用率: 0%
  显存: 63756MB / 97871MB (65.1%)
================================================================================
```

执行 rlhf 的节点中，master 节点的 GPU 利用率0号卡为0，其他为100%，非 master 节点的 GPU 利用率均为100%.

master 节点
```
================================================================================
🖥️  GPU 状态监控 [2025-11-26]
================================================================================
GPU 0: NVIDIA H20
  利用率: 0%
  显存: 36248MB / 97871MB (37.0%)
GPU 1: NVIDIA H20
  利用率: 100%
  显存: 36058MB / 97871MB (36.8%)
GPU 2: NVIDIA H20
  利用率: 100%
  显存: 36178MB / 97871MB (37.0%)
GPU 3: NVIDIA H20
  利用率: 100%
  显存: 36050MB / 97871MB (36.8%)
GPU 4: NVIDIA H20
  利用率: 100%
  显存: 36170MB / 97871MB (37.0%)
GPU 5: NVIDIA H20
  利用率: 100%
  显存: 36058MB / 97871MB (36.8%)
GPU 6: NVIDIA H20
  利用率: 100%
  显存: 36178MB / 97871MB (37.0%)
GPU 7: NVIDIA H20
  利用率: 100%
  显存: 36050MB / 97871MB (36.8%)
================================================================================
```

非 master 节点
```
================================================================================
🖥️  GPU 状态监控 [2025-11-26]
================================================================================
GPU 0: NVIDIA H20
  利用率: 100%
  显存: 36170MB / 97871MB (37.0%)
GPU 1: NVIDIA H20
  利用率: 100%
  显存: 36058MB / 97871MB (36.8%)
GPU 2: NVIDIA H20
  利用率: 100%
  显存: 36178MB / 97871MB (37.0%)
GPU 3: NVIDIA H20
  利用率: 100%
  显存: 36050MB / 97871MB (36.8%)
GPU 4: NVIDIA H20
  利用率: 100%
  显存: 36170MB / 97871MB (37.0%)
GPU 5: NVIDIA H20
  利用率: 100%
  显存: 36058MB / 97871MB (36.8%)
GPU 6: NVIDIA H20
  利用率: 100%
  显存: 36178MB / 97871MB (37.0%)
GPU 7: NVIDIA H20
  利用率: 100%
  显存: 36050MB / 97871MB (36.8%)
================================================================================
```

堆栈信息
```
Thread 3880 (idle): "MainThread"
    _invoke_run (torch/distributed/elastic/agent/server/api.py:879)
    run (torch/distributed/elastic/agent/server/api.py:715)
    wrapper (torch/distributed/elastic/metrics/api.py:138)
    launch_agent (torch/distributed/launcher/api.py:268)
    __call__ (torch/distributed/launcher/api.py:143)
    run (torch/distributed/run.py:892)
    main (torch/distributed/run.py:901)
    wrapper (torch/distributed/elastic/multiprocessing/errors/__init__.py:357)
    <module> (torch/distributed/run.py:905)
    _run_code (runpy.py:86)
    _run_module_as_main (runpy.py:196)

Thread 3951 (active): "MainThread"
    broadcast (torch/distributed/distributed_c10d.py:2824)
    wrapper (torch/distributed/c10d_logger.py:81)
    broadcast_object_list (torch/distributed/distributed_c10d.py:3628)
    wrapper (torch/distributed/c10d_logger.py:81)
    broadcast_object_list (accelerate/utils/operations.py:577)
    _server_rollout (swift/trainers/rlhf_trainer/rollout_mixin.py:747)
    _rollout (swift/trainers/rlhf_trainer/rollout_mixin.py:481)
    _infer_single_or_multi_turn (swift/trainers/rlhf_trainer/rollout_mixin.py:519)
    _fast_infer (swift/trainers/rlhf_trainer/rollout_mixin.py:671)
    _generate_completions (swift/trainers/rlhf_trainer/grpo_trainer.py:199)
    _generate_and_score_completions (swift/trainers/rlhf_trainer/grpo_trainer.py:218)
    wrapper (swift/trainers/rlhf_trainer/utils.py:407)
    _prepare_inputs (swift/trainers/rlhf_trainer/grpo_trainer.py:175)
    wrapper (swift/trainers/rlhf_trainer/utils.py:407)
    training_step (transformers/trainer.py:4014)
    training_step (swift/trainers/rlhf_trainer/grpo_trainer.py:1508)
    _inner_training_loop (transformers/trainer.py:2674)
    train (transformers/trainer.py:2325)
    train (swift/trainers/mixin.py:815)
    train (swift/llm/train/sft.py:254)
    run (swift/llm/train/sft.py:206)
    wrapper (swift/ray/base.py:170)
    main (swift/llm/base.py:49)
    rlhf_main (swift/llm/train/rlhf.py:227)
    <module> (swift/cli/rlhf.py:7)
Thread 4327 (idle): "Thread-1"
    wait (threading.py:324)
    wait (threading.py:607)
    run (tqdm/_monitor.py:60)
    _bootstrap_inner (threading.py:1016)
    _bootstrap (threading.py:973)

# 剩余7个Thread信息与 Thread 3951 一致
```

**Your hardware and system info**
硬件与系统
```bash
  操作系统: Linux 5.10.134-010.ali5000.al8.x86_64
  Python 版本: 3.10.13+gc
  NVCC 版本: Cuda compilation tools, release 12.8, V12.8.61
  PyTorch CUDA 版本: 12.8
  PyTorch cuDNN 版本: 91200
```
pip包
```bash
Package                           Version
--------------------------------- -----------------------
absl-py                           2.3.1
accelerate                        1.11.0
acm-sdk-python                    0.4.11
addict                            2.4.0
ai-scheduler                      0.9.19
aiofiles                          24.1.0
aiohappyeyeballs                  2.6.1
aiohttp                           3.13.1
aiooss2                           0.2.11
aiosignal                         1.4.0
annotated-types                   0.7.0
antlr4-python3-runtime            4.9.3
anyio                             4.11.0
apache-tvm-ffi                    0.1.0b15
apex                              0.1
argon2-cffi                       25.1.0
argon2-cffi-bindings              25.1.0
arrow                             1.4.0
astor                             0.8.1
asttokens                         3.0.0
astunparse                        1.6.3
async-lru                         2.0.5
async-timeout                     5.0.1
attrdict                          2.0.1
attrs                             25.4.0
av                                16.0.1
babel                             2.17.0
beautifulsoup4                    4.14.2
binpacking                        1.5.2
blake3                            1.0.8
bleach                            6.2.0
bracex                            2.6
brotli                            1.2.0
cachetools                        6.2.1
cbor2                             5.7.0
certifi                           2025.10.5
cffi                              2.0.0
chardet                           3.0.4
charset-normalizer                3.4.4
click                             8.2.1
cloudpickle                       3.1.1
column-io                         0.2.11+7c56d623.abi1
comm                              0.2.3
common-io                         0.8.23
compressed-tensors                0.11.0
contourpy                         1.3.2
cpm-kernels                       1.0.11
crcmod                            1.7
cryptography                      46.0.3
cuda-bindings                     13.0.2
cuda-pathfinder                   1.3.1
cuda-python                       13.0.2
cupy-cuda12x                      13.6.0
cycler                            0.12.1
Cython                            0.29.32
dacite                            1.9.2
datasets                          3.6.0
debugpy                           1.8.17
decorator                         5.2.1
decord                            0.6.0
deepspeed                         0.17.6
defusedxml                        0.7.1
depyf                             0.19.0
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
dnspython                         2.8.0
dockerfile-parse                  2.0.1
docopt                            0.6.2
e2b                               2.7.0
e2b-code-interpreter              2.3.0
easydict                          1.13
einops                            0.8.1
email-validator                   2.3.0
evaluate                          0.4.6
exceptiongroup                    1.3.0
executing                         2.2.1
fastapi                           0.119.1
fastapi-cli                       0.0.14
fastapi-cloud-cli                 0.3.1
fastjsonschema                    2.21.2
fastrlock                         0.8.3
ffmpy                             1.0.0
filelock                          3.20.0
filetype                          1.2.0
flash_attn                        2.8.0.post2
flash_attn_3                      3.0.0b1
flash_mla                         1.0.0+1408756
flashinfer-python                 0.4.0
fonttools                         4.60.1
fqdn                              1.5.1
frozendict                        2.4.7
frozenlist                        1.8.0
fsspec                            2025.3.0
future                            0.18.2
gcsfs                             2025.9.0
gguf                              0.17.1
gitdb                             4.0.12
GitPython                         3.1.45
google-api-core                   2.10.1
google-auth                       2.41.1
google-auth-oauthlib              1.2.2
google-cloud-core                 2.4.3
google-cloud-storage              2.14.0
google-crc32c                     1.7.1
google-resumable-media            2.7.2
googleapis-common-protos          1.56.4
GPUtil                            1.4.0
gradio                            6.0.1
gradio_client                     2.0.0
groovy                            0.1.2
grouped_gemm                      1.1.5
grpcio                            1.75.1
h11                               0.16.0
hdfs                              2.7.3
hf-xet                            1.1.10
hjson                             3.1.0
httpcore                          1.0.9
httptools                         0.7.1
httpx                             0.28.1
huggingface-hub                   0.35.3
idna                              2.8
ImageHash                         4.3.1
importlib_metadata                8.7.0
intel-cmplr-lib-ur                2025.2.1
intel-openmp                      2025.2.1
interegular                       0.3.3
ipykernel                         7.0.1
ipython                           8.37.0
ipywidgets                        8.1.7
isoduration                       20.11.0
jedi                              0.19.2
jieba                             0.42.1
Jinja2                            3.1.6
jiter                             0.11.1
jmespath                          0.10.0
joblib                            1.5.2
json_repair                       0.54.2
json5                             0.12.1
jsonpointer                       3.0.0
jsonschema                        4.25.1
jsonschema-specifications         2025.9.1
jupyter                           1.1.1
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.9.1
jupyter-events                    0.12.0
jupyter-lsp                       2.3.0
jupyter_server                    2.17.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.4.9
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.15
kazoo                             2.9.0
kiwisolver                        1.4.9
kmontitor-client                  0.0.0
lake_py_lib                       0.1.16
lark                              1.2.2
latex2sympy2_extended             1.0.6
lightning-utilities               0.15.2
llguidance                        0.7.30
llvmlite                          0.44.0
lm-format-enforcer                0.11.3
lmdb                              0.94
loguru                            0.7.3
lru-dict                          1.3.0
Markdown                          3.9
markdown-it-py                    4.0.0
MarkupSafe                        3.0.3
math-verify                       0.5.2
matplotlib                        3.9.2
matplotlib-inline                 0.1.7
mdl                               0.3.1
mdurl                             0.1.2
minify_html                       0.16.4
mistral_common                    1.8.5
mistune                           3.1.4
mizani                            0.14.2
mkl                               2025.0.1
mkl-include                       2025.0.1
ml_dtypes                         0.5.3
modelscope                        1.32.0
mpmath                            1.3.0
ms_swift                          3.10.0
msgpack                           1.1.2
msgspec                           0.19.0
multidict                         6.7.0
multimethod                       1.12
multiprocess                      0.70.16
nbclient                          0.10.2
nbconvert                         7.16.6
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.4.2
ninja                             1.13.0
nltk                              3.9.2
notebook                          7.4.7
notebook_shim                     0.2.4
numba                             0.61.2
numpy                             2.2.6
nvidia-cublas-cu12                12.8.4.1
nvidia-cuda-cupti-cu12            12.8.90
nvidia-cuda-nvrtc-cu12            12.8.93
nvidia-cuda-runtime-cu12          12.8.90
nvidia-cudnn-cu12                 9.10.2.21
nvidia-cudnn-frontend             1.15.0
nvidia-cufft-cu12                 11.3.3.83
nvidia-cufile-cu12                1.13.1.3
nvidia-curand-cu12                10.3.9.90
nvidia-cusolver-cu12              11.7.3.90
nvidia-cusparse-cu12              12.5.8.93
nvidia-cusparselt-cu12            0.7.1
nvidia-cutlass-dsl                4.2.1
nvidia-ml-py                      12.575.51
nvidia-ml-py3                     7.352.0
nvidia-nccl-cu12                  2.27.3
nvidia-nvjitlink-cu12             12.8.93
nvidia-nvtx-cu12                  12.8.90
oauthlib                          3.3.1
omegaconf                         2.3.0
onnx                              1.19.1
onnx-ir                           0.1.11
onnxscript                        0.3.1
openai                            2.6.0
openai-harmony                    0.0.4
opencv-python                     4.12.0.88
opencv-python-headless            4.12.0.88
openlm_hub                        0.0.56
orjson                            3.11.4
oss2                              2.18.4
ossfs                             2025.5.0
outlines_core                     0.2.11
overrides                         7.7.0
packaging                         25.0
pandas                            2.3.3
pandocfilters                     1.5.1
pangudfs-client                   1.0.27+lightsdk1.1.28
parso                             0.8.5
partial-json-parser               0.2.1.1.post6
pathlib                           1.0.1
patsy                             1.0.2
peft                              0.17.1
pexpect                           4.9.0
phik                              0.12.5
pillow                            10.4.0
pip                               24.0
platformdirs                      4.5.0
plotnine                          0.15.0
prometheus_client                 0.23.1
prometheus-fastapi-instrumentator 7.1.0
prompt_toolkit                    3.0.52
propcache                         0.4.1
protobuf                          6.33.1
psutil                            5.9.5
ptyprocess                        0.7.0
pure_eval                         0.2.3
puremagic                         1.30
py-cpuinfo                        9.0.0
py-spy                            0.4.1
pyarrow                           21.0.0
pyasn1                            0.6.1
pyasn1_modules                    0.4.2
pybase64                          1.4.2
pybind11                          3.0.1
pycountry                         24.6.1
pycparser                         2.23
pycryptodome                      3.23.0
pydantic                          2.12.3
pydantic_core                     2.41.4
pydantic-extra-types              2.10.6
pydicom                           1.2.2
pydub                             0.25.1
Pygments                          2.19.2
pykmonitor                        2.2.0
pynvml                            12.0.0
pyodps                            0.12.3
pyparsing                         3.2.5
pyreft                            0.0.8
pytest-runner                     6.0.1
python-dateutil                   2.9.0.post0
python-dotenv                     1.1.1
python-json-logger                4.0.0
python-multipart                  0.0.20
pytz                              2025.2
pyvene                            0.1.8
PyWavelets                        1.8.0
PyYAML                            6.0.3
pyzmq                             27.1.0
qwen-vl-utils                     0.0.14
ray                               2.50.1
redis                             6.4.0
referencing                       0.37.0
regex                             2025.10.22
requests                          2.32.5
requests-oauthlib                 2.0.0
retrying                          1.4.2
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rfc3987-syntax                    1.1.0
rich                              14.2.0
rich-toolkit                      0.15.1
rignore                           0.7.1
rouge                             1.0.1
rpds-py                           0.27.1
rsa                               4.9.1
ruamel.yaml                       0.18.15
ruamel.yaml.clib                  0.2.14
safehttpx                         0.1.7
safetensors                       0.6.2
scikit-learn                      1.7.2
scipy                             1.14.0
seaborn                           0.12.2
semantic-version                  2.10.0
Send2Trash                        1.8.3
sentencepiece                     0.2.1
sentry-sdk                        2.42.1
setproctitle                      1.3.7
setuptools                        80.9.0
shellingham                       1.5.4
simplejson                        3.17.6
six                               1.14.0
sklearn                           0.0.post12
smart_open                        7.4.0
smmap                             5.0.2
sniffio                           1.3.1
sortedcontainers                  2.4.0
soundfile                         0.13.1
soupsieve                         2.8
soxr                              1.0.0
stack-data                        0.6.3
starlette                         0.48.0
statsmodels                       0.14.5
sympy                             1.14.0
tabulate                          0.9.0
tbb                               2022.2.0
tcmlib                            1.4.0
tensorboard                       2.20.0
tensorboard-data-server           0.7.2
terminado                         0.18.1
thop-statistics                   0.1.1.post2303141613
threadpoolctl                     3.6.0
thrift                            0.16.0
tiktoken                          0.12.0
tinycss2                          1.4.0
tokenizers                        0.22.1
tomli                             2.3.0
tomlkit                           0.13.3
torch                             2.8.0
torchaudio                        2.8.0
torchdata                         0.11.0
torchmetrics                      1.8.2
torchvision                       0.23.0
tornado                           6.1
tqdm                              4.67.1
traitlets                         5.14.3
transformer_engine_mdl            2.6.0+torch2.8.bf78e5d1
transformers                      4.57.1
transformers-stream-generator     0.0.5
transitions                       0.9.0
triton                            3.4.0
trl                               0.24.0
typeguard                         4.4.4
typer                             0.20.0
typing_extensions                 4.15.0
typing-inspection                 0.4.2
tzdata                            2025.2
umf                               0.11.0
uri-template                      1.3.0
urllib3                           2.5.0
uvicorn                           0.38.0
uvloop                            0.22.1
visions                           0.8.1
vllm                              0.11.0
wandb                             0.22.2
watchfiles                        1.1.1
wcmatch                           10.1
wcwidth                           0.2.14
webcolors                         24.11.1
webencodings                      0.5.1
websocket-client                  1.9.0
websockets                        15.0.1
Werkzeug                          3.1.3
wheel                             0.45.1
widgetsnbextension                4.0.14
wordcloud                         1.9.4
wrapt                             2.0.0
xformers                          0.0.32.post1
xgrammar                          0.1.25
xxhash                            3.6.0
yarl                              1.22.0
ydata-profiling                   4.17.0
zipp                              3.23.0
zstandard                         0.25.0
```

**Additional context**

**Comment by YY-WW518** [comment]
I encountered nearly the same issue as you, but I managed to get it running by adjusting the communication settings. However, it still throws an OOM error. I trained using 4*H20.

**Comment by Qiao0124** [comment]
I think it might be related to the model. A few days ago I did SFT on Qwen3-VL-32B with Swift followed by GRPO, this issue kept happening, and it was totally reproducible. 

But yesterday, after I redid the SFT and then ran GRPO again, the problem just disappeared. But I can’t remember what argument I changed. (though a new problem: "TypeError: argument of type 'RolloutInferRequest' is not iterable", I should open a new issue for that)

**Comment by hjh0119** [comment]
--vllm_use_async_engine false

**Comment by Qiao0124** [comment]
@hjh0119 but if i want to overwrite MultiTurnScheduler run(), i still need to set --vllm_use_async_engine true:
```python
        Important Notes:
            - Method overriding is only supported when using server mode (swift rollout)
              with vllm_use_async_engine=True
            - Custom implementations must maintain async/await compatibility
            - Ensure proper handling of conversation state across turns
```

and then it will still get stuck.

stack info:
```bash
Process 3803: /checkpoint/binary/train_package/python_bin -m torch.distributed.run --nproc_per_node 8 --master_port 33145 --nnodes 2 --node_rank 0 --master_addr xxx /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/swift/cli/rlhf.py --rlhf_type grpo --model /checkpoint/binary/train_package/output/models/Qwen3-VL-32B-Instruct/sft4grpo --external_plugins train/plugin.py --multi_turn_scheduler d2c_scheduler --max_turns 3 --agent_template hermes --loss_scale hermes --reward_funcs d2c_reward --use_vllm true --vllm_mode server --vllm_server_host xxx --vllm_server_port 8000 --vllm_server_timeout 300 --train_type full --torch_dtype bfloat16 --dataset train/data/grpo_train.jsonl --load_from_cache_file true --max_completion_length 8192 --num_train_epochs 1 --per_device_train_batch_size 1 --learning_rate 1e-6 --gradient_accumulation_steps 1 --save_strategy steps --save_steps 1000 --save_total_limit 10 --logging_steps 1 --output_dir output/models/Qwen3-VL-32B-Instruct/grpo --warmup_ratio 0.01 --dataloader_num_workers 1 --num_generations 8 --temperature 0.7 --padding_free true --attn_impl flash_attention_2 --deepspeed zero3 --move_model_batches 8 --add_version false --create_checkpoint_symlink true
Python v3.10.13+gc (/checkpoint/binary/train_package/python_bin)

Thread 3803 (idle): "MainThread"
    _invoke_run (torch/distributed/elastic/agent/server/api.py:879)
    run (torch/distributed/elastic/agent/server/api.py:715)
    wrapper (torch/distributed/elastic/metrics/api.py:138)
    launch_agent (torch/distributed/launcher/api.py:268)
    __call__ (torch/distributed/launcher/api.py:143)
    run (torch/distributed/run.py:892)
    main (torch/distributed/run.py:901)
    wrapper (torch/distributed/elastic/multiprocessing/errors/__init__.py:357)
    <module> (torch/distributed/run.py:905)
    _run_code (runpy.py:86)
    _run_module_as_main (runpy.py:196)

...

Process 3868: /checkpoint/binary/train_package/python_bin -u /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/swift/cli/rlhf.py --rlhf_type grpo --model /checkpoint/binary/train_package/output/models/Qwen3-VL-32B-Instruct/sft4grpo --external_plugins train/plugin.py --multi_turn_scheduler d2c_scheduler --max_turns 3 --agent_template hermes --loss_scale hermes --reward_funcs d2c_reward --use_vllm true --vllm_mode server --vllm_server_host xxx--vllm_server_port 8000 --vllm_server_timeout 300 --train_type full --torch_dtype bfloat16 --dataset train/data/grpo_train.jsonl --load_from_cache_file true --max_completion_length 8192 --num_train_epochs 1 --per_device_train_batch_size 1 --learning_rate 1e-6 --gradient_accumulation_steps 1 --save_strategy steps --save_steps 1000 --save_total_limit 10 --logging_steps 1 --output_dir output/models/Qwen3-VL-32B-Instruct/grpo --warmup_ratio 0.01 --dataloader_num_workers 1 --num_generations 8 --temperature 0.7 --padding_free true --attn_impl flash_attention_2 --deepspeed zero3 --move_model_batches 8 --add_version false --create_checkpoint_symlink true
Python v3.10.13+gc (/checkpoint/binary/train_package/python_bin)

Thread 3868 (idle): "MainThread"
    wait (threading.py:320)
    result (concurrent/futures/_base.py:453)
    infer (swift/trainers/rlhf_trainer/vllm_client.py:175)
    _engine_infer (swift/trainers/rlhf_trainer/rollout_mixin.py:800)
    _server_rollout (swift/trainers/rlhf_trainer/rollout_mixin.py:733)
    _rollout (swift/trainers/rlhf_trainer/rollout_mixin.py:487)
    _infer_single_or_multi_turn (swift/trainers/rlhf_trainer/rollout_mixin.py:525)
    _fast_infer (swift/trainers/rlhf_trainer/rollout_mixin.py:678)
    _generate_completions (swift/trainers/rlhf_trainer/grpo_trainer.py:201)
    _generate_and_score_completions (swift/trainers/rlhf_trainer/grpo_trainer.py:220)
    wrapper (swift/trainers/rlhf_trainer/utils.py:408)
    _prepare_inputs (swift/trainers/rlhf_trainer/grpo_trainer.py:177)
    wrapper (swift/trainers/rlhf_trainer/utils.py:408)
    training_step (transformers/trainer.py:4014)
    training_step (swift/trainers/rlhf_trainer/grpo_trainer.py:1665)
    _inner_training_loop (transformers/trainer.py:2674)
    train (transformers/trainer.py:2325)
    train (swift/trainers/mixin.py:816)
    train (swift/llm/train/sft.py:244)
    run (swift/llm/train/sft.py:196)
    wrapper (swift/ray/base.py:170)
    main (swift/llm/base.py:49)
    rlhf_main (swift/llm/train/rlhf.py:233)
    <module> (swift/cli/rlhf.py:7)
Thread 4253 (idle): "Thread-2"
    wait (threading.py:324)
    wait (threading.py:607)
    run (tqdm/_monitor.py:60)
    _bootstrap_inner (threading.py:1016)
    _bootstrap (threading.py:973)
Thread 4365 (idle): "Thread-3"
    wait (threading.py:324)
    get (queue.py:180)
    _run (tensorboard/summary/writer/event_file_writer.py:269)
    run (tensorboard/summary/writer/event_file_writer.py:244)
    _bootstrap_inner (threading.py:1016)
    _bootstrap (threading.py:973)
Thread 4366 (idle): "Thread-4"
    wait (threading.py:324)
    wait (threading.py:607)
    run (tqdm/_monitor.py:60)
    _bootstrap_inner (threading.py:1016)
    _bootstrap (threading.py:973)
Thread 4510 (idle): "ThreadPoolExecutor-140_0"
    readinto (socket.py:705)
    _read_status (http/client.py:279)
    begin (http/client.py:318)
    getresponse (http/client.py:1375)
    getresponse (urllib3/connection.py:565)
    _make_request (urllib3/connectionpool.py:536)
    urlopen (urllib3/connectionpool.py:803)
    send (requests/adapters.py:658)
    send (requests/sessions.py:703)
    request (requests/sessions.py:589)
    post (requests/sessions.py:637)
    process_chunk (swift/trainers/rlhf_trainer/vllm_client.py:144)
    run (concurrent/futures/thread.py:58)
    _worker (concurrent/futures/thread.py:83)
    run (threading.py:953)
    _bootstrap_inner (threading.py:1016)
    _bootstrap (threading.py:973)
```

**Comment by casper-hansen** [comment]
Might be related to torch 2.9 bug https://github.com/pytorch/pytorch/issues/166643

Official workaround should be `pip install 'nvidia-cudnn-cu12>=9.15.0.57'` from the info in the issue.

TRL also having same issue https://github.com/huggingface/trl/issues/4559

**Comment by hjh0119** [comment]
async_engine with scheduler(multi turn rollout) should work fine

async_engine w/o scheduler is fixed in https://github.com/modelscope/ms-swift/pull/6786

**Comment by Qiao0124** [comment]
I pulled the latest ms-swift code and it worked, and my env and other dependencies doesn't changed. Thank you all!

**Comment by aprylewu** [comment]
hello，遇到了同样的问题，
swift rlhf
    --rlhf_type grpo
    # 基础模型
    --model "${ACTOR_MODEL}"
    # 加载自定义reward function
    --external_plugins /workspace/training/grpo/vc_orm.py
    --reward_funcs qa
    # 使用外部 rollout vLLM
    --use_vllm true
    --vllm_mode server
    --vllm_use_async_engine false
    --train_type lora
    --lora_rank ${LORA_RANK}
    --lora_alpha ${LORA_ALPHA}
    --lora_dropout ${LORA_DROPOUT}
    --target_modules "${LORA_TARGET_MODULES}"
    --torch_dtype bfloat16
    # 数据集
    --dataset "${TRAIN_DATASET}"
    --load_from_cache_file false
    # 生成配置
    --max_completion_length 2048
    --temperature 1.0
    --repetition_penalty 1.1
    # 训练配置
    --num_train_epochs 1
    --per_device_train_batch_size 1
    --gradient_accumulation_steps 1
    --gradient_checkpointing true
    --learning_rate "${LORA_LEARNING_RATE}"
    --warmup_ratio 0.05
    --num_generations 8
    --num_iterations 2
    --beta 0.001
    --max_grad_norm 0.5
    --async_generate false
    # 保存策略
    --save_strategy steps
    --save_steps 100
    --save_total_limit 5
    # 评估策略
    --eval_strategy steps
    --eval_steps 50
    --per_device_eval_batch_size 1
    # 日志
    --logging_steps 1
    --log_completions true
    # 输出
    --output_dir "${OUTPUT_DIR}"
    # 数据加载
    --dataloader_num_workers 0
    --dataset_num_proc 1
    # DeepSpeed ZeRO-3
    --deepspeed zero3_offload
    # Wandb - 只有rank 0报告
    --report_to "${REPORT_TO}"
    # 视觉编码器配置
    --freeze_vit true
    --freeze_aligner true

问题同样，master 节点的 GPU 利用率0号卡为0，其他为满
rlhf日志末尾
wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script.
wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/

Train:   0%|          | 0/12912 [00:00<?, ?it/s]

**Comment by aprylewu** [comment]
同时，注意到rollout这边脚本会报
  0%|          | 0/64 [00:00<?, ?it/s]
  2%|▏         | 1/64 [00:06<06:18,  6.01s/it]
  3%|▎         | 2/64 [00:06<02:40,  2.58s/it]
  5%|▍         | 3/64 [00:06<01:28,  1.46s/it]
  6%|▋         | 4/64 [00:06<00:56,  1.07it/s]
 11%|█         | 7/64 [00:06<00:21,  2.70it/s]
 14%|█▍        | 9/64 [00:06<00:15,  3.60it/s]
 17%|█▋        | 11/64 [00:07<00:13,  4.07it/s]
 19%|█▉        | 12/64 [00:07<00:11,  4.55it/s]
 23%|██▎       | 15/64 [00:07<00:06,  7.04it/s]
 27%|██▋       | 17/64 [00:07<00:06,  7.38it/s]
 31%|███▏      | 20/64 [00:07<00:05,  8.31it/s]
 36%|███▌      | 23/64 [00:08<00:03, 11.15it/s]
 41%|████      | 26/64 [00:08<00:02, 13.37it/s]
 44%|████▍     | 28/64 [00:08<00:04,  8.98it/s]
 48%|████▊     | 31/64 [00:08<00:02, 11.36it/s]
 52%|█████▏    | 33/64 [00:09<00:02, 10.94it/s]
 56%|█████▋    | 36/64 [00:09<00:02, 12.91it/s]
 59%|█████▉    | 38/64 [00:09<00:02, 12.46it/s]
 62%|██████▎   | 40/64 [00:09<00:01, 12.72it/s]
 67%|██████▋   | 43/64 [00:09<00:01, 13.47it/s]
 70%|███████   | 45/64 [00:10<00:02,  8.79it/s]
 73%|███████▎  | 47/64 [00:10<00:01, 10.15it/s]
 77%|███████▋  | 49/64 [00:10<00:01,  8.86it/s]
 80%|███████▉  | 51/64 [00:10<00:01, 10.39it/s]
 83%|████████▎ | 53/64 [00:10<00:01,  8.88it/s]
 86%|████████▌ | 55/64 [00:11<00:01,  7.77it/s]
 88%|████████▊ | 56/64 [00:11<00:01,  4.53it/s]
显示不知道在加载什么东西，但是就卡在这里了

**Comment by alanshaoTT** [comment]
> hello，遇到了同样的问题， swift rlhf --rlhf_type grpo # 基础模型 --model "${ACTOR_MODEL}" # 加载自定义reward function --external_plugins /workspace/training/grpo/vc_orm.py --reward_funcs qa # 使用外部 rollout vLLM --use_vllm true --vllm_mode server --vllm_use_async_engine false --train_type lora --lora_rank ${LORA_RANK} --lora_alpha ${LORA_ALPHA} --lora_dropout ${LORA_DROPOUT} --target_modules "${LORA_TARGET_MODULES}" --torch_dtype bfloat16 # 数据集 --dataset "${TRAIN_DATASET}" --load_from_cache_file false # 生成配置 --max_completion_length 2048 --temperature 1.0 --repetition_penalty 1.1 # 训练配置 --num_train_epochs 1 --per_device_train_batch_size 1 --gradient_accumulation_steps 1 --gradient_checkpointing true --learning_rate "${LORA_LEARNING_RATE}" --warmup_ratio 0.05 --num_generations 8 --num_iterations 2 --beta 0.001 --max_grad_norm 0.5 --async_generate false # 保存策略 --save_strategy steps --save_steps 100 --save_total_limit 5 # 评估策略 --eval_strategy steps --eval_steps 50 --per_device_eval_batch_size 1 # 日志 --logging_steps 1 --log_completions true # 输出 --output_dir "${OUTPUT_DIR}" # 数据加载 --dataloader_num_workers 0 --dataset_num_proc 1 # DeepSpeed ZeRO-3 --deepspeed zero3_offload # Wandb - 只有rank 0报告 --report_to "${REPORT_TO}" # 视觉编码器配置 --freeze_vit true --freeze_aligner true
> 
> 问题同样，master 节点的 GPU 利用率0号卡为0，其他为满 rlhf日志末尾 wandb: Use W&B Weave for improved LLM call tracing. Install Weave with `pip install weave` then add `import weave` to the top of your script. wandb: For more information, check out the docs at: https://weave-docs.wandb.ai/
> 
> Train: 0%| | 0/12912 [00:00<?, ?it/s]

请问解决了吗  我也遇到了同样的问题
