### ISSUE TITLE
qwen3-vl,grpo训练一步耗时太长且触发NCCL错误

### ISSUE THREAD

**Issue by Vanza11** [modelscope/ms-swift#6877]
在使用经过sft后的qwen3-vl模型进行grpo训练时，模型和数据都是本地的，出现ProcessGroupNCCL报错，单步耗时几千秒且第六步之后中断，报错信息如下：
[INFO:swift] model_parameter_info: PeftModelForCausalLM: 4454.3309M Params (16.5151M Trainable [0.3708%]), 0.0001M Buffers.
[2025-12-01 23:44:29] WARNING connectionpool.py:868: Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f101f79fed0>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/revisions
[2025-12-01 23:44:29] WARNING connectionpool.py:868: Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5f8763e250>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/revisions
[2025-12-01 23:44:29] WARNING connectionpool.py:868: Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb03728bb90>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/revisions
[2025-12-01 23:44:29] WARNING connectionpool.py:868: Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe0a9f35610>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/revisions
[2025-12-01 23:44:31] WARNING connectionpool.py:868: Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f11004f6510>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/revisions
[2025-12-01 23:44:31] WARNING connectionpool.py:868: Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f11004f7d50>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/repo/files?Revision=master&Recursive=True
[2025-12-01 23:44:31] WARNING connectionpool.py:868: Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5f8763e7d0>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/revisions
[2025-12-01 23:44:31] WARNING connectionpool.py:868: Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5f87640190>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/repo/files?Revision=master&Recursive=True
[2025-12-01 23:44:31] WARNING connectionpool.py:868: Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb0372921d0>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/revisions
[2025-12-01 23:44:31] WARNING connectionpool.py:868: Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb037293b50>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/repo/files?Revision=master&Recursive=True
[2025-12-01 23:44:31] WARNING connectionpool.py:868: Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe0a8762510>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/revisions
[2025-12-01 23:44:31] WARNING connectionpool.py:868: Retrying (Retry(total=1, connect=1, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe0a8763ad0>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/repo/files?Revision=master&Recursive=True
[2025-12-01 23:44:33] WARNING connectionpool.py:868: Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f101f7ac6d0>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/repo/files?Revision=master&Recursive=True
[INFO:swift] use_reentrant: True
[INFO:swift] The logging file will be saved in: /public/home/lab10/xuyingrong/TableRecognition/TableRecognition/output/GRPO_TableRecognition/v47-20251201-234422/logging.jsonl
[INFO:swift] Successfully registered post_encode hook: ['PeftModelForCausalLM'].
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
[2025-12-01 23:44:33] WARNING connectionpool.py:868: Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5f87640ad0>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/repo/files?Revision=master&Recursive=True
[2025-12-01 23:44:33] WARNING connectionpool.py:868: Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb0372944d0>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/repo/files?Revision=master&Recursive=True
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
[2025-12-01 23:44:33] WARNING connectionpool.py:868: Retrying (Retry(total=0, connect=0, read=2, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe0a8764750>: Failed to resolve 'www.modelscope.cn' ([Errno -2] Name or service not known)")': /api/v1/models/unknown/repo/files?Revision=master&Recursive=True
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 151645, 'bos_token_id': None}.

Train:   0%|          | 0/15000 [00:00<?, ?it/s]/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

Train:   0%|          | 1/15000 [19:44<4934:34:14, 1184.38s/it]
                                                               

Train:   0%|          | 1/15000 [19:44<4934:34:14, 1184.38s/it]
Train:   0%|          | 1/15000 [19:44<4934:34:14, 1184.38s/it][INFO:swift] Overriding multi-modal data from rollout_infos for key: images

Train:   0%|          | 2/15000 [1:28:48<12187:33:13, 2925.40s/it]
Train:   0%|          | 3/15000 [5:48:40<36281:58:09, 8709.41s/it]
Train:   0%|          | 4/15000 [9:41:47<44957:20:13, 10792.64s/it]
Train:   0%|          | 5/15000 [10:04:13<30766:23:03, 7386.39s/it]
                                                                   

Train:   0%|          | 5/15000 [10:04:13<30766:23:03, 7386.39s/it]
Train:   0%|          | 5/15000 [10:04:13<30766:23:03, 7386.39s/it]
Train:   0%|          | 6/15000 [10:46:01<23855:30:25, 5727.61s/it][rank0]:[E1202 11:06:56.320643155 ProcessGroupNCCL.cpp:683] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1236, OpType=ALLREDUCE, NumelIn=16515072, NumelOut=16515072, Timeout(ms)=600000) ran for 600043 milliseconds before timing out.
[rank1]:[E1202 11:06:56.348742890 ProcessGroupNCCL.cpp:683] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1236, OpType=ALLREDUCE, NumelIn=16515072, NumelOut=16515072, Timeout(ms)=600000) ran for 600077 milliseconds before timing out.
[rank2]:[E1202 11:06:56.382614623 ProcessGroupNCCL.cpp:683] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1236, OpType=ALLREDUCE, NumelIn=16515072, NumelOut=16515072, Timeout(ms)=600000) ran for 600094 milliseconds before timing out.
[rank3]:[E1202 11:06:56.406819086 ProcessGroupNCCL.cpp:683] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1236, OpType=ALLREDUCE, NumelIn=16515072, NumelOut=16515072, Timeout(ms)=600000) ran for 600094 milliseconds before timing out.
[rank2]:[E1202 11:06:57.945662494 ProcessGroupNCCL.cpp:2241] [PG ID 1 PG GUID 1 Rank 2]  failure detected by watchdog at work sequence id: 1236 PG status: last enqueued work: 1237, last completed work: 1235
[rank0]:[E1202 11:06:57.945665654 ProcessGroupNCCL.cpp:2241] [PG ID 1 PG GUID 1 Rank 0]  failure detected by watchdog at work sequence id: 1236 PG status: last enqueued work: 1237, last completed work: 1235
[rank2]:[E1202 11:06:57.945689871 ProcessGroupNCCL.cpp:730] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank1]:[E1202 11:06:57.945654446 ProcessGroupNCCL.cpp:2241] [PG ID 1 PG GUID 1 Rank 1]  failure detected by watchdog at work sequence id: 1236 PG status: last enqueued work: 1237, last completed work: 1235
[rank0]:[E1202 11:06:57.945707501 ProcessGroupNCCL.cpp:730] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank1]:[E1202 11:06:57.945716749 ProcessGroupNCCL.cpp:730] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank3]:[E1202 11:06:57.945693154 ProcessGroupNCCL.cpp:2241] [PG ID 1 PG GUID 1 Rank 3]  failure detected by watchdog at work sequence id: 1236 PG status: last enqueued work: 1237, last completed work: 1235
[rank0]:[E1202 11:06:57.945756057 ProcessGroupNCCL.cpp:2573] [PG ID 1 PG GUID 1 Rank 0] First PG on this rank to signal dumping.
[rank3]:[E1202 11:06:57.945760450 ProcessGroupNCCL.cpp:730] Stack trace of the failed collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank2]:[E1202 11:06:57.945822468 ProcessGroupNCCL.cpp:2573] [PG ID 1 PG GUID 1 Rank 2] First PG on this rank to signal dumping.
[rank1]:[E1202 11:06:57.945842763 ProcessGroupNCCL.cpp:2573] [PG ID 1 PG GUID 1 Rank 1] First PG on this rank to signal dumping.
[rank3]:[E1202 11:06:57.945876650 ProcessGroupNCCL.cpp:2573] [PG ID 1 PG GUID 1 Rank 3] First PG on this rank to signal dumping.
[rank1]:[E1202 11:06:57.639442577 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 1] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 185, last completed NCCL work: 185.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc. 
[rank3]:[E1202 11:06:57.640136272 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 3] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 185, last completed NCCL work: 185.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc. 
[rank2]:[E1202 11:06:57.640295784 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 2] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 185, last completed NCCL work: 185.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc. 
[rank0]:[E1202 11:06:57.640667771 ProcessGroupNCCL.cpp:1858] [PG ID 0 PG GUID 0(default_pg) Rank 0] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 185, last completed NCCL work: 185.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc. 
[rank1]:[E1202 11:06:57.680367963 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 1] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
[rank3]:[E1202 11:06:57.680395626 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 3] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
[rank2]:[E1202 11:06:57.680435189 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 2] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
[rank0]:[E1202 11:06:57.680521142 ProcessGroupNCCL.cpp:1575] [PG ID 0 PG GUID 0(default_pg) Rank 0] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
[rank3]:[E1202 11:07:57.610822254 ProcessGroupNCCL.cpp:744] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E1202 11:07:57.610890563 ProcessGroupNCCL.cpp:758] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
[rank3]:[E1202 11:07:57.614261563 ProcessGroupNCCL.cpp:2057] [PG ID 1 PG GUID 1 Rank 3] Process group watchdog thread terminated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1236, OpType=ALLREDUCE, NumelIn=16515072, NumelOut=16515072, Timeout(ms)=600000) ran for 600094 milliseconds before timing out.
Exception raised from checkTimeout at /pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:686 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (0x7fe4dc74bb80 in /public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x247 (0x7fe4dd626407 in /public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x1691 (0x7fe4dd62b011 in /public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (0x7fe4dd62c25f in /public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xdbbf4 (0x7fe5344c7bf4 in /public/home/lab10/miniconda3/envs/tablerecognition/bin/../lib/libstdc++.so.6)
frame #5: <unknown function> + 0x94ac3 (0x7fe53ca21ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x7fe53cab3850 in /lib/x86_64-linux-gnu/libc.so.6)

W1202 11:07:58.234000 4019012 site-packages/torch/distributed/elastic/multiprocessing/api.py:908] Sending process 4019064 closing signal SIGTERM
W1202 11:07:58.236000 4019012 site-packages/torch/distributed/elastic/multiprocessing/api.py:908] Sending process 4019065 closing signal SIGTERM
W1202 11:07:58.237000 4019012 site-packages/torch/distributed/elastic/multiprocessing/api.py:908] Sending process 4019066 closing signal SIGTERM
E1202 11:07:59.967000 4019012 site-packages/torch/distributed/elastic/multiprocessing/api.py:882] failed (exitcode: -6) local_rank: 3 (pid: 4019067) of binary: /public/home/lab10/miniconda3/envs/tablerecognition/bin/python3.11
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/distributed/run.py", line 940, in <module>
    main()
  File "/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 357, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/distributed/run.py", line 936, in main
    run(args)
  File "/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/distributed/run.py", line 927, in run
    elastic_launch(
  File "/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 156, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/lab10/miniconda3/envs/tablerecognition/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 293, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

运行脚本：
export NPROC_PER_NODE=4
export MAX_PIXELS=200704
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:128
export MASTER_PORT=29501
export TORCH_CUDNN_V8_API_ENABLED=1

# GPU内存管理设置 - 优化内存分配
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:128,garbage_collection_threshold:0.6

# GRPO训练命令
NPROC_PER_NODE=4 \
swift rlhf \
    --rlhf_type grpo \
    --model models/Qwen3-VL-4B-Instruct-sft_merged \
    --external_plugins ${PROJECT_ROOT}/plugin/plugin.py \
    --reward_funcs my_reward \
    --multi_turn_scheduler my_scheduler \
    --max_turns 7 \
    --use_vllm false \
    --train_type lora \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --torch_dtype bfloat16 \
    --dataset ${PROJECT_ROOT}/datasets/train_2k.jsonl \
    --max_completion_length 10240 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --learning_rate 2e-5 \
    --dataloader_num_workers 4 \
    --save_strategy steps \
    --save_steps 200 \
    --logging_steps 5 \
    --output_dir ${OUTPUT_DIR} \
    --warmup_ratio 0.05 \
    --num_generations 2 \
    --temperature 1.0 \
    --repetition_penalty 1.1 \
    --system ${PROJECT_ROOT}/scripts/system_prompt.txt \
    --deepspeed zero2 \
    --log_completions true \
    --report_to none \
    --swanlab_mode local \
    --run_name "GRPO_$(date +%Y%m%d_%H%M%S)" \
    --beta 0.001 \
    --max_grad_norm 1.0

使用4×H100-80G

**Comment by hjh0119** [comment]
IMAGE_MAX_TOKEN_NUM https://swift.readthedocs.io/zh-cn/latest/Instruction/Command-line-parameters.html#qwen3-vl
```diff
- MAX_PIXELS
+ IMAGE_MAX_TOKEN_NUM
```

use pytorch < 2.9

**Comment by Vanza11** [comment]
> IMAGE_MAX_TOKEN_NUM https://swift.readthedocs.io/zh-cn/latest/Instruction/Command-line-parameters.html#qwen3-vl
> 
> - MAX_PIXELS
> + IMAGE_MAX_TOKEN_NUM
> use pytorch < 2.9

The problem is solved!  Thank you very much!!!

**Comment by Dswn888** [comment]
> > IMAGE_MAX_TOKEN_NUM https://swift.readthedocs.io/zh-cn/latest/Instruction/Command-line-parameters.html#qwen3-vl
> > 
> > * MAX_PIXELS
> > 
> > 
> > * IMAGE_MAX_TOKEN_NUM
> >   use pytorch < 2.9
> 
> The problem is solved! Thank you very much!!!

你好，我想请问下问题的解决是通过使用pytorch小于2.9的版本还是通过设定image_max_token_num解决的呢

**Comment by Vanza11** [comment]
> > > IMAGE_MAX_TOKEN_NUM https://swift.readthedocs.io/zh-cn/latest/Instruction/Command-line-parameters.html#qwen3-vl
> > > 
> > > * MAX_PIXELS
> > > * IMAGE_MAX_TOKEN_NUM
> > >   use pytorch < 2.9
> > 
> > 
> > The problem is solved! Thank you very much!!!
> 
> 你好，我想请问下问题的解决是通过使用pytorch小于2.9的版本还是通过设定image_max_token_num解决的呢

我检查了一下环境中一些重要依赖包的版本，有几个包的版本不对，修改之后就可以了

**Comment by Dswn888** [comment]
> > > > IMAGE_MAX_TOKEN_NUM https://swift.readthedocs.io/zh-cn/latest/Instruction/Command-line-parameters.html#qwen3-vl
> > > > 
> > > > * MAX_PIXELS
> > > > * IMAGE_MAX_TOKEN_NUM
> > > >   use pytorch < 2.9
> > > 
> > > 
> > > The problem is solved! Thank you very much!!!
> > 
> > 
> > 你好，我想请问下问题的解决是通过使用pytorch小于2.9的版本还是通过设定image_max_token_num解决的呢
> 
> 我检查了一下环境中一些重要依赖包的版本，有几个包的版本不对，修改之后就可以了

好嘞感谢，可以问下是怎么检查的吗，是参照图片里的包的要求吗（我也遇到了类似的报错https://github.com/modelscope/ms-swift/issues/6927）
<img width="1288" height="1208" alt="Image" src="https://github.com/user-attachments/assets/78142665-e855-4c46-836e-3671d849b049" />
我的库版本是如下内容，按理说应该是按照官方的要求配好了呀：
python==3.11.2
transformers==4.57.1
qwen_vl_utils==0.0.14
ms-swift==3.10.3
deepspeed==0.17.6
vllm==0.11.0
trl==0.24.0
torch==2.8.0

方便分享一下你的包的版本嘛？

**Comment by Vanza11** [comment]
> > > > > IMAGE_MAX_TOKEN_NUM https://swift.readthedocs.io/zh-cn/latest/Instruction/Command-line-parameters.html#qwen3-vl
> > > > > 
> > > > > * MAX_PIXELS
> > > > > * IMAGE_MAX_TOKEN_NUM
> > > > >   use pytorch < 2.9
> > > > 
> > > > 
> > > > The problem is solved! Thank you very much!!!
> > > 
> > > 
> > > 你好，我想请问下问题的解决是通过使用pytorch小于2.9的版本还是通过设定image_max_token_num解决的呢
> > 
> > 
> > 我检查了一下环境中一些重要依赖包的版本，有几个包的版本不对，修改之后就可以了
> 
> 好嘞感谢，可以问下是怎么检查的吗，是参照图片里的包的要求吗（我也遇到了类似的报错[https://github.com/modelscope/ms-swift/issues/6927）](https://github.com/modelscope/ms-swift/issues/6927%EF%BC%89) <img alt="Image" width="1288" height="1208" src="https://private-user-images.githubusercontent.com/64242289/523446402-78142665-e855-4c46-836e-3671d849b049.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUyNTI5NjAsIm5iZiI6MTc2NTI1MjY2MCwicGF0aCI6Ii82NDI0MjI4OS81MjM0NDY0MDItNzgxNDI2NjUtZTg1NS00YzQ2LTgzNmUtMzY3MWQ4NDliMDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA5VDAzNTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMjNmY2I4MTkwY2MzYzJmMjQzN2E4YjAwNjNjOTEzYTk3MTlmYmIwZDU0NTliMDQ0ZjRmODI1OGNmNzQ4OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lQ7BiQXSd5EeKom6ooaJpGStL-254nYzWfyk-GmXaAM"> 我的库版本是如下内容，按理说应该是按照官方的要求配好了呀： python==3.11.2 transformers==4.57.1 qwen_vl_utils==0.0.14 ms-swift==3.10.3 deepspeed==0.17.6 vllm==0.11.0 trl==0.24.0 torch==2.8.0
> 
> 方便分享一下你的包的版本嘛？

我的版本是：
python==3.11.14
transformers==4.57.1
qwen_vl_utils==0.0.14
ms-swift==3.9.2
deepspeed==0.17.5
vllm==0.11.0
trl==0.23.1
torch==2.8.0

**Comment by Dswn888** [comment]
> > > > > > IMAGE_MAX_TOKEN_NUM https://swift.readthedocs.io/zh-cn/latest/Instruction/Command-line-parameters.html#qwen3-vl
> > > > > > 
> > > > > > * MAX_PIXELS
> > > > > > * IMAGE_MAX_TOKEN_NUM
> > > > > >   use pytorch < 2.9
> > > > > 
> > > > > 
> > > > > The problem is solved! Thank you very much!!!
> > > > 
> > > > 
> > > > 你好，我想请问下问题的解决是通过使用pytorch小于2.9的版本还是通过设定image_max_token_num解决的呢
> > > 
> > > 
> > > 我检查了一下环境中一些重要依赖包的版本，有几个包的版本不对，修改之后就可以了
> > 
> > 
> > 好嘞感谢，可以问下是怎么检查的吗，是参照图片里的包的要求吗（我也遇到了类似的报错[https://github.com/modelscope/ms-swift/issues/6927）](https://github.com/modelscope/ms-swift/issues/6927%EF%BC%89) <img alt="Image" width="1288" height="1208" src="https://private-user-images.githubusercontent.com/64242289/523446402-78142665-e855-4c46-836e-3671d849b049.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUyNTI5NjAsIm5iZiI6MTc2NTI1MjY2MCwicGF0aCI6Ii82NDI0MjI4OS81MjM0NDY0MDItNzgxNDI2NjUtZTg1NS00YzQ2LTgzNmUtMzY3MWQ4NDliMDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA5VDAzNTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMjNmY2I4MTkwY2MzYzJmMjQzN2E4YjAwNjNjOTEzYTk3MTlmYmIwZDU0NTliMDQ0ZjRmODI1OGNmNzQ4OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lQ7BiQXSd5EeKom6ooaJpGStL-254nYzWfyk-GmXaAM"> 我的库版本是如下内容，按理说应该是按照官方的要求配好了呀： python==3.11.2 transformers==4.57.1 qwen_vl_utils==0.0.14 ms-swift==3.10.3 deepspeed==0.17.6 vllm==0.11.0 trl==0.24.0 torch==2.8.0
> > 方便分享一下你的包的版本嘛？
> 
> 我的版本是： python==3.11.14 transformers==4.57.1 qwen_vl_utils==0.0.14 ms-swift==3.9.2 deepspeed==0.17.5 vllm==0.11.0 trl==0.23.1 torch==2.8.0

好嘞收到，十分感谢
