### ISSUE TITLE
H20上sft google/gemma-3n-E4B 模型出现 cuda error

### ISSUE THREAD

**Issue by LiXinYuECNU** [modelscope/ms-swift#7266]
类似的代码，我使用google/gemma-3n-E2B就不会报错，请问怎么解决
`swift sft \
    --dataset xxx/jsons_chat/chat_zh/train_all_chat.json \
    --model xxx/models/google/gemma-3n-E4B \
    --train_type full \
    --torch_dtype bfloat16 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --learning_rate 3e-5 \
    --lr_scheduler_type cosine_with_min_lr --lr_scheduler_kwargs '{"min_lr": 0}' \
    --lora_rank 32 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --target_modules all-linear \
    --gradient_accumulation_steps 16 \
    --max_length 8192 \
    --save_steps 1000 \
    --logging_steps 100 \
    --truncation_strategy left \
    --output_dir output \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 16 \
    --model_author swift \
    --model_name swift-robot \
    --save_total_limit 2 \
    2>&1 | tee "$LOGFILE"`

Train:   0%|          | 2/1304 [00:16<2:57:59,  8.20s/it][A[rank1]: Traceback (most recent call last):
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/cli/sft.py", line 20, in <module>
[rank1]:     sft_main()
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/train/sft.py", line 353, in sft_main
[rank1]:     return SwiftSft(args).main()
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/base.py", line 49, in main
[rank1]:     result = self.run()
[rank1]:              ^^^^^^^^^^
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/ray/base.py", line 170, in wrapper
[rank1]:     return func(self, *args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/train/sft.py", line 207, in run
[rank1]:     return self.train(trainer)
[rank1]:            ^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/train/sft.py", line 255, in train
[rank1]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/trainers/mixin.py", line 815, in train
[rank1]:     res = super().train(*args, **kwargs)
[rank1]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/transformers/trainer.py", line 2325, in train
[rank1]:     return inner_training_loop(
[rank1]:            ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/transformers/trainer.py", line 2715, in _inner_training_loop
[rank1]:     _grad_norm = self.accelerator.clip_grad_norm_(
[rank1]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/trainers/mixin.py", line 617, in clip_grad_norm_
[rank1]:     if isinstance(grad_norm, torch.Tensor) and grad_norm.isnan().item():
[rank1]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: torch.AcceleratorError: CUDA error: an illegal memory access was encountered
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by LiXinYuECNU** [comment]
如果 --max_grad_norm 0 \
模型可以正常推理了，不会报错，但是这样梯度设置有问题吧

**Comment by LiXinYuECNU** [comment]
还会有些这样的warning
[rank7]:[W1231 14:33:47.872305194 CUDAGuardImpl.h:122] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank7]:[W1231 14:33:47.872347893 CUDAGuardImpl.h:122] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank7]:[W1231 14:33:47.872368123 CUDAGuardImpl.h:122] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank7]:[W1231 14:33:47.872377653 CUDAGuardImpl.h:122] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank7]:[W1231 14:33:47.872385202 CUDAGuardImpl.h:122] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank7]:[W1231 14:33:47.872406292 CUDAGuardImpl.h:122] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank7]:[W1231 14:33:47.872413752 CUDAGuardImpl.h:122] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank7]:[W1231 14:33:47.872421052 CUDAGuardImpl.h:122] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)

**Comment by LiXinYuECNU** [comment]
尝试升级了ms-swift的版本，依然会报错
[A{'loss': 23.2534771, 'grad_norm': 2544.0, 'learning_rate': 4.5e-07, 'token_acc': 0.0, 'epoch': 0.0, 'global_step/max_steps': '1/1304', 'percentage': '0.08%', 'elapsed_time': '9s', 'remaining_time': '3h 20m 51s', 'memory(GiB)': 65.99, 'train_speed(iter/s)': 0.108121}


Train:   0%|          | 1/1304 [00:09<3:14:37,  8.96s/it][A

Train:   0%|          | 1/1304 [00:09<3:14:37,  8.96s/it][A

Train:   0%|          | 2/1304 [00:16<2:56:25,  8.13s/it][A[rank3]: Traceback (most recent call last):
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/cli/sft.py", line 20, in <module>
[rank3]:     sft_main()
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/train/sft.py", line 365, in sft_main
[rank3]:     return SwiftSft(args).main()
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/base.py", line 49, in main
[rank3]:     result = self.run()
[rank3]:              ^^^^^^^^^^
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/ray/base.py", line 170, in wrapper
[rank3]:     return func(self, *args, **kwargs)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/train/sft.py", line 210, in run
[rank3]:     return self.train(trainer)
[rank3]:            ^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/llm/train/sft.py", line 258, in train
[rank3]:     trainer.train(trainer.args.resume_from_checkpoint)
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/trainers/mixin.py", line 880, in train
[rank3]:     res = super().train(*args, **kwargs)
[rank3]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/transformers/trainer.py", line 2325, in train
[rank3]:     return inner_training_loop(
[rank3]:            ^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/transformers/trainer.py", line 2715, in _inner_training_loop
[rank3]:     _grad_norm = self.accelerator.clip_grad_norm_(
[rank3]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/root/miniconda3/lib/python3.11/site-packages/swift/trainers/mixin.py", line 634, in clip_grad_norm_
[rank3]:     if isinstance(grad_norm, torch.Tensor) and grad_norm.isnan().item():
[rank3]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]: torch.AcceleratorError: CUDA error: an illegal memory access was encountered
[rank3]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank3]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank3]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by RewindL** [comment]
这种一般就是爆显存了吧，把Deepspeed打开

**Comment by LiXinYuECNU** [comment]
这个模型本身不大，而且batch是1，单卡96G的显存，应该不是爆显存的问题，而且爆显存也不是这个error吧

**Comment by liuhongye216** [comment]
是不是代码中显式指定了cuda:1或者cuda:2但是实际只有一块卡？

**Comment by z0o0ey** [comment]
请使用最新版本的 Swift 和 vLLM 再次尝试；如果问题依然存在，欢迎重新开启此 Issue 或创建新的 Issue。
