### ISSUE TITLE
使用 GPT OSS 进行 Megatron GRPO 训练时，在 rollout server 上首次执行 update_flattened_params 时发生错误

### ISSUE THREAD

**Issue by akpe12** [modelscope/ms-swift#7270]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

当按照以下步骤进行训练时，rollout server 上发生了错误。

运行 rollout server
使用的命令：
CUDA_VISIBLE_DEVICES=1 swift rollout --model /home/jovyan/pretrained-models/models/openai/gpt-oss-120b --vllm_max_model_len 65536 --port 8000

运行训练脚本
使用的脚本：
NCCL_P2P_DISABLE=1 \
MEGATRON_LM_PATH="/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM" \
CUDA_VISIBLE_DEVICES=2,3,4,5 \
NPROC_PER_NODE=4 \
PYTORCH_CUDA_ALLOC_CONF='expandable_segments:True' \
megatron rlhf \
    --rlhf_type grpo \
    --model '/home/jovyan/pretrained-models/models/openai/gpt-oss-120b' \
    --load_safetensors true \
    --save_safetensors true \
    --merge_lora false \
    --context_parallel_size 1 \
    --tensor_model_parallel_size 1 \
    --expert_model_parallel_size 1 \
    --pipeline_model_parallel_size 4 \
    --dataset '/home/jovyan/text-llm/experiment/model_dev/1.5.1.1/omniverse/save/stages/3_grpo/data/stage_3_data.json' \
    --max_epochs 1 \
    --global_batch_size 4 \
    --micro_batch_size 1 \
    --generation_batch_size 4 \
    --num_generations 2 \
    --reward_funcs format \
    --use_vllm true \
    --vllm_mode server \
    --vllm_server_host 127.0.0.1 \
    --vllm_server_port 8000 \
    --max_length 1024 \
    --max_completion_length 512 \
    --train_type lora \
    --lora_rank 8 \
    --lora_alpha 32 \
    --target_modules all-linear \
    --lr 5e-5 \
    --bf16 true \
    --beta 0.04 \
    --importance_sampling_level sequence \
    --epsilon 3e-4 \
    --epsilon_high 4e-4 \
    --dynamic_sample false \
    --overlong_filter true \
    --loss_type grpo \
    --sleep_level 2 \
    --offload_model true \
    --offload_bridge false \
    --offload_optimizer true \
    --log_interval 1 \
    --recompute_granularity selective \
    --finetune \
    --num_workers 8 \
    --dataset_num_proc 8 \
    --no_save_optim \
    --no_save_rng \
    --attention_backend flash \
    --temperature 1.0 \
    --padding_free false \
    --sequence_parallel false \
    --log_completions true \
    --softmax_type vanilla \

在执行训练脚本、即将开始 epoch 0 时，rollout server 在进行 post update_flattened_params 的同时发生了如下错误。

INFO:     127.0.0.1:43474 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] Invocation of collective_rpc method failed
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] Traceback (most recent call last):
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 777, in _handle_client_request
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     result = method(*self._convert_msgspec_args(method, args))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 416, in collective_rpc
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return self.model_executor.collective_rpc(method, timeout, args,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 83, incollective_rpc
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return func(*args, **kwargs)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/llm/infer/rollout.py", line 181, in update_flattened_params
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     self.model_runner.model.load_weights(weights=list(named_params.items()))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 712, in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return loader.load_weights(weights, mapper=self.hf_to_vllm_mapper)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 294,in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     autoloaded_weights = set(self._load_module("", self.module, weights))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 252,in _load_module
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     yield from self._load_module(prefix,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 225,in _load_module
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     loaded_params = module_load_weights(weights)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 626, in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return self._load_weights_mxfp4(ep_rank_end, ep_rank_start,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 452, in _load_weights_mxfp4
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     weight_loader(param,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] TypeError: default_weight_loader() got an unexpected keyword argument 'weight_name'
[ERROR:swift] Method execution failed: collective_rpc
Traceback (most recent call last):
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/llm/infer/rollout.py", line 262, in llm_worker
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 362, in collective_rpc
    return self.engine_core.collective_rpc(method, timeout, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 749, in collective_rpc
    return self.call_utility("collective_rpc", method, timeout, args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 697, in call_utility
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
Exception: Call to collective_rpc method failed: default_weight_loader() got an unexpected keyword argument 'weight_name'

INFO:     127.0.0.1:43474 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] Invocation of collective_rpc method failed
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] Traceback (most recent call last):
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 777, in _handle_client_request
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     result = method(*self._convert_msgspec_args(method, args))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 416, in collective_rpc
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return self.model_executor.collective_rpc(method, timeout, args,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 83, incollective_rpc
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return func(*args, **kwargs)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/llm/infer/rollout.py", line 181, in update_flattened_params
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     self.model_runner.model.load_weights(weights=list(named_params.items()))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 712, in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return loader.load_weights(weights, mapper=self.hf_to_vllm_mapper)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 294,in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     autoloaded_weights = set(self._load_module("", self.module, weights))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 252,in _load_module
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     yield from self._load_module(prefix,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 225,in _load_module
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     loaded_params = module_load_weights(weights)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 626, in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return self._load_weights_mxfp4(ep_rank_end, ep_rank_start,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 434, in _load_weights_mxfp4
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     weight_loader(param,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] TypeError: default_weight_loader() got an unexpected keyword argument 'weight_name'
[ERROR:swift] Method execution failed: collective_rpc
Traceback (most recent call last):
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/llm/infer/rollout.py", line 262, in llm_worker
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 362, in collective_rpc
    return self.engine_core.collective_rpc(method, timeout, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 749, in collective_rpc
    return self.call_utility("collective_rpc", method, timeout, args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 697, in call_utility
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
Exception: Call to collective_rpc method failed: default_weight_loader() got an unexpected keyword argument 'weight_name'

INFO:     127.0.0.1:43474 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] Invocation of collective_rpc method failed
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] Traceback (most recent call last):
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 777, in _handle_client_request
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     result = method(*self._convert_msgspec_args(method, args))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 416, in collective_rpc
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return self.model_executor.collective_rpc(method, timeout, args,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 83, incollective_rpc
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return func(*args, **kwargs)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/llm/infer/rollout.py", line 181, in update_flattened_params
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     self.model_runner.model.load_weights(weights=list(named_params.items()))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 712, in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return loader.load_weights(weights, mapper=self.hf_to_vllm_mapper)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 294,in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     autoloaded_weights = set(self._load_module("", self.module, weights))
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 252,in _load_module
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     yield from self._load_module(prefix,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 225,in _load_module
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     loaded_params = module_load_weights(weights)
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 626, in load_weights
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     return self._load_weights_mxfp4(ep_rank_end, ep_rank_start,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]   File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/model_executor/models/gpt_oss.py", line 452, in _load_weights_mxfp4
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780]     weight_loader(param,
(EngineCore_DP0 pid=292664) ERROR 01-02 11:34:17 [core.py:780] TypeError: default_weight_loader() got an unexpected keyword argument 'weight_name'
[ERROR:swift] Method execution failed: collective_rpc
Traceback (most recent call last):
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/llm/infer/rollout.py", line 262, in llm_worker
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 362, in collective_rpc
    return self.engine_core.collective_rpc(method, timeout, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 749, in collective_rpc
    return self.call_utility("collective_rpc", method, timeout, args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 697, in call_utility
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
Exception: Call to collective_rpc method failed: default_weight_loader() got an unexpected keyword argument 'weight_name'

INFO:     127.0.0.1:43474 - "POST /update_flattened_params/ HTTP/1.1" 200 OK
(EngineCore_DP0 pid=292664) INFO 01-02 11:34:18 [block_pool.py:378] Successfully reset prefix cache
INFO:     127.0.0.1:43474 - "POST /reset_prefix_cache/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:43474 - "POST /get_engine_type/ HTTP/1.1" 200 OK
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.55s/it]
INFO:     127.0.0.1:43474 - "POST /infer/ HTTP/1.1" 200 OK

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

【当前使用的虚拟环境】

ms-swift 3.12.0
transformer-engine 2.10
torch 2.8.0
trl 0.24.0
apex 0.1
Megatron-LM 0.15
CUDA 12.8

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

1. 将 softmax_type 设置为 vanilla 的原因。
   当在脚本中未明确指定 softmax_type 时，确认 softmax_type 会被默认设置为 learnable。
   在设置为 learnable 的情况下，会出现如下错误，因此将其明确指定为 vanilla。

```
[rank0]: Traceback (most recent call last): [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/cli/_megatron/rlhf.py", line 7, in <module> [rank0]: megatron_rlhf_main() [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/train/rlhf.py", line 78, in megatron_rlhf_main [rank0]: return MegatronRLHF(args).main() [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/llm/base.py", line 49, in main [rank0]: result = self.run() [rank0]: ^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/train/sft.py", line 77, in run [rank0]: self.trainer.train(train_dataset, val_dataset, data_collator) [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/trainers/grpo_trainer.py", line 69, in train [rank0]: super().train(train_dataset, val_dataset, data_collator) [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/trainers/base.py", line 1098, in train [rank0]: pretrain( [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/training/training.py", line 737, in pretrain [rank0]: iteration, num_floating_point_operations_so_far = train( [rank0]: ^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/training/training.py", line 2298, in train [rank0]: ) = train_step( [rank0]: ^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/trainers/base.py", line 564, in train_step [rank0]: new_data_iterator = self._replace_data_iterator(data_iterator, model) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/trainers/grpo_trainer.py", line 261, in _replace_data_iterator [rank0]: micro_batch_data = self._generate_and_score_completions(rollout_batch) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/trainers/grpo_trainer.py", line 401, in _generate_and_score_completions [rank0]: micro_batch_encoded = self._maybe_compute_logps(micro_batch_encoded) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/trainers/grpo_trainer.py", line 895, in _maybe_compute_logps [rank0]: ref_per_token_logps_raw = self.model_forward( [rank0]: ^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/trainers/grpo_trainer.py", line 1310, in model_forward [rank0]: output_tensor = forward_step_helper(model, data) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/utils/utils.py", line 310, in forward_step_helper [rank0]: output_tensor = model(**inputs) [rank0]: ^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/model/gpt_model.py", line 299, in forward [rank0]: hidden_states = self.decoder( [rank0]: ^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/transformer_block.py", line 553, in __call__ [rank0]: return super().__call__(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/module.py", line 305, in __call__ [rank0]: return super().__call__(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/transformer_block.py", line 697, in forward [rank0]: hidden_states, context = layer( [rank0]: ^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/transformer_layer.py", line 852, in __call__ [rank0]: return super().__call__(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/module.py", line 305, in __call__ [rank0]: return super().__call__(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/swift/megatron/init.py", line 544, in forward [rank0]: hidden_states, context = self._forward_attention(*_args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/transformer_layer.py", line 499, in _forward_attention [rank0]: attention_output_with_bias = self.self_attention( [rank0]: ^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/attention.py", line 866, in forward [rank0]: core_attn_out = self._checkpointed_attention_forward( [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/attention.py", line 253, in _checkpointed_attention_forward [rank0]: hidden_states = tensor_parallel.checkpoint( [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/tensor_parallel/random.py", line 480, in checkpoint [rank0]: return CheckpointFunction.apply(function, distribute_saved_activations, *args) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/autograd/function.py", line 576, in apply [rank0]: return super().apply(*args, **kwargs) # type: ignore[misc] [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/tensor_parallel/random.py", line 426, in forward [rank0]: outputs = run_function(*args) [rank0]: ^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/transformer/attention.py", line 239, in custom_forward [rank0]: output_ = self.core_attention( [rank0]: ^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/Megatron-LM/megatron/core/extensions/transformer_engine.py", line 1052, in forward [rank0]: core_attn_out = super().forward( [rank0]: ^^^^^^^^^^^^^^^^ [rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 198, in nonrecursive_disable_wrapper [rank0]: return fn(*args, **kwargs) [rank0]: ^^^^^^^^^^^^^^^^^^^
[rank0]: File "/home/jovyan/workspace/chanwoo/omniverse-pipeline/venv/think_megatron_train_dev/lib/python3.11/site-packages/transformer_engine/pytorch/attention/dot_product_attention/dot_product_attention.py", line 1397, in forward
[rank0]: raise ValueError(
[rank0]: ValueError: No dot product attention backend is available for the provided inputs. Please run with NVTE_DEBUG=1 NVTE_DEBUG_LEVEL=2 to find out the reasons for disabling all backends.
```

**Comment by akpe12** [comment]
@hjh0119 

为了解决该问题，我将分享我已确认的事项。

经确认，该问题似乎是由于通过 update_flattend_params 传递给 rollout server 的 flattened parameter，在 vLLM 中用于加载 weight 的 weight loader 不存在而导致的。

在通过 vllm serve 对模型进行服务时，我们确认在调用 update_flattend_params 时，同样是使用 _load_weights_mxfp4 来进行 weight 加载。

在检查 vllm serve 的运行行为时发现，在 gpt_oss.py 的 _load_weights_mxfp4 中，当加载通过 update_flattend_params 获取的 weight，且参数名中包含 “.w2_bias” 的参数时，期望的 weight_loader 应如下所示：
```
weight_loader type: <class 'method'>
weight_loader: <bound method FusedMoE.weight_loader of FusedMoE(
global_num_experts=128, local_num_experts=128, top_k=4, intermediate_size_per_partition=2944, tp_size=1, ep_size=1, reduce_results=True, renormalize=True, use_grouped_topk=False, scoring_func='softmax', activation='swigluoai')>
```

但是，在调用 update_flattend_params 之后进行 weight 加载时，实际情况如下：

```
weight_loader type: <class 'function'>
weight_loader: <function default_weight_loader at 0x7f18f59ad300>
```

**Comment by hjh0119** [comment]
maybe same issue https://github.com/volcengine/verl/issues/4110

**Comment by hjh0119** [comment]
Using the BF16 version of the model works for me.


```bash
    --model 'unsloth/gpt-oss-20b-BF16' \
    --model_type gpt_oss \
```

**Comment by akpe12** [comment]
在使用 bf16 模型时，我已经确认该问题得到了解决。
