### ISSUE TITLE
GRPO的vllm-server出现NCCL error

### ISSUE THREAD

**Issue by hajimi618** [modelscope/ms-swift#7879]
### Checklist / 检查清单

- [x] I have searched existing issues, and this is a new bug report. / 我已经搜索过现有的 issues，确认这是一个新的 bug report。

### Bug Description / Bug 描述

Node1代码:
CUDA_VISIBLE_DEVICES=3,4 \
python3 -m swift.cli.rollout \
    --model /Model/Qwen3-32B \
    --model_type qwen3 \
    --tensor_parallel_size 2

Node2关键代码:
swift rlhf \
    --rlhf_type grpo \
    --model /Model/Qwen3-32B \
    --model_type qwen3 \
    --use_vllm true \
    --vllm_device auto \
    --vllm_mode colocate \
    --vllm_server_host Node1-address \
    --vllm_server_port 8000 \

Node1一开始成功运行：
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

Node2运行之后卡住，而Node1报错：
INFO:     172.18.127.130:60808 - "GET /health/ HTTP/1.1" 200 OK
INFO:     172.18.127.130:60810 - "GET /get_world_size/ HTTP/1.1" 200 OK
INFO:     172.18.127.130:60812 - "POST /init_communicator/ HTTP/1.1" 200 OK
[rank1]:[W122 20:05:19.749124012 socket.cpp:204] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[rank0]:[W122 20:05:19.749490853 socket.cpp:204] [c10d] The hostname of the client socket cannot be retrieved. err=-3
(VllmWorker rank=1 pid=11606) INFO 01-22 20:05:19 [utils.py:990] Found nccl from library libnccl.so.2
(VllmWorker rank=1 pid=11606) INFO 01-22 20:05:19 [pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorker rank=0 pid=11566) INFO 01-22 20:05:19 [utils.py:990] Found nccl from library libnccl.so.2
(VllmWorker rank=0 pid=11566) INFO 01-22 20:05:19 [pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383] WorkerProc hit an exception: %s
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383] Traceback (most recent call last):
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]   File "/site-packages/vllm/v1/executor/multiproc_executor.py", line 376, in worker_busy_loop
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]     output = func(*args, **kwargs)
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]   File "/site-packages/trl/scripts/vllm_serve.py", line 108, in init_communicator
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]     self.pynccl_comm = PyNcclCommunicator(pg, device=self.device)
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]   File "/site-packages/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]   File "/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]   File "site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorker rank=1 pid=11606) ERROR 01-22 20:05:19 [multiproc_executor.py:383] RuntimeError: NCCL error: unhandled system error (run with NCCL_DEBUG=INFO for details)

### How to Reproduce / 如何复现

nvcc --version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

vllm: 0.8.3
transformers: 4.51.3
ms-swift: 3.5.0.dev0

**Comment by hjh0119** [comment]
plz retry with

pip install -U ms-swift

upgrade vllm to 0.11 / 0.13

**Comment by hajimi618** [comment]
你好，更新库版本并且将相应的运行脚本进行修改：

Node1代码:
CUDA_VISIBLE_DEVICES=3,4
python3 -m swift.cli.rollout
--model /Model/Qwen3-32B
--model_type qwen3
--vllm_tensor_parallel_size 2

Node2关键代码:
swift rlhf
--rlhf_type grpo
--model /Model/Qwen3-32B
--model_type qwen3
--use_vllm true
--vllm_mode server
--vllm_server_host Node1-address
--vllm_server_port 8000 \

Node2出现了新的报错：
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.18.127.130:40658 - "GET /health/ HTTP/1.1" 200 OK
INFO:     172.18.127.130:40660 - "POST /close_communicator/ HTTP/1.1" 200 OK
INFO:     172.18.127.130:40660 - "GET /get_world_size/ HTTP/1.1" 200 OK
INFO:     172.18.127.130:40660 - "POST /init_communicator/ HTTP/1.1" 200 OK
[rank1]:[W123 11:04:55.855742943 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[rank0]:[W123 11:04:55.856111010 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
(Worker_TP1 pid=14675) INFO 01-23 11:04:55 [__init__.py:1384] Found nccl from library libnccl.so.2
(Worker_TP1 pid=14675) INFO 01-23 11:04:55 [pynccl.py:103] vLLM is using nccl==2.27.3
(Worker_TP0 pid=14674) INFO 01-23 11:04:55 [__init__.py:1384] Found nccl from library libnccl.so.2
(Worker_TP0 pid=14674) INFO 01-23 11:04:55 [pynccl.py:103] vLLM is using nccl==2.27.3
(EngineCore_DP0 pid=14600) INFO 01-23 11:05:55 [shm_broadcast.py:466] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation).
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]   File "/site-packages/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]   File "/site-packages/trl/scripts/vllm_serve.py", line 108, in init_communicator
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]     self.pynccl_comm = PyNcclCommunicator(pg, device=self.device)
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]   File "/site-packages/vllm/distributed/device_communicators/pynccl.py", line 133, in __init__
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]   File "/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 324, in ncclCommInitRank
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]   File "/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 291, in NCCL_CHECK
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671]     raise RuntimeError(f"NCCL error: {error_str}")
(Worker_TP1 pid=14675) ERROR 01-23 11:06:18 [multiproc_executor.py:671] RuntimeError: NCCL error: remote process exited or there was a network error
(EngineCore_DP0 pid=14600) INFO 01-23 11:06:55 [shm_broadcast.py:466] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation).

**Comment by hjh0119** [comment]
检查nccl联通

**Comment by younengma** [comment]
这个问题后面有解决么？ 做OPSD碰到同样的问题。vllm的版本是0.13.0. ms-swift是4.1.1。
1. teacher 和student在不同的机器上
- 基于vllm rollout 部署会出现：
No available shared memory broadcast block found in 60 seconds。即使是很小的模型（4B）。
- 基于vllm serve 部署的模型两台机器之间调用是没问题的，说明nccl链接没问题

2. teacher 和student在同一台机器上
vllm rollout 可以正常跑

这应该是rollout的一个bug吧？

**Comment by hjh0119** [comment]
> 基于vllm serve 部署的模型两台机器之间调用是没问题的，说明nccl链接没问题

调用只需要网络连通

**Comment by younengma** [comment]
> > 基于vllm serve 部署的模型两台机器之间调用是没问题的，说明nccl链接没问题
> 
> 调用只需要网络连通
确实是nccl连接不上引起的。多谢
