### ISSUE TITLE
swift pt qwen3-0.6B报错，好像是dtype相关问题

### ISSUE THREAD

**Issue by hl0737** [modelscope/ms-swift#7998]
### Checklist / 检查清单

- [x] I have searched existing issues, and this is a new question or discussion topic. / 我已经搜索过现有的 issues，确认这是一个新的问题与讨论。

### Question Description / 问题描述

执行命令：`NPROC_PER_NODE=8 \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
swift pt \
    --model models/Qwen3-0.6B \
    --tuner_type full \
    --dataset output.jsonl \
    --torch_dtype bfloat16 \
    --streaming true \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 3e-4 \
    --gradient_accumulation_steps 8 \
    --packing false \
    --eval_steps 5000 \
    --save_steps 20 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --deepspeed zero3 \
    --max_length 2048 \
    --max_steps 5000 \
    --warmup_ratio 0.05 \
    --dataloader_num_workers 4 \
    --dataset_num_proc 8 \
    --save_only_model true \
    --output_dir output/qwen3-0.6b \
    --report_to none \
    --attn_impl flash_attn
`

遇到这个报错`[rank4]: Traceback (most recent call last):
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/cli/pt.py", line 7, in <module>
[rank4]:     pretrain_main()
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/pipelines/train/pretrain.py", line 17, in pretrain_main
[rank4]:     return SwiftPretrain(args).main()
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/pipelines/base.py", line 47, in main
[rank4]:     result = self.run()
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/ray/base.py", line 169, in wrapper
[rank4]:     return func(self, *args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/pipelines/train/sft.py", line 198, in run
[rank4]:     return self.train(trainer)
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/pipelines/train/sft.py", line 264, in train
[rank4]:     trainer.train(resume_checkpoint)
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/trainers/mixin.py", line 936, in train
[rank4]:     res = super().train(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2325, in train
[rank4]:     return inner_training_loop(
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 2674, in _inner_training_loop
[rank4]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/trainers/seq2seq_trainer.py", line 228, in training_step
[rank4]:     return super().training_step(model, inputs, *args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/trainer.py", line 4020, in training_step
[rank4]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/trainers/seq2seq_trainer.py", line 138, in compute_loss
[rank4]:     outputs = model(**inputs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1666, in forward
[rank4]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1492, in _run_ddp_forward
[rank4]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 819, in forward
[rank4]:     return model_forward(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/accelerate/utils/operations.py", line 807, in __call__
[rank4]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
[rank4]:     return func(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/generic.py", line 918, in wrapper
[rank4]:     output = func(self, *args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 480, in forward
[rank4]:     outputs: BaseModelOutputWithPast = self.model(
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/generic.py", line 1072, in wrapper
[rank4]:     outputs = func(self, *args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 410, in forward
[rank4]:     hidden_states = decoder_layer(
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/modeling_layers.py", line 93, in __call__
[rank4]:     return self._gradient_checkpointing_func(partial(super().__call__, **kwargs), *args)
[rank4]:   File "/data_genie/genie/liang.hu/ms-swift/swift/trainers/mixin.py", line 869, in _new_checkpoint
[rank4]:     return _old_checkpoint(*args, use_reentrant=use_reentrant_, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/_compile.py", line 54, in inner
[rank4]:     return disable_fn(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1181, in _fn
[rank4]:     return fn(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 512, in checkpoint
[rank4]:     ret = function(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank4]:     return func(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 260, in forward
[rank4]:     hidden_states, _ = self.self_attn(
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/utils/deprecation.py", line 172, in wrapped_func
[rank4]:     return func(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 200, in forward
[rank4]:     query_states = self.q_norm(self.q_proj(hidden_states).view(hidden_shape)).transpose(1, 2)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1787, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/data_genie/genie/liang.hu/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 134, in forward
[rank4]:     return F.linear(input, self.weight, self.bias)
[rank4]: RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16BF, lda, b, CUDA_R_16BF, ldb, &fbeta, c, std::is_same_v<C_Dtype, float> ? CUDA_R_32F : CUDA_R_16BF, ldc, compute_type, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
Train:   0%|          | 0/5000 [00:01<?, ?it/s]`

想请教下是为啥，cuda是12.9，pip安装的包如下

`(swift) root@/data_genie/genie/liang.hu> pip list
Package                       Version     Editable project location
----------------------------- ----------- -----------------------------------
absl-py                       2.4.0
accelerate                    1.12.0
addict                        2.4.0
aiofiles                      24.1.0
aiohappyeyeballs              2.6.1
aiohttp                       3.13.3
aiosignal                     1.4.0
aliyun-python-sdk-core        2.16.0
aliyun-python-sdk-kms         2.16.5
annotated-doc                 0.0.4
annotated-types               0.7.0
antlr4-python3-runtime        4.9.3
anyio                         4.12.1
async-timeout                 5.0.1
attrdict                      2.0.1
attrs                         25.4.0
binpacking                    2.0.1
brotli                        1.2.0
certifi                       2026.1.4
cffi                          2.0.0
charset-normalizer            3.4.4
click                         8.3.1
contourpy                     1.3.2
cpm-kernels                   1.0.11
crcmod                        1.7
cryptography                  46.0.4
cuda-bindings                 12.9.4
cuda-pathfinder               1.3.3
cycler                        0.12.1
dacite                        1.9.2
datasets                      3.6.0
deepspeed                     0.18.5
dill                          0.3.8
distro                        1.9.0
einops                        0.8.2
exceptiongroup                1.3.1
fastapi                       0.128.0
ffmpy                         1.0.0
filelock                      3.20.3
flash_attn                    2.8.3
fonttools                     4.61.1
frozenlist                    1.8.0
fsspec                        2025.3.0
gitdb                         4.0.12
GitPython                     3.1.46
gradio                        5.50.0
gradio_client                 1.14.0
groovy                        0.1.2
grpcio                        1.76.0
h11                           0.16.0
hf-xet                        1.2.0
hjson                         3.1.0
httpcore                      1.0.9
httpx                         0.28.1
huggingface_hub               0.36.1
idna                          3.11
importlib_metadata            8.7.1
jieba                         0.42.1
Jinja2                        3.1.6
jiter                         0.13.0
jmespath                      0.10.0
joblib                        1.5.3
json_repair                   0.56.0
kiwisolver                    1.4.9
Markdown                      3.10.1
markdown-it-py                4.0.0
MarkupSafe                    3.0.3
matplotlib                    3.10.8
mdurl                         0.1.2
modelscope                    1.34.0
mpmath                        1.3.0
ms_swift                      4.0.0.dev0  /data_genie/genie/liang.hu/ms-swift
msgpack                       1.1.2
multidict                     6.7.1
multiprocess                  0.70.16
networkx                      3.4.2
ninja                         1.13.0
nltk                          3.9.2
numpy                         2.2.6
nvidia-cublas-cu12            12.8.4.1
nvidia-cuda-cupti-cu12        12.8.90
nvidia-cuda-nvrtc-cu12        12.8.93
nvidia-cuda-runtime-cu12      12.8.90
nvidia-cudnn-cu12             9.10.2.21
nvidia-cufft-cu12             11.3.3.83
nvidia-cufile-cu12            1.13.1.3
nvidia-curand-cu12            10.3.9.90
nvidia-cusolver-cu12          11.7.3.90
nvidia-cusparse-cu12          12.5.8.93
nvidia-cusparselt-cu12        0.7.1
nvidia-nccl-cu12              2.27.5
nvidia-nvjitlink-cu12         12.8.93
nvidia-nvshmem-cu12           3.4.5
nvidia-nvtx-cu12              12.8.90
omegaconf                     2.3.0
openai                        2.16.0
orjson                        3.11.7
oss2                          2.19.1
packaging                     25.0
pandas                        2.3.3
peft                          0.18.1
pillow                        11.3.0
pip                           25.3
platformdirs                  4.5.1
propcache                     0.4.1
protobuf                      6.33.5
psutil                        7.2.2
py-cpuinfo                    9.0.0
pyarrow                       23.0.0
pycparser                     3.0
pycryptodome                  3.23.0
pydantic                      2.12.3
pydantic_core                 2.41.4
pydub                         0.25.1
Pygments                      2.19.2
pyparsing                     3.3.2
python-dateutil               2.9.0.post0
python-multipart              0.0.22
pytz                          2025.2
PyYAML                        6.0.3
regex                         2026.1.15
requests                      2.32.5
rich                          14.3.2
rouge                         1.0.1
ruff                          0.15.0
safehttpx                     0.1.7
safetensors                   0.7.0
scipy                         1.15.3
semantic-version              2.10.0
sentencepiece                 0.2.1
sentry-sdk                    2.52.0
setuptools                    80.10.2
shellingham                   1.5.4
simplejson                    3.20.2
six                           1.17.0
smmap                         5.0.2
sniffio                       1.3.1
sortedcontainers              2.4.0
starlette                     0.50.0
sympy                         1.14.0
tensorboard                   2.20.0
tensorboard-data-server       0.7.2
tiktoken                      0.12.0
tokenizers                    0.22.2
tomlkit                       0.13.3
torch                         2.10.0
tqdm                          4.67.3
transformers                  4.57.6
transformers-stream-generator 0.0.5
triton                        3.6.0
trl                           0.24.0
typer                         0.21.1
typing_extensions             4.15.0
typing-inspection             0.4.2
tzdata                        2025.3
urllib3                       2.6.3
uvicorn                       0.40.0
wandb                         0.24.2
websockets                    15.0.1
Werkzeug                      3.1.5
wheel                         0.46.3
xxhash                        3.6.0
yarl                          1.22.0
zipp                          3.23.0
zstandard                     0.25.0`

**Comment by AirAgentSDE** [comment]
我也遇到了这个问题，看到您已经关闭了issue，可以请问一下是什么原因以及如何解决吗？谢谢

**Comment by hl0737** [comment]
Cuda版本用12.8就好了，我之前是12.9，仅供参考



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2026年03月05日 18:30 |
| 收件人 | ***@***.***> |
| 抄送至 | Liang ***@***.***>、State ***@***.***> |
| 主题 | Re: [modelscope/ms-swift] swift pt qwen3-0.6B报错，好像是dtype相关问题 (Issue #7998) |
AirAgentSDE left a comment (modelscope/ms-swift#7998)

我也遇到了这个问题，看到您已经关闭了issue，可以请问一下是什么原因以及如何解决吗？谢谢
