### ISSUE TITLE
可以全量微调，但是lora微调报错

### ISSUE THREAD

**Issue by Eason51** [modelscope/ms-swift#8148]
### Checklist / 检查清单

- [x] I have searched existing issues, and this is a new question or discussion topic. / 我已经搜索过现有的 issues，确认这是一个新的问题与讨论。

### Question Description / 问题描述

跑主页的[demo](https://github.com/modelscope/ms-swift?tab=readme-ov-file#-quick-start)
ms-swift 版本：3.12.6
torch版本: 2.10.0
cuda版本: 12.9
已经确保了LD_LIBRARY_PATH指向了包含正确版本文件的路径

跑全量微调可以顺利运行
跑lora微调的时候会报错：
`RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

安装cuda_compat，并将LD_LIBRARY_PATH指向cuda_compat相关文件后，跑lora微调还是报错：
`RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by wanderHZ** [comment]
我在用Qwen/Qwen3.5-4B执行swift infer/eval 的时候也遇到了这个错误

<img width="1429" height="73" alt="Image" src="https://github.com/user-attachments/assets/e9fbb589-2283-4f5a-aaa8-094b4d29ef9d" />

**Comment by Eason51** [comment]
> 我在用Qwen/Qwen3.5-4B执行swift infer/eval 的时候也遇到了这个错误
> 
> <img alt="Image" width="1429" height="73" src="https://private-user-images.githubusercontent.com/85046267/557425035-e9fbb589-2283-4f5a-aaa8-094b4d29ef9d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzI2MTcwOTAsIm5iZiI6MTc3MjYxNjc5MCwicGF0aCI6Ii84NTA0NjI2Ny81NTc0MjUwMzUtZTlmYmI1ODktMjI4My00ZjVhLWFhYTgtMDk0YjRkMjllZjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzA0VDA5MzMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YzNmMzdiOTIwMDRkMzk5NTBlNWQ4YWU5MTFmNGIzMmUxMTMwOGMyZjUxNDUwOGIxY2MzMWM1YTJiZTI4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.viteetPg08rZWuRDcyAOStrbhyBP3YxH7zkEzk9xGEo">

换了cuda12.8和swift3.11.2之后解决了
