### ISSUE TITLE
[bug] GRPO trainer's sequence parallel seems ineffective & 30BA3B zero3_offload OOM

### ISSUE THREAD

**Issue by Tohrusky** [modelscope/ms-swift#9356]
### Checklist / 检查清单

- [x] I have searched existing issues, and this is a new bug report. / 我已经搜索过现有的 issues，确认这是一个新的 bug report。

### Bug Description / Bug 描述

机器 8*H00 80GB，任务需要上下文12k

SFT 开启序列并行=6，步数从 600 / 6卡 = 100 变成了 600 step，符合预期

但是 GRPO 开启 序列并行后，步数似乎没有按预期变长，具体如下：
序列并行不开启时候，600个sample，G=6，600 * G / 6卡 = 600 step
开启序列并行=6，还是 600 step

btw，下面这个脚本，换成`Qwen/Qwen3-Omni-30B-A3B-Instruct` 调训推分离的 grpo 一直 oom
开启 zero3_offload 也会 oom，6卡 sft 时候 开启 zero3_offload 每张卡只占 40GB，感觉显存应该是够的

### How to Reproduce / 如何复现

```
lint:
	uv run --no-sync pre-commit install --install-hooks 2>/dev/null || true
	uv run --no-sync pre-commit run --all-files


# BASE_MODEL = Qwen/Qwen3-Omni-30B-A3B-Instruct
BASE_MODEL = Qwen/Qwen3-4B


sft:
	CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 \
	NPROC_PER_NODE=6 \
	uv run --no-sync swift sft \
	--model $(BASE_MODEL) \
	--tuner_type full \
	--torch_dtype bfloat16 \
	--dataset AI-MO/NuminaMath-TIR#600 \
	--num_train_epochs 1 \
	--per_device_train_batch_size 1 \
	--gradient_accumulation_steps 1 \
	--sequence_parallel_size 6 \
	--padding_free true \
	--attn_impl flash_attention_2 \
	--learning_rate 1e-5 \
	--warmup_ratio 0.05 \
	--lr_scheduler_type cosine \
	--save_steps 250 \
	--save_total_limit 50 \
	--logging_steps 1 \
	--max_length 12000 \
	--output_dir $(BASE_MODEL)_sft \
	--dataloader_num_workers 8 \
	--dataset_num_proc 8 \
	--deepspeed zero3 \
	--report_to tensorboard \
	--use_hf true

rollout:
	CUDA_VISIBLE_DEVICES=6,7 \
	uv run --no-sync swift rollout \
	--model $(BASE_MODEL) \
	--vllm_max_model_len 12000 \
	--vllm_gpu_memory_utilization 0.90 \
	--vllm_tensor_parallel_size 2 \
	--vllm_data_parallel_size 1 \
	--vllm_enable_prefix_caching False \
	--use_hf true

train:
	CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 \
	NPROC_PER_NODE=6 \
	uv run --no-sync swift rlhf \
	--rlhf_type grpo \
	--model $(BASE_MODEL) \
	--tuner_type full \
	--torch_dtype bfloat16 \
	--dataset AI-MO/NuminaMath-TIR#600 \
	--reward_funcs format \
	--reward_weights 1 \
	--use_vllm true \
	--vllm_mode server \
	--vllm_server_host 127.0.0.1 \
	--vllm_server_port 8000 \
	--max_length 12000 \
	--max_completion_length 512 \
	--loss_type grpo \
	--importance_sampling_level sequence \
	--beta 0.0 \
	--epsilon 3e-4 \
	--epsilon_high 4e-4 \
	--num_iterations 1 \
	--num_train_epochs 1 \
	--per_device_train_batch_size 1 \
	--gradient_accumulation_steps 1 \
	--sequence_parallel_size 6 \
	--padding_free true \
	--attn_impl flash_attention_2 \
	--overlong_filter True \
	--generation_batch_size 24 \
	--num_generations 6 \
	--temperature 1 \
	--learning_rate 1e-6 \
	--warmup_ratio 0.05 \
	--lr_scheduler_type cosine \
	--save_steps 200 \
	--save_total_limit 50 \
	--logging_steps 1 \
	--output_dir $(BASE_MODEL)_rl \
	--dataloader_num_workers 8 \
	--dataset_num_proc 8 \
	--log_completions true \
	--log_entropy false \
	--deepspeed zero3 \
	--report_to tensorboard \
	--use_hf true

```

### OOM

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/cli/rlhf.py", line 7, in <module>
[rank0]:     rlhf_main()
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/pipelines/train/rlhf.py", line 246, in rlhf_main
[rank0]:     return SwiftRLHF(args).main()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/pipelines/base.py", line 52, in main
[rank0]:     result = self.run()
[rank0]:              ^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/ray/base.py", line 168, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/pipelines/train/sft.py", line 197, in run
[rank0]:     return self.train(trainer)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/pipelines/train/sft.py", line 271, in train
[rank0]:     trainer.train(resume_checkpoint)
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/trainers/mixin.py", line 903, in train
[rank0]:     res = super().train(*args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 1427, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 1509, in _inner_training_loop
[rank0]:     self._run_epoch(
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 1737, in _run_epoch
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/grpo_trainer.py", line 1852, in training_step
[rank0]:     return super().training_step(model, inputs, num_items_in_batch)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/trl/trainer/grpo_trainer.py", line 1085, in training_step
[rank0]:     output = super().training_step(model, inputs, num_items_in_batch)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 1903, in training_step
[rank0]:     inputs = self._prepare_inputs(inputs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/utils.py", line 613, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/grpo_trainer.py", line 206, in _prepare_inputs
[rank0]:     generation_batch = self._generate_and_score_completions(generation_batch)
[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/utils.py", line 613, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/grpo_trainer.py", line 238, in _generate_and_score_completions
[rank0]:     inputs = self._generate_completions(inputs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/grpo_trainer.py", line 219, in _generate_completions
[rank0]:     results = self._fast_infer(inputs)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/rollout_mixin.py", line 1063, in _fast_infer
[rank0]:     self._move_model_to_vllm()
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/utils.py", line 613, in wrapper
[rank0]:     return func(self, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/rollout_mixin.py", line 452, in _move_model_to_vllm
[rank0]:     self._move_full_model_to_vllm()
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/swift/rlhf_trainers/rollout_mixin.py", line 774, in _move_full_model_to_vllm
[rank0]:     with gather_if_zero3(parameters):
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 2331, in __enter__
[rank0]:     self.params[0].all_gather(param_list=self.params)
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1231, in all_gather
[rank0]:     return self._all_gather(param_list, async_op=async_op, hierarchy=hierarchy)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/deepspeed/utils/nvtx.py", line 33, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1636, in _all_gather
[rank0]:     self._allgather_params_coalesced(all_gather_nonquantize_list, hierarchy, quantize=False)
[rank0]:   File "/myproject/.venv/lib/python3.12/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1927, in _allgather_params_coalesced
[rank0]:     flat_tensor = torch.empty(tensor_size, dtype=param_list[0].ds_tensor.dtype,
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 768.00 MiB. GPU 0 has a total capacity of 79.11 GiB of which 327.38 MiB is free. Process 3263317 has 1.10 GiB memory in use. Process 20821 has 77.66 GiB memory in use. Of the allocated memory 74.73 GiB is allocated by PyTorch, and 80.05 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank2]:[W515 10:19:45.688021006 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[rank4]:[W515 10:19:45.740893619 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[rank5]:[W515 10:19:45.913089280 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[rank1]:[W515 10:19:46.277838705 ProcessGroupNCCL.cpp:1553] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Train:   0%|          | 0/600 [00:02<?, ?it/s] 
```

### 环境

最新commit ms-swift

``` 
uv pip list
Package                                  Version
---------------------------------------- --------------------
abnf                                     2.2.0
absl-py                                  2.4.0
accelerate                               1.13.0
addict                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.5
aiosignal                                1.4.0
aliyun-python-sdk-core                   2.16.0
aliyun-python-sdk-kms                    2.16.5
annotated-doc                            0.0.4
annotated-types                          0.7.0
anthropic                                0.102.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.13.0
apache-tvm-ffi                           0.1.11
ast-serialize                            0.4.0
astor                                    0.8.1
attrdict                                 2.0.1
attrs                                    26.1.0
audioread                                3.1.0
av                                       17.0.1
backoff                                  2.2.1
binpacking                               2.0.1
bitsandbytes                             0.49.2
blake3                                   1.0.8
brotli                                   1.2.0
cachetools                               7.1.1
cbor2                                    6.1.1
certifi                                  2026.4.22
cffi                                     2.0.0
cfgv                                     3.5.0
chardet                                  7.4.3
charset-normalizer                       3.4.7
cint                                     1.0.0
click                                    8.3.3
cloudpickle                              3.1.2
compressed-tensors                       0.15.0.1
contourpy                                1.3.3
coverage                                 7.14.0
cpm-kernels                              1.0.11
crcmod                                   1.7
cryptography                             48.0.0
cuda-bindings                            12.9.4
cuda-pathfinder                          1.5.4
cuda-python                              12.9.4
cycler                                   0.12.1
dacite                                   1.9.2
datasets                                 4.8.4
decorator                                5.2.1
decord                                   0.6.0
deepspeed                                0.19.0
depyf                                    0.20.0
dill                                     0.4.1
diskcache                                5.6.3
diskcache-weave                          5.6.3.post1
distlib                                  0.4.0
distro                                   1.9.0
dnspython                                2.8.0
docstring-parser                         0.18.0
einops                                   0.8.2
email-validator                          2.3.0
fastapi                                  0.136.1
fastapi-cli                              0.0.24
fastapi-cloud-cli                        0.17.1
fastar                                   0.11.0
ffmpy                                    1.0.0
fickling                                 0.1.11
filelock                                 3.29.0
fla-core                                 0.4.2
flash-attn                               2.8.3+cu128torch2.10
flash-linear-attention                   0.4.2
flashinfer-cubin                         0.6.6
flashinfer-python                        0.6.6
fonttools                                4.63.0
frozenlist                               1.8.0
fsspec                                   2026.2.0
gguf                                     0.19.0
gitdb                                    4.0.12
gitpython                                3.1.50
googleapis-common-protos                 1.75.0
gql                                      4.0.0
gradio                                   5.50.0
gradio-client                            1.14.0
graphql-core                             3.2.8
graphviz                                 0.21
groovy                                   0.1.2
grpcio                                   1.80.0
h11                                      0.16.0
hf-xet                                   1.5.0
hjson                                    3.1.0
httpcore                                 1.0.9
httptools                                0.7.1
httpx                                    0.28.1
httpx-sse                                0.4.3
huggingface-hub                          1.14.0
identify                                 2.6.19
idna                                     3.15
ijson                                    3.5.0
importlib-metadata                       8.7.1
iniconfig                                2.3.0
interegular                              0.3.3
intervaltree                             3.2.1
jinja2                                   3.1.6
jiter                                    0.14.0
jmespath                                 0.10.0
joblib                                   1.5.3
json-repair                              0.59.10
jsonschema                               4.26.0
jsonschema-specifications                2025.9.1
kaitaistruct                             0.11
kiwisolver                               1.5.0
lark                                     1.2.2
latex2sympy2-extended                    1.11.0
lazy-loader                              0.5
librosa                                  0.11.0
librt                                    0.11.0
llguidance                               1.3.0
llvmlite                                 0.44.0
lm-format-enforcer                       0.11.3
loguru                                   0.7.3
markdown                                 3.10.2
markdown-it-py                           4.2.0
markupsafe                               3.0.3
math-verify                              0.9.0
matplotlib                               3.10.9
mcp                                      1.27.1
mdurl                                    0.1.2
mistral-common                           1.11.2
model-hosting-container-standards        0.1.15
modelscope                               1.36.3
mpmath                                   1.3.0
ms-swift                                 4.3.0.dev0
msgpack                                  1.1.2
msgspec                                  0.21.1
multidict                                6.7.1
multiprocess                             0.70.19
mypy                                     2.1.0
mypy-extensions                          1.1.0
networkx                                 3.6.1
ninja                                    1.13.0
nltk                                     3.9.4
nodeenv                                  1.10.0
numba                                    0.61.2
numpy                                    2.2.6
nvidia-cublas-cu12                       12.9.1.4
nvidia-cuda-cupti-cu12                   12.9.79
nvidia-cuda-nvrtc-cu12                   12.9.86
nvidia-cuda-runtime-cu12                 12.9.79
nvidia-cudnn-cu12                        9.10.2.21
nvidia-cudnn-frontend                    1.18.0
nvidia-cufft-cu12                        11.4.1.4
nvidia-cufile-cu12                       1.14.1.1
nvidia-curand-cu12                       10.3.10.19
nvidia-cusolver-cu12                     11.7.5.82
nvidia-cusparse-cu12                     12.5.10.65
nvidia-cusparselt-cu12                   0.7.1
nvidia-cutlass-dsl                       4.5.0
nvidia-cutlass-dsl-libs-base             4.5.0
nvidia-ml-py                             13.595.45
nvidia-nccl-cu12                         2.27.5
nvidia-nvjitlink-cu12                    12.9.86
nvidia-nvshmem-cu12                      3.4.5
nvidia-nvtx-cu12                         12.9.79
omegaconf                                2.3.0
openai                                   2.36.0
openai-harmony                           0.0.8
opencv-python-headless                   4.13.0.92
opentelemetry-api                        1.41.1
opentelemetry-exporter-otlp              1.41.1
opentelemetry-exporter-otlp-proto-common 1.41.1
opentelemetry-exporter-otlp-proto-grpc   1.41.1
opentelemetry-exporter-otlp-proto-http   1.41.1
opentelemetry-proto                      1.41.1
opentelemetry-sdk                        1.41.1
opentelemetry-semantic-conventions       0.62b1
opentelemetry-semantic-conventions-ai    0.5.1
orjson                                   3.11.9
oss2                                     2.19.1
outlines-core                            0.2.11
packaging                                26.2
pandas                                   2.3.3
partial-json-parser                      0.2.1.1.post7
pathspec                                 1.1.1
pdfminer-six                             20260107
peft                                     0.18.1
pillow                                   11.3.0
platformdirs                             4.9.6
pluggy                                   1.6.0
polyfile-weave                           0.5.9
pooch                                    1.9.0
pre-commit                               4.6.0
prometheus-client                        0.25.0
prometheus-fastapi-instrumentator        7.1.0
propcache                                0.5.2
protobuf                                 6.33.6
psutil                                   7.2.2
py-cpuinfo                               9.0.0
pyarrow                                  24.0.0
pybase64                                 1.4.3
pycountry                                26.2.16
pycparser                                3.0
pycryptodome                             3.23.0
pydantic                                 2.12.3
pydantic-core                            2.41.4
pydantic-extra-types                     2.11.1
pydantic-settings                        2.14.1
pydub                                    0.25.1
pygments                                 2.20.0
pyjwt                                    2.12.1
pyparsing                                3.3.2
pytest                                   9.0.3
pytest-cov                               7.1.0
python-dateutil                          2.9.0.post0
python-discovery                         1.3.1
python-dotenv                            1.2.2
python-json-logger                       4.1.0
python-multipart                         0.0.28
pytz                                     2026.2
pyyaml                                   6.0.3
pyzmq                                    27.1.0
quack-kernels                            0.4.1
qwen-omni-utils                          0.0.9
qwen-vl-utils                            0.0.14
referencing                              0.37.0
regex                                    2026.5.9
requests                                 2.34.2
rich                                     15.0.0
rich-toolkit                             0.19.9
rignore                                  0.7.6
rouge                                    1.0.1
rpds-py                                  0.30.0
ruff                                     0.15.13
safehttpx                                0.1.7
safetensors                              0.7.0
scikit-learn                             1.8.0
scipy                                    1.17.1
semantic-version                         2.10.0
sentencepiece                            0.2.1
sentry-sdk                               2.60.0
setproctitle                             1.3.7
setuptools                               80.10.2
shellingham                              1.5.4
simplejson                               4.1.1
six                                      1.17.0
smmap                                    5.0.3
sniffio                                  1.3.1
sortedcontainers                         2.4.0
soundfile                                0.13.1
soxr                                     1.1.0
sse-starlette                            3.4.4
starlette                                0.52.1
supervisor                               4.3.0
sympy                                    1.14.0
tabulate                                 0.10.0
tenacity                                 9.1.4
tensorboard                              2.20.0
tensorboard-data-server                  0.7.2
threadpoolctl                            3.6.0
tiktoken                                 0.13.0
tokenizers                               0.22.2
tomlkit                                  0.13.3
torch                                    2.10.0+cu129
torch-c-dlpack-ext                       0.1.5
torchaudio                               2.10.0+cu129
torchvision                              0.25.0+cu129
tqdm                                     4.67.3
transformers                             5.8.1
transformers-stream-generator            0.0.5
triton                                   3.6.0
trl                                      0.29.1
typer                                    0.25.1
typing-extensions                        4.15.0
typing-inspection                        0.4.2
tzdata                                   2026.2
urllib3                                  2.7.0
uvicorn                                  0.47.0
uvloop                                   0.22.1
virtualenv                               21.3.3
vllm                                     0.19.1
wandb                                    0.27.0
watchfiles                               1.1.1
weave                                    0.52.40
websockets                               15.0.1
werkzeug                                 3.1.8
xgrammar                                 0.2.0
xxhash                                   3.7.0
yarl                                     1.23.0
zipp                                     3.23.1
zstandard                                0.25.0
```

**Comment by hjh0119** [comment]
Set `move_model_batches` to avoid OOM caused by gathering the entire model at once

**Comment by Tohrusky** [comment]
> Set `move_model_batches` to avoid OOM caused by gathering the entire model at once

@hjh0119 

After set `move_model_batches 10`, it works! 💗

However, when I set `sequence_parallel 6`, the training steps remain the same as before.

**Comment by hjh0119** [comment]
GRPO consists of two phases: rollout and training. 

When SP is enabled, it is only applied to the training side. Due to sequence splitting, SP implicitly reduces the effective batch size during training. To ensure that rollout data is consumed at a consistent rate, the design here is to scale up `gradient_accumulation_steps` so that both SP and non-SP settings consume the same amount of rollout data within a single gradient update step.

https://github.com/modelscope/ms-swift/blob/v4.2.0/swift/rlhf_trainers/grpo_trainer.py#L151-L152

**Comment by Tohrusky** [comment]
gotcha~

**Comment by LukeLIN-web** [comment]
How long it need to train? I find many paper use 32 A100 .

**Comment by Tohrusky** [comment]
> How long it need to train? I find many paper use 32 A100 . 

I just use 8 gpus to debug...

In this demo config, around 6-9 hours for 600samples?

**Comment by LukeLIN-web** [comment]
> > How long it need to train? I find many paper use 32 A100 .
> 
> I just use 8 gpus to debug...
> 
> In this demo config, around 6-9 hours for 600samples?

orz， it is really consuming, thank you.
